### ISSUE TITLE
Create test GEDCOM

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#100]
For testing purposes, we should have a GEDCOM that can be loaded for testing. It should have a range of scenarios we can use to test to make sure the correct individuals and families are included for various settings.

This GEDCOM should have an accompanying list of scenarios so that we can see what scenarios are included and which records are used for the scenario.

**Comment by hartenthaler** [comment]
There is a GEDCOM test suite (but it is in German): [GEDCOM Storyboard](https://wiki.genealogy.net/GEDCOM_Musterdatei/Storyboard) and [GEDCOM test file](https://wiki.genealogy.net/GEDCOM_Musterdatei/Musterdatei). Maybe this goes in the direction you are thinking of.

**Comment by Neriderc** [comment]
Yes, that sort of thing!

I'd like to go one step further, outlining _test scenarios_ that the records fulfill.

For example, scenarios could be as follows:
- Step brother
- Spouse of ex-spouse
- Mother of step child

Then you'd have records that fulfill these scenarios:
- Individual X123 is step brother of X143
- Individual X958 is mother of X987 who is ex-spouse of X478
- Individual X45 step mother of X65

And a matching GEDCOM that holds these records.

Then if you were testing something, you could look at the scenario list to find what you needed to test. If it wasn't there you'd know you need to add another record to the test data.

I had originally thought of adding files to the repository, but looking at what you have there I'm thinking maybe something similar in the repo wiki would do. I might start a small page and build on it if the format seems to work.

**Comment by Neriderc** [comment]
I'm going to close this. I have created a [set of test data](https://github.com/Neriderc/GVExport/wiki/Test-data). It's limited currently but I will add scenarios as needed and grow the GEDCOM. I think the intention of this story is fulfilled.
