### ISSUE TITLE
Check blood relative status of adopted children and partners outside displayed tree

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#109]
Currently, adopted children and partners are shown as non-blood relatives (if option selected to show this in a different colour), unless a relative link is found in the displayed tree, in which case they are shown as related.

It is possible that an adopted child has been adopted from elsewhere in the family. E.g. a child being adopted by their biological uncle. Or that a partner is related, possibly distantly.

In this case, currently the record is only shown as related if this link is displayed in the diagram (i.e. uncle's parents and siblings). If this link is not displayed, then the adopted child or partner will be shown as non-related as scanning the records in the tree did not find a link.

If there is a link in the tree, then the child or partner should still be displayed as related even if the link is not shown in the diagram.

To do this, we should build an array of related records by scanning the tree starting from the initial individuals and ignoring any limits. Then compare this full list of relatives against the individuals in our diagram.

If practical, we should only do this scanning in the case it is required - i.e. a non-related adopted child is found in the tree or the "spouses" option is enabled.

See #36 for more discussion on this.

**Comment by hartenthaler** [comment]
... and you have to do the scanning for all partners, if there are partners found in the tree.

**Comment by Neriderc** [comment]
> ... and you have to do the scanning for all partners, if there are partners found in the tree.

Do we? If partners are not related, why do we need to scan their families?

**Comment by hartenthaler** [comment]
Normally you can assume that a partner is not related. But there are several examples in my tree where the wife of a husband was his second or third or more distant cousin.

**Comment by Neriderc** [comment]
Ah I think that's fine. All we would be looking to do is create an array of individual XREFs for comparing against. We shouldn't need to follow partner links as these relative-partners would be added to the array when tracing back through the relatives.

**Comment by hartenthaler** [comment]
Correct! But it is necessary to build up this array of INDI XREFs if a non-related adopted child is found in the tree *or* a partner is found in the tree.

**Comment by Neriderc** [comment]
Ah I see what you're getting at! You're right, that would also be necessary. I will edit the issue to clarify this.

**Comment by hartenthaler** [comment]
Yes! That is it!
