### ISSUE TITLE
Create "toast" message system

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#110]
Currently we don't have a way of providing information to the user.

As a first step towards this, we will create a toast system. This would provide a pop-up message in the bottom right of the screen.

For our initial implementation, we should have two message scenarios:

1. In #36, there is the potential for an adopted child to be marked as non-related if the displayed tree does not show the link. This is also possible for a related partner. We should add a warning to the user if a non-related adopted child or partner is shown in the tree. 
2. When the browser render is updated or the output downloaded, a message should show in the corner to indicate it has completed and to tell the user how many records have been included (X individuals and X family records).

**Comment by hartenthaler** [comment]
From my point of view you should show the warning in your scenario 1 not only if a non-related adopted child is shown in the tree but also if a non-related partner is shown in the tree.

**Comment by Neriderc** [comment]
I have updated it. I guess this warning could be shown for partners whenever "spouses" is selected in the settings. But for that situation a toast is not really the right way to give the warning. But it would do for now as this should only be a temporary thing until the other issue is solved.

**Comment by Neriderc** [comment]
I've merged in #120 which adds a (basic) toast system and implements number 2 from the list.

For number 1, I'll look at this a bit later (or perhaps not at all, if I can get to #109 soon).

**Comment by Neriderc** [comment]
Closing this as #109 completed. Translation was added to toast in #127, so everything here is complete.
