### ISSUE TITLE
Bugs with GVE 2.1.6 and PHP 7.4.30

### ISSUE THREAD

**Issue by schuco** [Neriderc/GVExport#116]
Maybe due to my outdated php 7.4.30 I get following errors:
1. The "X" to remove the input menu does not react
2. The preview works with selection no ancestors and no descendants.
Otherwise I get the error displayed in the screenshots. The list is not fully readable due to the "X"-bug (see 1.)
I still use webtrees 2.1.6 as the vesta-modules are not yet updated to wt 2.1.7
![GVE Screenshot2](https://user-images.githubusercontent.com/5896925/183889553-82b62de3-9490-4206-af27-f069923e0a57.png)
![GVE Screenshot1](https://user-images.githubusercontent.com/5896925/183889558-2d7fe92c-633b-46f2-b528-e8f4a30937e2.png)

**Comment by Neriderc** [comment]
Could you click the "reset" button? When upgrading my production server I saw the same issue but resetting the settings fixed it.

**Comment by schuco** [comment]
After reinstalling GVE 2.1.6 I could not even observe the reported error 2 once  more.

The error 1 regarding "X" disappeared after Reset.

After that I tried a bit around setting different selections for ancestors and descendants.
Setting include ancestors and leaving the field max generations blanks produced the following error. This is not really a bug, as a numeric value can be expected setting include ancestors.

Thank you @Neriderc for fast reaction and solution of the problem!
![Firefox_Screenshot_2022-08-11T07-51-49 406Z](https://user-images.githubusercontent.com/5896925/184089021-1a18f79e-67dd-45bb-9c62-968fbfdd8d3a.png)

**Comment by Neriderc** [comment]
No problem! I wish there were no problems but a quick resolution is a good second option :slightly_smiling_face:
