### ISSUE TITLE
color of blood-related ancestor is wrong

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#117]
Using the latest release 2.1.6 of GVExport I observed in my tree that an ancestor of a starting person has the wrong colour.
![Screenshot (226)](https://user-images.githubusercontent.com/6324175/184027120-389a49c6-b42c-4776-a410-76f8f13b03be.png)
The top left person "Josef Baumgärtner" is an ancestor of the left starting person (at the bottom of the diagram. The two starting persons are married and related together.

Implementing #109 will solve this problem.

**Comment by hartenthaler** [comment]
I assume that the reason is that the son Kaspar Baumgärtner (I61) is set as a stopping person. I assume that this is also the reason for the link to the family F1395 that should not be there. F1395 is the second family of Kaspar Baumgärtner with his second wife. Because Kaspar is a stopping person his second wife is not included, which is correct. But then the link to the family should not be there, too.

**Comment by Neriderc** [comment]
https://github.com/Neriderc/GVExport/issues/109 has been completed so this should be resolved in the next release. I'll close for now but if you still experience the issue we can reopen.
