### ISSUE TITLE
Error when no data in max level field

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#118]
I observed this error only one time and could not reproduce it afterwards.
![Screenshot (225)](https://user-images.githubusercontent.com/6324175/184029677-b0e2b643-2b2e-4963-a8e4-2608dc8b3dbf.png)

**Comment by Neriderc** [comment]
I think I know the cause. If you don't enter anything in the box for max level of descendants, I get this exact error message.

It's easy enough to check for but I think this is part of a wider piece of work on validation, as mentioned in #38.

In this case, I think if you enter nothing in the box, then we should either set it to 0 or to the default value using javascript. Most likely setting it to 0 would be easiest.

**Comment by hartenthaler** [comment]
Yes, that is the reason.

**Comment by Neriderc** [comment]
Great, we'll leave this open to track adding validation to that field.
