### ISSUE TITLE
2.1.2 - Missing translation for 'Warning'

### ISSUE THREAD

**Issue by TheDutchJewel** [Neriderc/GVExport#119]
There is a missing translation for 'Warning':
![afbeelding](https://user-images.githubusercontent.com/46184729/184085224-7d171225-3a80-4bb0-8095-79537be459f7.png)

**Comment by Neriderc** [comment]
Thanks for spotting this! I have added the term to POEditor so translations can be added.

I'll also need to do a code change, as this term isn't included in the translation code (so even if we update the translation list, it won't actually show). I'll do this change before the next release.

**Comment by Neriderc** [comment]
Done in #121, is now available on master branch and will be in next release.
