### ISSUE TITLE
colour of non-blood-related ancestors of foster children is wrong

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#123]
Since the last version of GVExport, the colour of the ancestors of adopted children is set to "non-blood-related", which is correct in most cases. But the colour of the ancestors of foster children is still wrong.

There are the following cases for the PEDIGREE_LINKAGE_TYPE
- child is a biological child: status is not defined or BIRTH
- child is not a biological child: status is ADOPTED or FOSTER or SEALING or RADA (RADA is only used in webtrees, not in the GEDCOM standard)

Implementing #109 would solve this issue.

**Comment by schuco** [comment]
I observed that the biological parents of my adopted grandfather were colored "non-blood-related".
After I rearranged the biological family first and thereafter the adopting family colors were correct.

**Comment by Neriderc** [comment]
> I observed that the biological parents of my adopted grandfather were colored "non-blood-related". After I rearranged the biological family first and thereafter the adopting family colors were correct.

This is interesting. I'm keen on getting #109 completed as there are a lot of colouring issues that may be solved by it, and it would be interesting to see if it works for this too. 

It's interesting to me that biological parents are shown as non-related as the code looks for the adopted link in the GEDCOM for the family (with the parents) to decide not to set them as related. If this child does not have an adopt link to the family with the biological parents then it's quite unusual that they would be shown as non-related.

**Comment by schuco** [comment]
Let me add further info which may explain for experts unlike me the inconsistent handling of biological and adoption parents.
This is part of the GEDCOM of the adopted child (my grandfather) AFTER I had rearranged biological family first:

**1 FAMC @F188@
2 _PRIMARY Y
1 FAMC @F197@
2 PEDI adopted
1 ADOP
2 FAMC @F197@
3 ADOP BOTH
2 DATE 21 JAN 1909
2 PLAC Dorstfeld
2 OBJE @M1068@**

This is from the biological parents Pedigree:
**1 CHIL @I1159@
2 PEDI**

and this from adopting family
**1 CHIL @I1159@
2 ADOP**

I do not understand if it is necessary in the individuals GEDCOM to have both, 
1 FAMC @F197@ with 2 PEDI adopted
and 
1 ADOP with 2 FAMC @F197@ and 3 ADOP BOTH

**Comment by Neriderc** [comment]
#109 has been completed so this should be resolved in the next release. I'll close for now but if you still experience the issue we can reopen.
