### ISSUE TITLE
Grandparents of adopted children are incomplete

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#124]
I have an adopted boy in my tree (adopted by his father and mother).

When selecting "ancestors" and "partner" only the grandparents of the father's side are found, the parents of the mother are not shown anymore. Very strange.

When deselecting "partner" everything is ok. The option "partner" should not make any difference in this scenario. The adopted boy has a foster sister. For her, anything is ok (selecting partner does not matter).

**Comment by Neriderc** [comment]
Interesting! I suspect that when I added the non-relative status for adopted children, this has caught some logic that doesn't trigger the next step for non-related partners. I'll look into this.

**Comment by hartenthaler** [comment]
This is fixed for adopted children as starting person.

But if the starting person is a foster child, then the parents of the foster father are shown, but not the parents of the foster mother.

**Comment by Neriderc** [comment]
In my test case here, Tony at top right is a foster child, and both foster parents have their parents shown:
![image](https://user-images.githubusercontent.com/89974636/188342472-b6d8cb41-e8f9-49c6-a504-c4b98d576759.png)

Do you have any more info on what settings you are using that may cause this?

**Comment by hartenthaler** [comment]
I don't know what was the difference. But with your latest fix this issue was solved, too.
