### ISSUE TITLE
Error in GVE 2.1.7 when muliple asterisks are used for preferred parts of the name

### ISSUE THREAD

**Issue by schuco** [Neriderc/GVExport#129]
Displaying just my maternal grandfather (no ancestors, descendants, spouses selected) I get:

**serverside rendering:**
_Error (return code 1) executing command "/usr/bin/dot -Tpdf -o/tmp/c4ca4238a0b923820dcc509a6f75849b/gvexport.pdf /tmp/c4ca4238a0b923820dcc509a6f75849b/gvexport.dot" in "/var/www/vhosts/schulte-coerne.de/brandneu.schulte-coerne.de".
Check path and Graphviz functionality!

Error: mismatched tag in line 1
... Reddemann (I166) ...
in label of node I166_

**Browser:**
![Firefox_Screenshot_2022-08-12T09-48-11 394Z](https://user-images.githubusercontent.com/5896925/184330604-29558964-cd6c-4ba0-8279-21966d002c40.png)
![Firefox_Screenshot_2022-08-12T09-48-49 175Z](https://user-images.githubusercontent.com/5896925/184330601-5af6bfcd-af8a-4486-b5c1-50855134c795.png)
![Firefox_Screenshot_2022-08-12T09-49-20 328Z](https://user-images.githubusercontent.com/5896925/184330598-a4c8cc39-7265-482e-987e-422c78fe6b6b.png)
![Firefox_Screenshot_2022-08-12T09-51-44 326Z](https://user-images.githubusercontent.com/5896925/184330592-67a2dabf-bfe2-4900-9701-a5a9aa9db558.png)

I observed this error only displaying this special person. His name is quite long, you see it takes 4 screenshots to show the node label.

Meanwhile I have looked into the GEDCOM of I166:

the Name-section was
**1 NAME Hermann* Josef Julius /Peveling gen. Reddemann*/
2 GIVN Hermann* Josef Julius
2 SURN Peveling gen. Reddemann***

After taking away the stars in the surname and name there was no more error.
**1 NAME Hermann* Josef Julius /Peveling gen. Reddemann/
2 GIVN Hermann* Josef Julius
2 SURN Peveling gen. Reddemann**

**Comment by hartenthaler** [comment]
This GEDCOM looks strange to me. Using an asterisk appended to one of the first names indicates the preferred name (Rufname). This is only necessary if not the first first name is the preferred one. What is the meaning of three or two asterisks appended to the last name? I would not use an abbreviation (gen.) in the last name.

I would expect
````
1 NAME Hermann Josef Julius /Peveling genannt Reddemann/
2 GIVN Hermann Josef Julius
2 SURN Peveling genannt Reddemann
````
or 
````
1 NAME Hermann Josef Julius* /Peveling genannt Reddemann/
2 GIVN Hermann Josef Julius*
2 _RUFNAME Julius
2 SURN Peveling genannt Reddemann
````

**Comment by schuco** [comment]
I can't explain the Arterisk in the surname and also would not use it there.
However I think it is useful to underline the first name if it is the preferred name as some people are called by double first names e.g. Heinz Werner.

**Comment by hartenthaler** [comment]
Ok, but even if the usage of the asterisks is strange it should not lead to an error in GVExport.

**Comment by schuco** [comment]
I looked into the problem once more:

1. I discovered more individuals with double asterisk in my tree. All of them resulted in the same error which could be removed by deleting one asterisk.
2. Most of these individuals with double asterisk were sibs of the family "Peveling genannt Reddemann" (Peveling called Reddemann). I now remember that I gave the asterisk after "Reddemann" intentionally as the generation of my grandfather only wanted to be named this way (on their graves it is written only "Reddemann").
3. And indeed in webtrees these individual's names are displayed with their preferred first name underscored and also the part "Reddemann" of the surname is underscored. So webtrees can handle multiple asterisks without error.
4. I found another case where an indi with 3 firstnames had two of these with asterisk. This led to an error in GVE but was correctly underlined in webtrees.

**Comment by hartenthaler** [comment]
I never saw this function. I assume that even Greg does not know that webtrees is supporting last names with two asterisks. I have to check if my own module "extended family" has a problem with that.

**Comment by Neriderc** [comment]
So when GVExport requests the name from webtrees, it doesn't actually return the asterisk. Instead it uses HTML tags to indicate that this name is a "starred name". I convert these to underline tags to underline it.

I'm not actually sure how webtrees would provide the name with two asterisks. I will have to test this before working out how to solve it. Unfortunately I'm a bit starved for time at the moment but I plan to tackle this soon as it _seems_ like a pretty simple thing to solve.

**Comment by Neriderc** [comment]
It seems that webtrees removes the first asterisk when identifying that it's a starred name, but it retains the second one and just includes the asterisk as part of the name. This is also how it is displayed in webtrees for me (i.e. if I go to the page of the individual with two asterisks at the end of one of their names, then this shows one asterisk.
![image](https://user-images.githubusercontent.com/89974636/184466434-03da5172-7b2d-4910-9a5e-dbd6e3e548c3.png)

I have updated to now support multiple preferred names, the above example looks like this (the names with asterisks have two asterisks in the name field):
![image](https://user-images.githubusercontent.com/89974636/184473107-2a05350e-c424-458f-a362-a45d35f48aeb.png)

I'll close this when the code is added but please let me know if anyone was expecting something different as we can always reopen and readdress it.
