### ISSUE TITLE
Relation status persons related to foster children is not shown correct

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#140]
This is working perfectly now for adopted children, but not for foster children. For example, the foster parents of a foster child are shown as blood-related.

@Neriderc: great work! Several issues disappeared!

**Comment by Neriderc** [comment]
How are foster children set up in webtrees? Is this like adopted children but with the relationship as "foster" instead of "adopted"?

When doing the changes for adopted children I used existing code that recognises the relationship from the GEDCOM, probably this is easy to fix but the original code must not have handled foster children. 

Are there other non-blood relationships we should handle while fixing this?

And a side question, in the context of a family tree, what is the difference between adoption and foster? Is "adoption" a legal adoption and "foster" being that child is part of the family but not legally adopted? 

Typically I'd think of "foster" as short term care, particularly looking after children in state care in return for money from the government. How would this link be used in the context of a family tree?

**Comment by hartenthaler** [comment]
> Is this like adopted children but with the relationship as "foster" instead of "adopted"?
Yes. If there is no relationship type specified for a child or if the type is "birth", it can be assumed that this is a blood relationship, in all other cases, it is a non-blood relationship. There is in webtrees another relationship supported: "RADA" for a person giving milk (breastfeed) to a child (in some cultures this has consequences for example rada siblings are not allowed to marry each other).

"Adoption" should be always a legal act without a declared end in time. Explicit in an adoption event or implicit for example if a couple marries and the already existing children are adopted during this event by some declaration of of the father for example. "Foster" is normally for some time, for example until the child gots 18 years old, after that time the foster relationship ends. In most cases, the actual used last name of an adopted child is the name of the adopting family. Foster child is normally still using their last name by birth (but there are cases for example security reasons to give the foster child the name of the fostering family). For example, in my extended family, there is a family with a foster child. They are living as a "normal" family, The foster child is using the family name of the foster family; the biological mother of the child does not give the allowance for adoption. But to secure the child, the biological mother was not allowed to live together with her child; she does not know where and under what name her child is living. Formally the government is responsible for this child, the foster family can be changed and the foster contract will end when the child gets 18 years old and has its own income.

**Comment by Neriderc** [comment]
Thanks!

I have an example somewhere between these two things. An orphaned child that joined the family of an aunt and uncle. In my country, adoptions are rare and are generally in the event of e.g. an adoption at birth. Adoption leads to an updated birth certificate with the new parents listed.

In most cases like the orphaned child above, the courts will grant _guardianship_. This grants the applicants the ability to make all decisions for the child and act as their parents, however, the birth certificate still shows the original parents.

In the above case the child joined the family and is treated like a child of theirs. Though in guardianship it is possible for others to petition the court to have the guardianship overturned, in this case it is unlikely. For all intents and purposes, this child is now a part of the new family and that's unlikely to change. However, this is not a legal adoption but is instead another legal process.

Would this be best represented as a foster relationship?

**Comment by hartenthaler** [comment]
> Would this be best represented as a foster relationship?

I would say: yes, this is an example for foster.

**Comment by Neriderc** [comment]
Thanks! I have an update to make to my tree!

For this issue, I have a code update that should fix this - and show any relationship that is not birth or blank as non-blood. I just need to assemble some test data for all the different pedigrees to ensure they all work properly. Once I've tested that I'll create the pull request and close this.
