### ISSUE TITLE
Create "advanced settings" sections

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#154]
We should move some settings into "advanced" and hide these by default, with a link to expand this section. Here's what I'm thinking:

- we should have a separate one of these for each of the sections. At the bottom of each section would be a button to show the advanced settings, and this would expand to show the settings.
 - we should remember the state. e.g. if you expanded it, we would save this in the cookie so next time you loaded the page it would already be expanded. Probably manage this separately for each section. This means we can be more aggressive about adding things to the advanced section, leaving the base panel clean and easy for beginners.
 - We can then start to add new settings (or restore settings that were available in the distant past) by adding them to these sections, e.g. options to change the default colours. These would be future pieces of work.

Some candidates for moving to "advanced":
First section:
- Stop processing on
- Mark not blood-related (keep default as on)

Second section:
 - Probably everything from "Show Individual ID" on

This would leave the form much cleaner and simpler - and as I said, we could save the state of the advanced section (shown/hidden) so users that want the advanced settings can easily see these pretty much the same as they do now, but new users would get a much simpler list.

I'm keen to hear thoughts on this.

**Comment by hartenthaler** [comment]
Excellent ideas. This would be helpful in making the menu shorter and narrower (if nothing is expanded). This will be an advancement for the GUI.

I have one question: what will happen when the link to expand the menu is clicked? Will the existing menu be enlarged or will a new (popup?) menu appear? I would prefer to expand the existing menu. This would allow making all menus invisible using one click at the existing "x" button.

**Comment by Neriderc** [comment]
Yes so what I'm thinking is that you shuffle the items around so the advanced things are at the bottom, then we hide them but have a link at the bottom of the section that says "Advanced" or "Advanced settings". When clicked, this would expand the form to make it look much like it does right now (but with a link to "Hide advanced settings"). No popup menu.
