### ISSUE TITLE
Option to not show birth/death details (i.e. name only)

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#157]
As per #151, we should have the option to show the name only.

We have a couple of options here and I'm keen for input on which is preferred:
1. In the event that "Show date of birth" and "Show place of birth" are both disabled, we could show just the name
2. We could add another option for "Show birth" and "Show death", with the place/date options only being available when these are selected.

The difference between these is that 1. would not show the birth/death markers on their own while 2. would allow that. Currently you can uncheck the date/place options and still see that a person is or isn't alive by looking for the appropriate symbol ("+" by default). That wouldn't be possible with 1. but with 2. we are adding more options that are potentially unnecessary.

I'm keen to hear some thoughts on these options.

**Comment by hartenthaler** [comment]
For me option 1 would be the preferred one, because that is closer to the idea "hide everything beside the name". Hiding the date and place but showing indirectly if the person is alive or dead is less important.

**Comment by hartenthaler** [comment]
As a workaround, it is now possible to change the colour of the details to white.
