### ISSUE TITLE
Update browser render automatically

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#159]
Instead of having to click the "Update" button, we could update after any change is made to the settings.

In the event that this is too taxing on an older browser/computer that a user has, we should add an option to disable this in the Output section.

At this point probably we should not add an advanced section to this part given it would only have one checkbox in it. At a later time where there are more advanced options this could be moved to the advanced section.

**Comment by Neriderc** [comment]
@hartenthaler I've just created pull request #193

I have added an option under Output Settings to auto-update the browser render. I have hidden the update button when it's enabled.

Can you let me know what you think? Do you think this should be enabled or disabled by default?

It feels very jarring to me to not have to click the update button because I'm so used to it, but for a new user it's probably not as jarring.

**Comment by hartenthaler** [comment]
... "jarring" was a new word for me - I will check how it feels to me.

**Comment by hartenthaler** [comment]
That feels very good to me! Much more intuitive than before. I have done some stress tests with larger trees and it is ok for me. You can see the rotating wheel and so it is clear that the system is still working, you can click on another option in the meantime, and it works as it should. Ok, you will get then several toast messages in a short time but this works perfectly, too.

In my opinion, the new option should be enabled by default! For new users of this module, it will be more intuitive and old users will like the shorter time to see results.

**Comment by hartenthaler** [comment]
I have seen one time something strange. In the diagram area, there was a complete webtrees page (including the webtrees menus and so on). It showed a message: "you are not logged in". But it disappeared after one second and was replaced by a correct GVExport diagram.

**Comment by Neriderc** [comment]
> That feels very good to me!

Great! I will merge this in. I think this will be the last thing for this version. I will do some regression testing when I get the chance, and then release a new version.




> I have seen one time something strange. In the diagram area, there was a complete webtrees page (including the webtrees menus and so on). It showed a message: "you are not logged in". But it disappeared after one second and was replaced by a correct GVExport diagram.

This is likely something to do with webtrees. The browser render is created via sending a request to the server to download the file as DOT, then retrieving the response and putting this into Viz.js. If an error is thrown by Viz.js, the DOT contents are displayed after the error message. It's possible that in the case webtrees receives the request to the module and returns a page saying you are not logged in, then this page could be inserted into the browser render box.

With  #186 we detect if we received an HTML page instead of a DOT file, and if so we refresh the page after showing a toast message, so this is likely what fixed it.

I'm not sure if there's much more we can do than this as ultimately the page saying you're logged out is from webtrees, so there isn't a lot we can do besides refreshing the page.
