### ISSUE TITLE
Create full documentation

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#16]
Currently there is very little documentation about using GVExport. We should document each feature so users know how to use them.

Given the small scale of the module, a GitHub wiki page should be sufficient.

Possible acceptance criteria:

Given the GVExport module needs user documentation
When a user wants to know more about a feature provided in the module
Then they can access relevant documentation in the GitHub repo wiki, including:
- Installation of the module
- Installation of GraphViz
- Basic overview of the tool, it's purpose, and step by step instructions for a simple scenario
- Detailed documentation of each button, checkbox, dropdown, or other option

Out of scope:
- Developer documentation

**Comment by hartenthaler** [comment]
That would be helpful. I used this module but didn't spend enough time playing with all the options.

**Comment by hartenthaler** [comment]
Thank you! Good idea. I just started a similar activity in the framework of the German webtrees manual. There is now a very first draft of a wiki page in German language: https://wiki.genealogy.net/Webtrees_Handbuch/Anleitung_für_Webmaster/Erweiterungsmodule/GVExport

I will try to synchronize your English page and this German page.

**Comment by Neriderc** [comment]
Great, thanks! Let me know if there's anything I can do to help make it easier. I've only just started to set up the structure, so if a different structure would make it easier to keep things in sync then let me know.

**Comment by hartenthaler** [comment]
There is a general structure for all custom modules in the German webtrees manual, so I used that (similar to the structure in the GitHub READme). But I have added some structure elements you have suggested here. The most important task is now to describe the elements in the user interface. This can be synced with your GitHub wiki. All the other more formal parts are now available in the actual version at GenWiki.

**Comment by hartenthaler** [comment]
I have added the change log to the content because it contains valuable information during the phase documenting this module. The change log will be removed in the final release because it is more developer documentation and not user-oriented.

**Comment by Neriderc** [comment]
I've finished my initial plan for the wiki. It will of course need updates as we change things, but at this point it may be complete. Any further suggestions? https://github.com/Neriderc/GVExport/wiki

**Comment by Neriderc** [comment]
Great! I will close this as this is complete. Future documentation changes can be done as we change things.
