### ISSUE TITLE
Add list of fonts to choose from

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#160]
We should provide a list of fonts for the user to select from.

As fonts are loaded from the browser or server, we should include "[web safe](https://www.w3schools.com/cssref/css_websafe_fonts.asp)" fonts only.

- Arial
- Verdana
- Tahoma
- Trebuchet MS
- Times New Roman
- Georgia
- Garamond
- Courier New
- Brush Script MT

As part of this, we should test the fallback onto other fonts in the case a font is not available. E.g. use a font value of "[user selected], Arial, Sans" where "Arial" is known to work well currently.

- Also add ability for user to change font colours.

**Comment by arbor95** [comment]
I would like the color of the font back to black. Is there a reason it's greyish now?

**Comment by Neriderc** [comment]
Having text grey-ish rather than #000000 black is becoming more common, for a few reasons. You can do a google search to find endless arguments, but in general the idea is that counterintuitively some people find it hard to read text that contrasts too much with the background. The shades I've picked are on the greyer end of the scale, and I'm willing to play with these a bit more as they are reasonably light. However, I don't think we will have pure black as the default.

Currently, there is no functionality for a user to edit colours. Some colours can be changed in the config.php file but the text colour is not one of them (yet).

I'll bump this up the to-do list and add customising font colour to the list of things to do for this issue. I'll look at making the fonts a slightly darker grey by default, but if you want pure black I will aim to have this customisable in the next version.

**Comment by Neriderc** [comment]
This is now available on the 'main" branch and will be in the next release.

You can change the font to one of the ones listed above, and can set the colour for the name and the colour for the "details" (everything else).

I have also made the text slightly darker (but still grey) by default.
