### ISSUE TITLE
Investigate MCLIMIT setting

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#163]
What does this setting do? It says it reduces crossings on the graph - which I presume to mean arrows crossing over each other. Do we have proof it works?

~~Does this work from browser mode? I suspect it only works server side, as it does not seem to impact the time it takes to generate the browser render. Can it be used client side?~~ 

~~If it can't be used client-side, then we should hide or disable the option when GraphViz not installed.~~
 
confirmed it makes a difference client side, you do get slightly different output if you select different settings  - but still not convinced it *actually* helps to reduce arrow crossings. It seems you just get the arrow crossings in different places.

**Comment by hartenthaler** [comment]
for me it is the same impression: it has an effect but it does not help to reduce arrow crossings

**Comment by Neriderc** [comment]
Thanks for confirming you see the same thing I do.

I propose we:
- Remove this setting from the UI
- Retain it in the config.php - in case people are using it they can set it here
- Change the default to 1 instead of the current 50, since running it 50 times doesn't seem to help
