### ISSUE TITLE
Bug when using php 8.1

### ISSUE THREAD

**Issue by ddrury** [Neriderc/GVExport#167]
strtolower doesn't accept null as a parameter and throws an error in line 165 of config.php. The problem is that there is an entry in country-codes_json.json where "CLDR display name" (and a lot of other fields) is set to null.

**Comment by Neriderc** [comment]
Thanks for reporting this!

I'm running PHP 8.1 and don't see the error, however, we did find the CLDR names are in some cases very unhelpful for the purpose of abbreviation (e.g. the CLDR name for the US is "US". This file was downloaded and dropped in as is but I think we will develop our own based on it, and remove the unnecessary information. 

I'll work on this for the next release, in the meantime it sounds like you have already worked out that you can remove the problem country from the file to solve the issue.

I'm still curious why it's fine for me and not working for you. Is there something special about the PHP version you're using? e.g. are you using the FPM version?

**Comment by Neriderc** [comment]
This is now resolved on the "main" branch. It will be in the next release.

**Comment by ddrury** [comment]
> I'm still curious why it's fine for me and not working for you. Is there something special about the PHP version you're using? e.g. are you using the FPM version?

Hm, no idea, I'm using php 8.1.7 and was using FPM but just changed to apache module with same result. PHP error reporting is set to E_ALL

**Comment by Neriderc** [comment]
I'm on 8.1.8 but I doubt that's the reason, and a quick scan of the 8.1.8 change log doesn't show anything related. I also have error reporting set to E_ALL.

We may never know what the difference is but either way this should be resolved in the next release (or you can download the main branch now).
