### ISSUE TITLE
New design for decorated/combined mode

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#174]
I've played a bit with the design and have come up with something new I'd like to share.

I think it looks much better, but maybe others will disagree. The easy option would be to replace the existing decorated/combined modes with the new style but I just want to see if there is any opposition to this - i.e. does anyone prefer the old version over the new?

Here's the new version in decorated mode:
![gvexport(6)](https://user-images.githubusercontent.com/89974636/188265088-60245693-5ff9-467e-8e8d-d0febc0551d8.png)

And here is the old version of the same thing for comparison:
![gvexport(9)](https://user-images.githubusercontent.com/89974636/188265104-8dd8d5bd-ae13-4928-9895-b88916a30580.png)

Here is combined mode:
![gvexport(7)](https://user-images.githubusercontent.com/89974636/188265110-4c205bb6-d0e2-4708-83b1-bc7b914a5cad.png)

Here's the same thing in the current version:
![gvexport(8)](https://user-images.githubusercontent.com/89974636/188265117-ea6112e2-6f96-4625-a62e-c485e968fd23.png)

I'm really keen for feedback so let me know what you think!

**Comment by schuco** [comment]
If it does not need more space due to the colored top line and therefore enlarges big trees, I would  prefere the new design

**Comment by hartenthaler** [comment]
The new version looks better!

**Comment by Neriderc** [comment]
> If it does not need more space due to the colored top line and therefore enlarges big trees, I would prefere the new design

This is a good point. I left scales as before but extending the line at the top above the photo does make them slightly taller even though the space around the photo is used a little more efficiently. I have made an adjustment so the tiles have just enough room for the information, scaling down the photo slightly. This means it now takes up less room than previously. Of course if you want things bigger, you can increase the DPI.

![gvexport(1)](https://user-images.githubusercontent.com/89974636/188288532-83f2e07a-e9d1-404a-9792-20e49163c329.png)

I'll put these updates in the next realease :slightly_smiling_face:  (still time to make adjustments if anyone has further comments - there's a potential bug I want to investigate before releasing the next version).

**Comment by Neriderc** [comment]
I've merged this in. I've now done all the work to release a new version, so will publish a new version when I get a chance.
