### ISSUE TITLE
Allow to add a family XREF as stop point

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#178]
When adding a family XREF to the cutoff list this should be handled as a shortcut for adding all individuals in that family as cutoff points.

**Comment by Neriderc** [comment]
This would be a good feature but would require a few changes to how things are done. I'll put this on the to do list as a future enhancement.

**Comment by hartenthaler** [comment]
I suggest closing this issue. It was ok as long as the stop list consists of XREFs only. But now the stop list is a list of individuals and it would be strange (and maybe impossible to implement) a mixed list of INDI and FAM. The advantage to add a Stop-Family is less compared to the disadvantage of a more complicated user interface.

**Comment by Neriderc** [comment]
Ok I'll close it for now. If you get any ideas in the future on a good system that makes sense in the UI then we can look at it again.
