### ISSUE TITLE
GUI of new advanced option to skip scanning tree for unseen links to improve speed of diagram generation

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#179]
At least in German the describing text is lengthy and the position of the check box should be top aligned instead of centered (in this case? generally?)
![Screenshot (239)](https://user-images.githubusercontent.com/6324175/188315265-da1b6f6c-a447-422a-8fc5-9c3730cc3753.png)

**Comment by Neriderc** [comment]
Makes sense, I've made this change
