### ISSUE TITLE
trees are incomplete

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#180]
There is something fundamentally wrong with version 2.1.10. Ig there are two starting persons only the ancestors of one person are found. If there are two starting persons, which are married together, they are shown in the simple mode but they are not part of the combined diagram. Those errors are new with the latest version, I never have seen them before.

**Comment by Neriderc** [comment]
I have tested with two unrelated starting persons and ancestors are shown for both of them. What other settings are you using?

I suspect the issue with the combined diagram may be related to the fix in the previous version when trying to solve an issue with combined mode getting ghost records when a stop person is added. As has been discussed in #101, current spouses are not currently shown for the youngest generation. I would guess this causes them to be stripped out of the tree when attempting to resolve the other issue, so this will need to be fixed.

**Comment by Neriderc** [comment]
I have fixed issue 2 in #182, it would be good to hear more about the first issue as I can't reproduce this.

**Comment by hartenthaler** [comment]
Both issues are solved with your latest fix. Great!
