### ISSUE TITLE
Remove "marriage box" in combined mode if marriage information is disabled

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#185]
In my opinion the yellow "marriage box" in combined mode is not necessary or should be much smaller if the marriage date and place is deactivated.
![Screenshot (242)](https://user-images.githubusercontent.com/6324175/188612877-db6de214-ada6-4378-94e5-ad78733ba086.png)

**Comment by Neriderc** [comment]
There is actually a hidden option in the backend to disable the showing of family records, however, I believe this doesn't work in combined mode.

In either case, unless there is some underlying reason the nodes are needed I agree these should be hidden in this case.

**Comment by Neriderc** [comment]
How's this?

When no partner, no kids, not married, and family ID turned off (i.e. nothing to show in box), then no box (Matthew Bloggs here):
![image](https://user-images.githubusercontent.com/89974636/190267192-30e718bc-3778-4251-9786-33f6f2ac57bc.png)

If partner is shown, then show a smaller box:
![image](https://user-images.githubusercontent.com/89974636/190269555-47a2aed3-60a0-4ce6-af29-30edf4407665.png)

Except - if family ID, marriage date, and marriage place are all turned off, don't show family records at all:
![image](https://user-images.githubusercontent.com/89974636/190269096-d4672baa-0fff-42be-a2c5-11fe2ca78702.png)

Is this what is preferred or maybe for the second one still show no box since there are no marriage details?

@hartenthaler @michamarti it would be good to get your thoughts on this

**Comment by michamarti** [comment]
would be fine with me, 
so you can see the existence of a mariage without data, as opposed to not beeing married? with child relations?
if it's always displayed with empty family data, I'd prefer to show now box, to save space in my huge DINA0++ wallpapers :-)

**Comment by Neriderc** [comment]
> would be fine with me, so you can see the existence of a mariage without data, as opposed to not beeing married? with child relations?

It effectively shows the existence of a family record (not a marriage record), so even if they aren't married it would still show. Whether or not there is a marriage record is not information currently used, here I just check if there is anything in the box and if not then make it smaller. The difference between the first and second images above is that the partner is shown in the diagram - and therefore we have the family record too. I'm happy to not show this ever unless there are details to print, so long as @hartenthaler is ok with this.

> if it's always displayed with empty family data, I'd prefer to show now box, to save space in my huge DINA0++ wallpapers :-)

Given that every record in a generation is in line with the others, if _any_ record shows a box then I would expect that this would push out the size of that whole generation, so I'm not sure how much it would help if only those without a marriage record had no box - it would only take one in the generation to move them all out.

As part of this change we'd be making it possible to not show the marriage records at all, which would help.

**Comment by michamarti** [comment]
> Given that every record in a generation is in line with the others, if _any_ record shows a box then I would expect that this would push out the size of that whole generation, so I'm not sure how much it would help if only those without a marriage record had no box - it would only take one in the generation to move them all out.

imho that's true for top down, but not left to right ?

**Comment by hartenthaler** [comment]
> As part of this change we'd be making it possible to not show the marriage records at all, which would help.

Yes, if there is no marriage date, no place, and no FAM-XREF, then the box should not be there. That the two partners are linked together is in the combined mode clear, because their boxes are side by side.

> Is this what is preferred or maybe for the second one still show no box since there are no marriage details?
I would prefer that for the second screenshot there is no yellow (small) box be shown because the box is not necessary. But: ok then you will see in the diagram some families with yellow boxes and some without. For me, the side-by-side combination of two boxes is the relevant and important signal that those two persons are a couple. The yellow box shows more details if those details are available, but if there are no details, then the yellow box is not necessary.

**Comment by hartenthaler** [comment]
> It effectively shows the existence of a family record (not a marriage record), so even if they aren't married it would still show.

Yes, if there is a FAM record then there is a combined box. It is not relevant if they are married or not. Maybe this could be indicated in some way. It could be that a married couple has a dark yellow, and a not married couple has a light yellow box. A not-married couple can get a bright lightning symbol, a divorced couple gets a red flag. ;-) Additionally, if there is a source for the marriage then there could be a green hook symbol. And there are maybe more ideas, but this is for later.

**Comment by Neriderc** [comment]
> imho that's true for top down, but not left to right ?

Yes I believe so.

> Yes, if there is no marriage date, no place, and no FAM-XREF, then the box should not be there. That the two partners are linked together is in the combined mode clear, because their boxes are side by side.
> I would prefer that for the second screenshot there is no yellow (small) box be shown because the box is not necessary. But: ok then you will see in the diagram some families with yellow boxes and some without. For me, the side-by-side combination of two boxes is the relevant and important signal that those two persons are a couple. The yellow box shows more details if those details are available, but if there are no details, then the yellow box is not necessary.

It sounds like we have consensus so I have made the change. We don't have small empty boxes anymore, if there are no details to show then we don't show them. This of course may change with @hartenthaler 's other suggestions. Here's how it's looking now:
![image](https://user-images.githubusercontent.com/89974636/190504878-ce1103af-2cbf-4546-8938-965e52303a79.png)


> Yes, if there is a FAM record then there is a combined box. It is not relevant if they are married or not. Maybe this could be indicated in some way. It could be that a married couple has a dark yellow, and a not married couple has a light yellow box. A not-married couple can get a bright lightning symbol, a divorced couple gets a red flag. ;-) Additionally, if there is a source for the marriage then there could be a green hook symbol. And there are maybe more ideas, but this is for later.

Have a think about exactly what you'd like, and create a new issue for it :)

I'll merge in what I have for this and it will be in the next release.

@michamarti if you want to get started using it right away, from the [main page](https://github.com/Neriderc/GVExport) of this repository you can click the bright green "Code" button, then choose to "Download as ZIP", then unzip and install as usual.
