### ISSUE TITLE
Chain of partners is not shown in combined mode

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#187]
Maybe you can have a look at https://ahnen.hartenthaler.eu/module/_GVExport_/Chart/ahnen?xref=I43770#.
![Screenshot (243)](https://user-images.githubusercontent.com/6324175/188761021-67ffa393-cc4f-4529-bf7f-4db8586b0565.png)

If you select "anyone" and do not select ancestors and descendants, only the chains of partners should be shown. This is working in the simple and decorated mode.

If you select the combined mode there is a correct toast that 33 persons in 33 families are generated. But the diagram is empty. I would expect to see the 33 families. If you select "Include descendants" and set max. level to 0 the families are shown. I would expect that there is no difference between
- "include descendants" not selected and
- "include descendants" selected with max. level = 0.

**Comment by Neriderc** [comment]
I am able to see the issue on your tree. I think I know the likely cause so will look at fixing this.

> I would expect that there is no difference between
> 
>     * "include descendants" not selected and
> 
>     * "include descendants" selected with max. level = 0.

This is related to #101. Could you have a look at my last comment there and confirm what I have written is in line with your expectations? Then I can start looking at making the changes (probably in a later release but we will see).

**Comment by hartenthaler** [comment]
Yes, this is related to #101. I have forgotten about this. See now my comment there.

**Comment by Neriderc** [comment]
> I think I know the likely cause so will look at fixing this.

It was not this. I thought it was a recent change, but it appears to be from some old code that prevents a record being shown if it has no parents or children. I'm not sure of the logic behind this, but first I want to check what you would expect this to be displayed like in the combined mode. For example, with test records that look like this in decorated:
![image](https://user-images.githubusercontent.com/89974636/189005789-0f50fed2-a36c-495a-bc0e-38eb4e9a2179.png)

Is this what is expected for combined mode?

![image](https://user-images.githubusercontent.com/89974636/189005866-9d127464-3cb8-4e80-b235-3db7570c98f0.png)

**Comment by Neriderc** [comment]
And for a wider diagram, would you expect those records to just hang out not linked to anything? I'm guessing this is what that code is meant to prevent, but it's easy enough to disable it if we want.

![image](https://user-images.githubusercontent.com/89974636/189006134-f0700785-abfe-49f0-80b5-d22a4bcb570e.png)

**Comment by hartenthaler** [comment]
>  just hang out not linked to anything

Yes, I don't see another possibility. The German genealogical program Stammbaumdrucker has an option to show in this case a coloured line that interconnects the duplicated instances of a person. This could be an idea for GVExport, too. Maybe use a coloured dotted line. It helps to visualize this situation but disturbs the diagram a bit.

![Screenshot (244)](https://user-images.githubusercontent.com/6324175/189055752-f00ae9d8-9cd8-4f53-b4e2-6baaedab2612.png)

**Comment by hartenthaler** [comment]
Thank you for playing! Good analysis and good conclusion!
