### ISSUE TITLE
Enhance README.md

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#194]
Add two links to the section "Help and support":
- English wiki: https://github.com/Neriderc/GVExport/wiki
- German (webtrees manual): https://wiki.genealogy.net/Webtrees_Handbuch/Anleitung_für_Webmaster/Erweiterungsmodule/GVExport

**Comment by Neriderc** [comment]
Done :)

**Comment by hartenthaler** [comment]
That was fast!!!
