### ISSUE TITLE
Changes to which records are shown based on descendant setting

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#201]
Based on the discussion in #101 we should make the following changes:

- Currently if "Include descendants" is checked and the number of generations is set to 0, only the starting individual is shown. We should make this show partners (if "Spouse" selected) and partners of partners (if "Anyone" selected) in both cases (i.e. current functionality when unchecked should also be applied to setting generations to 0)
- The youngest generation should have spouses included if this option is enabled
- If a family record would have no spouse or children showing (only one linked individual), then it should not be shown in simple/decorated mode.

I believe these are the only changes required to bring us in line with the discussion, please let me know if this is not correct.

@hartenthaler and @schuco you may want to double check what I have here is in line with your expectations.

And if there are differing opinions on this please make yourself heard, we can always add options if needed.

**Comment by hartenthaler** [comment]
I agree 100%.

**Comment by schuco** [comment]
Perfect. See what is selected.
