### ISSUE TITLE
Starting person is not shown in combined mode

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#204]
There is a starting person and the ancestors with max generation 1 selected so that there is the starting person and the parents are shown. ok in simple mode.
![Screenshot (255)](https://user-images.githubusercontent.com/6324175/190217074-ed55620f-3b0e-4fc0-8890-30e24012a982.png)

In combined mode, only the parents are shown but not the starting person. I would expect to see all three people, too.
![Screenshot (256)](https://user-images.githubusercontent.com/6324175/190217094-e341b3ab-d0e4-496a-8e9e-b166d7d76943.png)

**Comment by Neriderc** [comment]
I have managed to reproduce this on 2.1.11, only when starting with someone married. But I have not been able to reproduce this on the up to date main branch. Could you check if this is fixed on main? It may have been resolved with the other changes made recently to resolve issues in combined mode.

**Comment by hartenthaler** [comment]
Yes, using the latest main branch it works as expected. Sorry.
