### ISSUE TITLE
How to show individuals in combined mode if they are married twice?

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#205]
What should be done in the following situation? Let's have a look in simple mode, first.
![Screenshot (258)](https://user-images.githubusercontent.com/6324175/190496607-8805ef48-a3ef-4021-a188-7664b732ead5.png)

In the simple mode this is as expected. The starting person and the parents are shown.

Now in complex mode it is a bit different:
![Screenshot (257)](https://user-images.githubusercontent.com/6324175/190496828-2e29bdf2-fec5-4667-8760-0d485c6a889e.png)

You can see that "Sibling Seudo" is married twice. The father "F Seudo" was married two times, too. Ok. This looks as it was expected.
But if you deselect now "Show family ID" it is very difficult to understand why two persons are there two times.

If you add now the option "spouses" the diagram is very clear in simple and combined mode.
![Screenshot (259)](https://user-images.githubusercontent.com/6324175/190500456-426f85f3-e3c5-4da0-acc4-8d781084eee2.png)
![Screenshot (262)](https://user-images.githubusercontent.com/6324175/190501405-f708f20d-1e91-47e8-8026-3a35b935bb05.png)

So in my opinion the problem behind is that in combined mode if "spouses" is not selected, dummy families are generated and those families do not have a partner if the option "spouses" is deactivated. From my point of view the solution would be: If the combined mode is selected, the "spouses" option is activated automatically and mandatory. Then it should be not necessary any longer to generate dummy families. Or do you see another way to visualize this situation in combined mode when "spouses" is deactivated?

btw: maybe you could replace the word "spouses" by "partners" because for me "spouses" indicates that the two partners are married together.

**Comment by Neriderc** [comment]
> So in my opinion the problem behind is that in combined mode if "spouses" is not selected, dummy families are generated and those families do not have a partner if the option "spouses" is deactivated. From my point of view the solution would be: If the combined mode is selected, the "spouses" option is activated automatically and mandatory. Then it should be not necessary any longer to generate dummy families. Or do you see another way to visualize this situation in combined mode when "spouses" is deactivated?

This is definitely one way to solve the problem. However, if you were wanting for example to show the ancestors of a person, you may want their parents and grandparents to be shown, but not their mother's ex-husband that is not related to the starting person. 

> btw: maybe you could replace the word "spouses" by "partners" because for me "spouses" indicates that the two partners are married together.

Is there a term that webtrees uses for this? If not, I'm happy to change this to partners as "spouses" also indicates to me that they are married.

**Comment by hartenthaler** [comment]
> However, if you were wanting for example to show the ancestors of a person, you may want their parents and grandparents to be shown, but not their mother's ex-husband that is not related to the starting person.

See my second screenshot above. The starting person is "Sibling Seudo".  I want his parents to be shown. GVExport shows the parents but it shows the father two times even if the option "spouses" is not selected. So another solution would be: do not show the father two times (as it is in the simple mode). And consequently do not show the starting person two times if "spouses" is not selected. This is definitely another way to solve the problem. But I'm not sure about the side effects of this solution. But why not try it?

**Comment by hartenthaler** [comment]
> Is there a term that webtrees uses for this? (spouses/partners)

webtrees uses for example in the sidebar "family navigator" the correct words if it is clear that they are married and the partner is male: "husband". Or it uses "partner" if it is clear that they are not married. If it is not clear you can see this situation in the tab "family" when you like to add a partner to a female person: webtrees uses "add a husband" even if it is not clear if they are married or not. But for me, it would be better to use "add a partner" in this case. webtrees does not know in this situation whether you like to add a married partner or a non-married partner; and even worse: maybe you like to add another woman to this female person.

**Comment by Neriderc** [comment]
> See my second screenshot above. The starting person is "Sibling Seudo". I want his parents to be shown. GVExport shows the parents but it shows the father two times even if the option "spouses" is not selected. So another solution would be: do not show the father two times (as it is in the simple mode). And consequently do not show the starting person two times if "spouses" is not selected. This is definitely another way to solve the problem. But I'm not sure about the side effects of this solution. But why not try it?

In your second screenshot, we have F Suedo listed a second time out on their own. With the code we undid in #187 this removed what I would guess was originally a fix for this situation. Perhaps this check should be triggered only for certain situations (it specifically checks for records with no parents or children, and doesn't display them).

The issue with Sibling Suedo is not new, it exists in the GVE 2.1.0 version that is the oldest in this repository. I'm not quite sure what the easiest way is to resolve this. I'd have to have a think about it.



> > Is there a term that webtrees uses for this? (spouses/partners)
> 
> webtrees uses for example in the sidebar "family navigator" the correct words if it is clear that they are married and the partner is male: "husband". Or it uses "partner" if it is clear that they are not married. If it is not clear you can see this situation in the tab "family" when you like to add a partner to a female person: webtrees uses "add a husband" even if it is not clear if they are married or not. But for me, it would be better to use "add a partner" in this case. webtrees does not know in this situation whether you like to add a married partner or a non-married partner; and even worse: maybe you like to add another woman to this female person.
> 
> see https://www.webtrees.net/index.php/en/forum/8-translation/37317-spouse-versus-partner

This makes sense. We could change this to "Partner" which is more accurate but still succinct.

**Comment by Neriderc** [comment]
In #187, all the problem records had both partners. Is there ever a case where a record with no parents, no children, _and_ only one spouse would be wanted? I can't imaging how someone could end up in a record like this unless they were also elsewhere in a connected part of the tree. Perhaps we should re-introduce that older code but only trigger it if either the husband or wife records are missing.

> The issue with Sibling Suedo ... I'd have to have a think about it.

I have had a bit more of a think about this. I think I know how we can remove the duplicate, but I just want to confirm I'd have this right.

In the case where the individual has no partner, no children, and is already in the tree, we should skip them. What about the marriage record:
- Should we leave the duplicate in the case that the marriage details are showing (since it will be clearer that this is a different marriage)? 
- Or is it better to only show when a spouse is present (since we may not be interested in this marriage when e.g. only listing ancestors, but it would show because this person is already in the tree)?

Personally I feel like if you are interested in second marriages then you would choose the spouse option, so if the spouse is not showing then probably we should not show the record even if the marriage details are showing. But I'm keen to hear thoughts on this.

**Comment by Neriderc** [comment]
Just a note that I have made the first change in pull request #210 but still looking for input on the second thing.

**Comment by Neriderc** [comment]
Currently we do not show the floating duplicate so the original issue is resolved, and there have been no further complaints about the display of this, so I will close this (old) issue.
