### ISSUE TITLE
Changing the language resets the starting individual

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#207]
Sometimes I have to produce a screenshot in the "English" language setting instead of the "German" setting while using GVExport. But when I use this function in the webtrees main menu and select "English" then all the carefully prepared settings in GVExport are destroyed.

**Comment by Neriderc** [comment]
Interesting! This does not happen for me.

I can switch back and forth between languages and the settings are saved. I even tried in your test instance and it works fine. I've tried Firefox and Chrome. 

Is it resetting all of the settings or just some?

**Comment by hartenthaler** [comment]
ok, then I have to test it a bit more carefully

**Comment by hartenthaler** [comment]
Ok, tested in my [productive](https://ahnen.hartenthaler.eu/) and my [test](http://ahnentest.hartenthaler.eu/) environment:
it is only the starting person that is set back, no other options.

1. open GVExport from a personal page
2. change the starting person to another person
3. change the language setting
4. the starting person is set back to the person from step 1

I would expect that the person selected in step 2 is preserved as starting person when changing the language setting.

**Comment by Neriderc** [comment]
Ah yes, I also see this. This is not loaded from saved information, but is set from the URL. If you start from a tree home page, webtrees feeds us the default individual's xref. If you start from a person's page, then that XREF is fed to us. If you reload the page (either by changing the language or simply by pressing refresh in your browser), then the URL XREF is then used to populate this box - and if you change who is in this box then it doesn't change.

I guess the question is, what are our expectations for this field?

My expectation is that if I go to an individual's page then from here navigate to GVExport, I want the individual whose page I was just on to be shown, not whomever I might have been looking at last time. However, if I refresh the page, I would like to keep the same individual.

Here's one idea: When the individual is changed in the selection box, update the URL XREF to the new individual's XREF.

It would be relatively straightforward to do, and i think it meets my expectations for what should happen in that box.

**Comment by hartenthaler** [comment]
Perfect analysis and conclusion! Thank you!
