### ISSUE TITLE
2.1.12 - Untranslated strings (ABT, AFT, BEF, BET/AND, EST)

### ISSUE THREAD

**Issue by TheDutchJewel** [Neriderc/GVExport#223]
I see some untranslated strings in the output:
- ABT
- AFT
- BEF
- BET [...] AND
- EST

Is it possible to translate them, or use symbols?

For example:
- ABT =`~`
- AFT = `>`
- BEF = `<`
- BET [...] AND = `>` [...] `<`
- EST = `±`

**Comment by Neriderc** [comment]
Either of these would be possible. It looks like webtrees converts e.g. 'EST' to 'estimated', then translates this to the selected language. We could do the same.

The symbols are a good idea. Much more concise than having full words, and so I think better for this sort of diagram.

Let's leave this open for a little bit to let others have their say. If there aren't any objections, I propose to implement this using your suggested symbols, and include this in the next release.

**Comment by schuco** [comment]
Generally there are not many (no?) words to be seen in GVE diagrams. Birth and death are indicated by symbols. Therefore the proposed solution fits well, is valid for all languages and is intuitively  understandable.

**Comment by hartenthaler** [comment]
I would prefer symbols more than words, too.

**Comment by Neriderc** [comment]
Symbols it is. I know there are more of these terms used than just the ones listed in this post. Are we happy to leave it as just these 5 or are there others we want to include?

**Comment by TheDutchJewel** [comment]
> I know there are more of these terms used than just the ones listed in this post. Are we happy to leave it as just these 5 or are there others we want to include?

Use symbols if possible, otherwise translated text.

**Comment by Neriderc** [comment]
I've created a pull request with these changes. I just want to confirm this is what you're expecting? Any last minute changes before I merge this?

![Image](https://user-images.githubusercontent.com/89974636/193977700-8387b21d-285d-4c6e-b580-0db3415aee52.png)

**Comment by TheDutchJewel** [comment]
Looks good, but I would also like to see a space _behind_ the symbols.

**Comment by Neriderc** [comment]
Like this?

![image](https://user-images.githubusercontent.com/89974636/193985601-c160068b-b6c6-459a-8045-850e15ff15ef.png)

**Comment by TheDutchJewel** [comment]
Yes, very nice!

**Comment by Neriderc** [comment]
Great, I will merge this in and  it will be in the next release.

As part of this change, the other values supported by webtrees but not in this list will now be translated as full words. This is using the existing translations in webtrees so should not need new translations.
