### ISSUE TITLE
What's important to you (the user)?

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#232]
It would be good to hear what features are important to anyone using GVExport, to help prioritise the order that things are added.

Feel free to mention existing issues that you'd like prioritised, or to suggest things that have not yet been mentioned.

Small things or big things are welcome. You can comment on little things that annoy you, options you wish you had, or big features on your wish list.

**Comment by hartenthaler** [comment]
> ... full-screen mode in https://github.com/Neriderc/GVExport/issues/234 for mobile devices. This would be my primary wish to be done for Windows devices too.

Then GVExport will look even a bit more like the custom modules LIN and TAM. Sounds as a good option.

The arrow colours can be modified already, but I would prefer to have the same possibility as user for some other elements, too.

For me saving the selected persons and families in the clippings cart (#177 ) has a high priority. But not enough time. I will try to get it done, nevertheless.

**Comment by Neriderc** [comment]
Thanks guys, I will aim for #234 and #195 for the next release. I'll be sure to support full screen mode on desktop browsers as well.

I'll look at the control panel settings after this. This is something I'm unfamiliar with, so I will need some time to research how to do this.

I have deliberately left #92 untouched. We have many changes happening and I worry that the saved data will quickly become useless if we change things too much. Hearing it's low priority, I will continue to hold off on this and will revisit at a later point.


@schuco 
> #195 It would be nice to configure colors. So I prefer the arrow for non blood-related descendants to be better distinguished (e.g. red).

As @hartenthaler mentioned, this is available right now. It's in the appearance section, at the bottom of the advanced settings.

If you click to enable different arrows based on blood relationship, two new options appear. Click the colour and you will be presented with a colour picker to change the colour. This is using your browser's built in colour picker, so it will look different in different browsers, but you should be able to change the colour using this.

![image](https://user-images.githubusercontent.com/89974636/194425646-6dec4bd9-a322-4fc9-912c-757579bd3be8.png)

**Comment by hartenthaler** [comment]
> I'll look at the control panel settings after this. This is something I'm unfamiliar with, so I will need some time to research how to do this.

Not very complex. You can have a look at my module "Extended Family". You need a view file to be presented in the control panel with all the options, like https://github.com/hartenthaler/hh_extended_family/blob/main/resources/views/settings.phtml

And two functions:
- public function getAdminAction(ServerRequestInterface $request): ResponseInterface
- public function postAdminAction(ServerRequestInterface $request): ResponseInterface
- As an example you can use https://github.com/hartenthaler/hh_extended_family/blob/main/ExtendedFamilyTabModule.php starting at line 218.

**Comment by Neriderc** [comment]
@hartenthaler Thanks! I will take a look after I'm done with the first two items.

**Comment by schuco** [comment]
Getting proposed changes done so fast I dare to propose another one:

If you stepwise build up a tree it is sometimes complicated to find the starting person in a big diagram as GraphViz reorders the tree-picture in every step.
Could there be an option to highlight the starting person(s)?
This would also be helpful if you want to explain a GVE-diagram to someone by pointing out special persons.

**Comment by schuco** [comment]
Before I leave for a journey one further comment on probably important improvements.
This is not important for me, but may be very important for installations without GraphViz .

I could not test creating SVG or PNG files with browser rendering so it may already now be possible to produce PDF directly. In case that this is not so, direct output in PDF would be desirable.
In my experience the optimal output for diagrams is in PDF. This has very small size compared to PNG or JPG and it can be scaled much better in a browser. Also a normal user like me can't handle SVG and will not send it to even less experienced family members.
Therefore producing PDF-output  in installations without GraphViz seems to be important.

**Comment by Neriderc** [comment]
> If you stepwise build up a tree it is sometimes complicated to find the starting person in a big diagram as GraphViz reorders the tree-picture in every step. Could there be an option to highlight the starting person(s)? This would also be helpful if you want to explain a GVE-diagram to someone by pointing out special persons.

Yes, I agree this would be great! How do you imagine this looking? Maybe something like having a different background colour for the the starting person(s)? Making them larger? Something else? Ideally this would be easy to find even on a really big diagram - probably changing the background colour of the individual would be the easiest way to achieve this. But I'm happy to hear suggestions.

> In my experience the optimal output for diagrams is in PDF. This has very small size compared to PNG or JPG and it can be scaled much better in a browser. Also a normal user like me can't handle SVG and will not send it to even less experienced family members.

SVG should open fine in any modern browser, but I agree, it's not the format I'd choose if sending the file to someone else. We have PDF export covered in #24 but it hasn't been looked at in any detail (it is already supported if you have GraphViz installed on the server). I had a cursory look a while back and it didn't look as simple as the other file types. I'll have a proper look at it after looking at #51 which I'm looking at now.

**Comment by schuco** [comment]
Changing background color!

**Comment by Neriderc** [comment]
Sounds good! I have created #240 to do this. It's reasonably straightforward to do, I'll finish what I'm working on then make this change.

**Comment by Neriderc** [comment]
Just so it's clear, I intend to leave this here for a while, anyone can reply and say what's important to them, or suggest their new ideas here if they don't want to create a new issue.

**Comment by schuco** [comment]
Lots of new options and possibilities in GVE fire the imagination for further application scenarios.
I could not sleep well last night and had the following idea. One could let the family history unfold with successive GVE diagrams as in time-lapse: starting with the earliest ancestor and progressing in selectable time periods, the living individuals and completed families (marriages) in the respective time period could be highlighted in the diagram as can be done for starting persons.
The resulting diagrams could be either downloaded one after the other or shown one after the other in the browser (possibly superimposed).
A problem certainly will be missing dates for birth, death and marriage especially in early periods. There it could help to obtain the data from the clipboard, where missing information could be temporarily replaced with plausible assumptions. Also an extended clipboard menu could be used for the options and input parameters.

**Comment by hartenthaler** [comment]
Have you seen the huhwt-wtlin module and it's Timeline function?

**Comment by schuco** [comment]
I have tried it by selecting my ancestors with their families and displayed them on the LIN timeline. 
I still have problems with the rather abstract description of LIN and TAM I have found. Is there a description with the interpretation of what you see by an example?

**Comment by hartenthaler** [comment]
The documentation for TAM and LIN is not finalized. And the modules are really complex.

- [actual LIN documentation in German at GitHub repository](https://github.com/huhwt/huhwt-wtlin/blob/master/README.de.md)
- [LIN in German webtrees manual](https://wiki.genealogy.net/Webtrees_Handbuch/Anleitung_f%C3%BCr_Webmaster/Erweiterungsmodule/TAM_und_Lineage/Lineage)
- [TAM and LIN  in German webtrees manual](https://wiki.genealogy.net/Webtrees_Handbuch/Anleitung_f%C3%BCr_Webmaster/Erweiterungsmodule/TAM_und_Lineage)

There are several screenshots available in the documentation. Maybe you can select one. Then I (or the author of this module) can try to explain it in more detail. Or take a screenshot of your data and then open an issue at the GitHub LIN site.

**Comment by schuco** [comment]
@hartenthaler thank you, I will come back to you after my broken  laptop will be repaired

**Comment by schuco** [comment]
I have been using v 2.1.18.1 for a while now and appreciate its versatility and added useful tools.
So I used saved settings to update notes on family branches by having one saved setting (downloaded) for each diagram in the notes. Updating is quite easy now and automatically inludes the latest state of the database..
I had a problem storing my be too many saved settings and will report this in a seperate item. The same for a slight problem setting resolution options for jpeg-files.
Here are some proposals or wishes for further improvements or new features:
1. Option to rename saved settings. 
2. There is the nice feature to search individuals in a diagram and center the display around these. Could there be the option to mark this individual with a certain colour like what can be done for starting individuals? Often I  have to set an individual to be a starting individual only to get it marked.
3. I come back to an issue I have repeatedly put forward: The reaction on the click on an individual in the diagram.
  - you can choose the treatment of starting individuals in the advanced options (default, add to list, ...) . I personally would prefere to see this option field in the primary menu, as I want to know which reaction can be expected and also to be able to switch this setting easily
  -  maybe these options can be even extended by an option, where a click does not result in going to the individuals page but rather in adding this individual to the list of starting persons without leaving GVExport.

**Comment by Neriderc** [comment]
>     1. Option to rename saved settings.

At the moment you can click to load the settings, then change the name and save it again. Then delete the previous one.

Adding the functionality to rename the setting makes sense though, and shouldn't be difficult. I have added #442 


>     2. There is the nice feature to search individuals in a diagram and center the display around these. Could there be the option to mark this individual with a certain colour like what can be done for starting individuals? Often I  have to set an individual to be a starting individual only to get it marked.

I will have a think about how to do this. I am thinking perhaps have an advanced setting that has a list of XREFs to highlight. To make this more user friendly, we could have either the ability to search a person to add to the list (like in the starting individual's list), or we could have the ability to click a person in the diagram and add them to this list (or both). Any thoughts?

>     3. I come back to an issue I have repeatedly put forward: The reaction on the click on an individual in the diagram.

It's on the list! https://github.com/Neriderc/GVExport/issues/402

I have replied [here](https://github.com/Neriderc/GVExport/issues/402#issuecomment-1596430354) so that the thoughts are not forgotten!

**Comment by aXymmetrx** [comment]
Hi @Neriderc, I've been using webtrees with GVExport v2.1.18.2 and I can't thank you enough for your effort on supporting it.

I've only been using all of this stuff only for one week and it seems working as intended.

Until I hit a family with multiple marriage. For my case, a husband with 2 wifes. It seems that in GVExport (with 'Combined' Diagram type), it will create 2 sets of node for the husband paired for each wife. 

[Husband + 1st Wife + its Descendants] and [Husband + 2nd Wife + its Descendants] (marked purple and green in image respectively)

With a lot of individuals and families were added into the list, the visual produced seems odd for this family as it puts the [Husband + 1st Wife + its Descendants] and [Husband + 2nd Wife + its Descendants] really far away from each other. Which I think to compensate for the 'lines' for connecting the nodes. Here's the example:

![1](https://github.com/Neriderc/GVExport/assets/104315110/5fb1a795-cc72-46f5-81d3-17fca58c36b2)

I tried exporting the GEDCOM file from webtrees and open it on yEd. It turns out yEd visual out a straight connecting lines, and the husband node were only created once with 2 wifes are put closer/next to each his wifes. Here's the example:

![2](https://github.com/Neriderc/GVExport/assets/104315110/e5594d71-a982-4b4e-a3a2-862296becd24)

![3](https://github.com/Neriderc/GVExport/assets/104315110/89e2b411-b040-44a9-94d7-da329636a3f4)

So I wondering if GVExport can have such option? A straight connecting lines with no duplicate nodes when comes to multiple relationship? It looks doable on different software, so I'm guessing that it should possibly can work on GVExport too.

I may sound pedantic on this, but showing this graph to elderly people carries a lot of emotions for them. Having them to see their multiple partners were put farther away surely hits differently on them. Having me to explain to them that 'thats how the software tries to efficiently sort and fit the people in once place' is beyond my imagination for them to understand.

Sorry for the long post. I hope I can get your comment on this. I'm not really understand how does this stuff works. I hope you can spare me off.

Anyway thanks!

**Comment by Neriderc** [comment]
I've created a new issue to track this, @aXymmetrx did you want to take a look? #455

**Comment by WeT-Klb** [comment]
If you choose 3 or 4 generations, would it be possible not to reduce the size of the graphic?
It would be nicer if the individual persons were displayed in the same size, but the graphic could be moved accordingly - as in "MyHeritage".
![GVExport with 2 Generations](https://github.com/Neriderc/GVExport/assets/20600342/f49a3d6e-fba4-4b5e-af0c-64f53a1a0e45)
![GVExport with 3 Generations](https://github.com/Neriderc/GVExport/assets/20600342/db52b660-0411-49d1-bd60-3fda73d29c71)
![GVExport with 4 Generations](https://github.com/Neriderc/GVExport/assets/20600342/a2732cff-232c-499c-a5ad-cb90c7f1e8a7)

**Comment by Neriderc** [comment]
@WeT-Klb so your preference would be that the view would be up close like in your fist image, even if your diagram was large? 

I don't want to promise anything before I've tried, but I don't see why it couldn't be done this way. It would just be a bit of maths to calculate the right zoom level, which seems doable. If you could confirm that is what you want (up close) then we can create a new issue (feel free to do this if you'd like) and I can start working on it.

**Comment by WeT-Klb** [comment]
Exactly. My personal opinion is that the view as in "MyHeritage" would be optimal. For example, you can select a person and then navigate through the whole tree by moving the graphic. Have you ever seen that there?
In my personal opinion, that would be the icing on the cake.

**Comment by marwelin** [comment]
It would be nice to have a marriage date prefix like ∞ in the diagram.

**Comment by marwelin** [comment]
The name abbreviation "First given name and surname" would be great for complete but compact diagrams.

**Comment by Neriderc** [comment]
Thanks for the suggestions! I've created a couple of "issues" to track them. They should be pretty straightforward, so I'll aim to put them in the next release.

**Comment by marwelin** [comment]
Thank you for adding the "issues" 😄 
I just had some additional ideas for a complete but compact view...

**Comment by marwelin** [comment]
To shorten the width of the diagram, all dates (Birth, Death, Marriage) may get the additional option "compact date", which uses only the first three characters of the month.
For example: 12. Nov. 2024 instead of 12. November 2024

**Comment by marwelin** [comment]
The birth and death locations stand behind the date, but the marriage location has an extra row.
Is there a reason for that behaviour or may the marriage location stand behind the marriage date.
For example:
   20. Mar. 2024 (Anywhere)
instead of
   20. Mar. 2024
   (Anywhere)

**Comment by marwelin** [comment]
The arrow-line between person frames does not begin direct at the start-frame, but its arrow ends direct at the target-frame.
May the arrow-line start direct at the start-frame?
The reason for that is: I had situations, where it looked like, that the arrow-line started in another horizontal arrow-line.

**Comment by Neriderc** [comment]
> To shorten the width of the diagram, all dates (Birth, Death, Marriage) may get the additional option "compact date", which uses only the first three characters of the month. For example: 12. Nov. 2024 instead of 12. November 2024

I'll add this one as another issue. It should be simple enough to do.

> The birth and death locations stand behind the date, but the marriage location has an extra row. Is there a reason for that behaviour or may the marriage location stand behind the marriage date. For example: 20. Mar. 2024 (Anywhere) instead of 20. Mar. 2024 (Anywhere)

Which diagram type are you using? With the Separated type, having the location at the end stretches out the oval:
![screen shot of family tree showing oval representing marriage is very wide](https://github.com/Neriderc/GVExport/assets/89974636/fd276202-d423-4032-91fb-9f84a2163531)
Compared to underneath:
![similar to above but marriage location is under marriage date, now the oval is taller and less enlongated](https://github.com/Neriderc/GVExport/assets/89974636/35038198-2f59-4425-8726-d6441ff9c3a1)

I think combined mode would look better side by side though, is that what you're meaning? Maybe we could change it to be side by side only for combined mode?

> The arrow-line between person frames does not begin direct at the start-frame, but its arrow ends direct at the target-frame. May the arrow-line start direct at the start-frame? The reason for that is: I had situations, where it looked like, that the arrow-line started in another horizontal arrow-line.

I don't know that we get much say in this. The diagram is assembled using Graphviz (hence the name GVExport), and it has been tricky in the past to make small tweaks like this. I've never seen it far enough away that I could get confused over who it referred to. What settings are you using for diagram? In particular, separated or combined, and top-to-bottom or left-to-right?

**Comment by marwelin** [comment]
> The birth and death locations stand behind the date, but the marriage location has an extra row. Is there a reason for that behaviour or may the marriage location stand behind the marriage date. For example: 20. Mar. 2024 (Anywhere) instead of 20. Mar. 2024 (Anywhere)

Have you noticed this proposal, too?

**Comment by marwelin** [comment]
I use the combined-type and top-to-bottom.
Yes, you are right, the separated-type looks better with 2-line "date \n location"
and the combined type looks better with side-by-side "date (location)".

**Comment by marwelin** [comment]
> The arrow-line between person frames does not begin direct at the start-frame, but its arrow ends direct at the target-frame.
> May the arrow-line start direct at the start-frame?
> The reason for that is: I had situations, where it looked like, that the arrow-line started in another horizontal arrow-line.

I just can't reproduce the situation.
Maybe the situation was eliminated by reordering some children order in webtrees yesterday.

**Comment by Neriderc** [comment]
Ok great, I'll plan for these in the next release, and further discussion can happen on the individual issues.

**Comment by marwelin** [comment]
What do you think about this idea:
If a couple is married, but nothing else is known about marriage, the marriage prefix ∞ could be shown in the diagram even without date+place.
This would allow to distinguish a married couple from a not married couple in the diagram.

**Comment by Neriderc** [comment]
I believe that's how it's implemented!

If you want to try out the changes before an official release, you can download the main branch. Basically go to the "code" page on github, click the bright green "code" button, and download the zip file. Install as usual, making sure you remove any dots in the folder name as webtrees will ignore extensions with a dot in the folder name.

**Comment by marwelin** [comment]
I am trying out the main branch now. As there is no extra issue for the last proposal, I answer here.
Thank you. It works exactly as I imagined.

Nevertheless here is an additional thought regarding this issue:
There are so many symbols for couple relationships. Here they are
- ∞ (or oo) for marriage
- I∞ for 1st marriage
- II∞ for 2nd marriage
- o for engaged
- o|o for divorced
- o-o for relationship (not married, illegitimate or common law union)

I think we do not need most of them in the diagram, except of ∞ for marriage.
What I am not sure about is the o|o symbol for divorced.
Is divorced important enough to be shown in the diagram? (maybe enable/disable configurable)

**Comment by hartenthaler** [comment]
For me it would be the most important:
- no symbol = not married
- marriage symbol = married and no divorce known
- divorce symbol = married and divorced

**Comment by marwelin** [comment]
I can agree with the first two
- no symbol = not married
- marriage symbol = married and no divorce known

I do not agree to the third, combining the divorce symbol to married and divorced information.
This is because, the marriage date and place is often known and important regarding to childrens names.
The divorce event is often known, but not the date and place.

If a couple is married, the married symbol +date +place should always be shown.
And if the couple is divorced, the divorce symbol +date +place should be shown **additionally** to the married information.

**Comment by hartenthaler** [comment]
What should happen if a couple marries, gets divorced, and marries again? You can enter such a case in two families or in one family. If there are two families this is shown already correctly in GVExport with two boxes as shown in the diagram (Niarchos was married two times to Livanos). 
![gvexport (10)](https://github.com/Neriderc/GVExport/assets/6324175/e4ea9337-321c-4c29-b7cc-0b64db676378)

If it is entered in one family, GVExport shows only the first marriage. I would expect that GVExport shows all events in the family, ie the first marriage event, the divorce event and the second marriage event.

**Comment by hartenthaler** [comment]
There were already intensive discussions about 1 or 2 families in the past. There are advantages and disadvantages for both. I agree with you @marwelin to prefer 2 families, but both options are possible in webtrees and in GEDCOM. The disadvantage of 2 families is: if there are children born during the first marriage and other children born during the second marriage they are now called step-brother/sister and not brother/sister which feels more natural.

**Comment by marwelin** [comment]
@hartenthaler The described disadvantage of 2 families of the same couple can be solved in webtrees. 
webtrees knows from the INDI tags, that the persons of the FAM tags are equal. In that case webtrees should be able to distinguish right between brother/sister and step-brother/sister.

**Comment by hartenthaler** [comment]
GVExport is a great and very flexible tool! I just used it to show how a small, but complex family can be shown. See https://discourse.genealogy.net/t/ungewoehnliche-stammbaeume-visualisieren/822464/23

**Comment by Neriderc** [comment]
I think everything in this post has been addressed, but it's getting long so I thought I'd create a fresh new one. If something isn't already captured in an open issue, we can discuss it in the new issue [here](https://github.com/Neriderc/GVExport/issues/487) and I'll close this one.
