### ISSUE TITLE
Add help text system

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#233]
We have a wiki, but we should add help directly into GVE so you can see help text related to the field you are currently looking at. We should also have a link to the wiki.

We could show help text when hovering over a field, or we could put an icon such as ℹ️ and clicking this could show help text.

We could have a "Help" button next to the "Reset" button. This could show a message with a link to the wiki and let the user know that issues should be reported here, and that discussion on new features and changes happen here.

**Comment by hartenthaler** [comment]
good idea! I would prefer an icon instead of hovering.

**Comment by Neriderc** [comment]
To close this issue, I propose we do the following things:

- Add the ability to display a "modal" popup message - a page of information that is displayed over everything, and can be dismissed by a close button to return to the normal GVE functionality.
- Create system where we can add a ℹ️ next to a UI element where clicking it would display a message.
- Add the ℹ️ buttons for each of the non-advanced settings (we can do those later)
- Add a help button next to the "reset" button that shows a link to the wiki, to the issues page, and maybe a blurb about what GVE does. In future this could have more. Pperhaps the current version. Maybe the release notes. But to start we want to limit the scope.

Then create a new issue that houses whichever parts are mentioned here but are not completed as part of this list.

I also propose we push this to release v2.1.16 as there's a fair bit of work in this, and there are several things that have been waiting almost a month to be put into a release so I think I'll release v2.1.15 without this and move this to the next release. I'll try to get v2.1.15 out in the next few days, once I find some time to test it.

**Comment by Neriderc** [comment]
I just had a thought, we should add the icon after the name of each category grouping, i.e. the while text on blue on the left. Then the help text for this section should explain the different options in that section.

**Comment by Neriderc** [comment]
I've built a basic modal popup system. I've decided not to use the emoji ℹ️ and instead have created something similar that respects the theme (uses the webtrees colours for primary button - the same as the "update" button if you have automatic updates turned off). When I put the emoji in, it came out different and was hard to see.

I started writing the first message, for the "Include people related to" section. We discussed in #249 that we needed some good help text for it, so I thought I'd get some help :).

Here's what we currently have in the wiki. Any suggestions? Anything said here that isn't needed in a pop-up help? Anything missing? Any suggestions on phrasing this better? Is there too much detail here for someone just trying to work out how to use it?

> ### Include anyone related to
> This is our starting point. Choose a person to base the diagram around. You might choose yourself.
> 
> You can choose as many starting individuals as you wish. A tree will be created for each starting individual based on the settings, then the trees are merged to create one tree for the diagram.
> 
> Click the X to remove a record from the list. If two or more records are listed, a "Clear all" option will appear to allow you to remove all records.
> 
> You can also click on an individual in this list to have the diagram in the browser scroll to that person.
> 
> When you next come to the page, the default individual or the last individual you were looking at in webtrees will be loaded. If there was just one saved individual then it will be replaced with the individual provided by webtrees on coming to the page. If there were multiple in the list, then the individual provided by webtrees will be added to the list (if not already in it). So be sure to double check you are only including individuals you are looking for when first loading the page.

**Comment by Neriderc** [comment]
Ok no feedback, so my plan is to basically copy what's in the wiki as a starting point. We can adjust things as needed.

**Comment by Neriderc** [comment]
Version 1 complete!
