### ISSUE TITLE
Improve mobile support

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#234]
When using GVExport, we should make the experience more pleasant on mobile.

The settings panel should fit the browser if the panel is wider than the screen.

The height of the browser render should fit the available space. We should consider a full-screen mode for the browser render.

Other tweaks as they make sense (suggestions welcome).

**Comment by Neriderc** [comment]
I have now made the changes I listed above:
- Settings panel scales to browser width if browser is less wide than panel
- Render scales to available space (on mobile there is not much space because of the webtrees header menus)
- Added fullscreen mode

I just want to say fullscreen mode is awesome, and you should try it (you can do this by downloading the code from the main branch, or by waiting until the next release). It's supported on both mobile and desktop.

These small changes have made mobile _much_ more pleasant in my opinion. However, I'm keen to hear of any other changes people would like to see to make mobile.

I'll leave this open for a few days or a week. Let me know what tweaks you'd like to support mobile browsers better.

**Comment by schuco** [comment]
@Neriderc `These small changes have made mobile much more pleasant in my opinion.`
**_Definitely!!!_**
I can use GVE on my smartphone now, which was practically impossible before.
This is a big step forward.

Looking into the news from Github it is a bit like having Saint Nicolas morning every day. (In Germany children find some gifts "brought by Saint Nicolas".)
Every day we get big further improvements on GVE. Thank you again!
The full screen mode on Windows devices is also an improvement and makes GVE even more attractive!

**Comment by Neriderc** [comment]
It's good to know it's appreciated! I can't promise to always keep the same pace :slightly_smiling_face: 

Ideas are just as important as building them. I wouldn't have made anywhere near as much progress without you guys feeding in the ideas!

**Comment by Neriderc** [comment]
I'm going to close this for now. But I will say that from now I think we will officially support mobile. So if there are any issues on mobile (or ideas to improve it), please create an issue.
