### ISSUE TITLE
Make starting individual(s) stand out more

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#240]
On large diagrams it can be hard to find the starting person. We should make this easier.

The current proposal is to do this by using a different background colour for these people (other than white).

The "simple" diagram type gets it's colours in a slightly different way so this change will not include the simple mode.

In summary, we should:
 - Use a different colour for the background of all starting individuals
 - Allow the user to change this colour in the UI
 - Apply this change to just the Decorated and Combined modes

**Comment by Neriderc** [comment]
@schuco what colour were you thinking? I can make it customisable but it would be nice to have a good default.

Some examples:
A light yellow (#FFFDC3):
![image](https://user-images.githubusercontent.com/89974636/194687361-5a87f778-b01f-410f-8f8c-6a9260413a6d.png)

A light-ish grey (#DEDDDA):
![image](https://user-images.githubusercontent.com/89974636/194687431-5c4dc852-9782-4fc4-9694-99bbe1b2b136.png)

Purple-ish (#F4E3F5):
![image](https://user-images.githubusercontent.com/89974636/194687519-69def148-3173-4d06-96c6-62dad62f65fa.png)

We should probably try to avoid colours with other meanings, e.g. blue is used for male, pink for female, yellow for other gender and another shade of yellow for family records, and green for unknown gender. However, I do like yellow the most out of these, and I think the shade here is different enough from the other yellows used.

You might have ideas for other colours that might look better.

I also have an alternate idea. We could use the non-related colour to fill the background based on gender. E.g:
![image](https://user-images.githubusercontent.com/89974636/194688373-4cfca09a-24fa-43c2-90a9-4cd904faa5d9.png)

In this case we would not have a customisable colour but instead a checkbox to enable/disable using the non-related colour to fill the background of starting individuals. I think this one looks nicest, however, it might not quite be obvious enough to find it quickly in a large diagram. The yellow is definitely easier to find.

**Comment by schuco** [comment]
Yellow would be the best signal
Greetings from an Italian motorway

**Comment by Neriderc** [comment]
> Yellow would be the best signal 

It is done!

> Greetings from an Italian motorway

Greetings from Saint Nicolas! There are two presents waiting for you when you get back (possibly even packaged into a release depending on when it is you return).

P.S. I hope someone else is driving as you check Github!

**Comment by schuco** [comment]
### Selection field in every starting person field to switch of highlighting

The option of highlighting starting persons has proved to be very helpful.
Together with the recently introduced new feature to save settings it is very helpful to prepare stories about family history like "_owners of a farm with change of generations_" or "_my relationship to aunt Mary_".
A complex diagram is much more informative and can be better explained with starting persons highlighted. Also its easier to find a person of interest in a big diagram by the feature to click on the starting person field.
However in a diagram with several starting persons you will often use some starting persons just to get an optimal  form or scale of the diagram, but they are not interesting in the context of the issue to be presented.

**Could there be another selection field added (additional to the delete "x") to every starting person field to switch of highlighting (if generally switched on).**
Thereotically  an own list of highlighted persons could be provided, but this would explode the menu even more. Also in most cases you will have added the persons of interest in the list of starting persons. 

Another, somewhat related idea for further improvements would be to have a **search function** to jump (center the diagram) for persons within the diagram.
