### ISSUE TITLE
Links do not work on mobile

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#249]
When using a mobile browser, links do not work. These work fine on desktop browsers.

Possibly related to the[ deprecation of xlink:href](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href).

**Comment by Neriderc** [comment]
Just an update, changing the deprecated xlink:href to href did not help. This will require further research.

**Comment by Neriderc** [comment]
@schuco give the main branch a go now!

It turned out that, long story short, the "panzoom" library (that provides the code for panning and zooming the browser render) disables mobile touch actions because dragging the diagram would also cause the page to be dragged around on mobile. Disabling these actions also disabled click actions, so links didn't work.

I've fixed it now, basically by disabling that part of panzoom (which they luckily provide functionality to do), and then preventing the page being dragged around in another way.

It works great for me, but it would be good to confirm if it works for you too!

**Comment by schuco** [comment]
Returning from Italy tonight I was eager to see the gifts promised by Saint Nicolas
1. The ability to set defaults in the wt-control menu is excellent an covers more than my expectations
2. Highlighting starting persons works fine and proves to be very helpful
3. Diagrams are clickable on both of my Androids (Samsung tablet S7 FE and mobile S20 FE). On the smartphone it is sometimes a bit tricky to find and focus the diagram but it works fine.

There are some observations regarding the selection menu I would like to mention here:
1. The process of accumulating starting persons works perfect for me. But would a beginner know or detect just by doing that unless you have already entered a second starting persons further starting persons can be just collected by clicking? There may be 2 solutions:
- explain it in a help text
- add a selection field (accumulating starting persons by further clicks)

2.  If you want to define more than one "stop-processing person" these are entered by XREF.  Could this be done in the same way as with the starting persons?

3. There is an explanation text **_"SVG only"_** for the item _Add URL to individuals and families_ 
- isn't it also for PDF?
- isn't automatically set for browser rendering (preview)?
- is it necessarily to be shown for any user or could it be seen in advanced settings?

**Comment by Neriderc** [comment]
> 3\. On the smartphone it is sometimes a bit tricky to find and focus the diagram but it works fine.

Sorry, could you explain what you mean by this? I find if I go fullscreen on my phone, move around to look at things, often when I leave fullscreen the smaller view is all grey because it only shows the top left of what I was looking at in fullscreen. Is this what you mean? It might help to know that you can click on a person in the starting persons list to have it scroll to that person.

> 1. The process of accumulating starting persons works perfect for me. But would a beginner know or detect just by doing that unless you have already entered a second starting persons further starting persons can be just collected by clicking? There may be 2 solutions:
> 
>  * explain it in a help text

Having something intuitive would be preferable to needing help text to explain it, but we are also a little limited on what we can do by the search field that webtrees provides. However, we can gather ideas and see how close we can get to fulfilling them.

>  * add a selection field (accumulating starting persons by further clicks)

Could you elaborate a bit more on this idea? Currently we have a selection box, and you can add further starting persons. Do you mean leaving the selection box "open" (keep showing the search results) after the first person is selected?

> 2\. If you want to define more than one "stop-processing person" these are entered by XREF.  Could this be done in the same way as with the starting persons?

This is planned but I realise we don't have an issue for it, so I've created #251 

> 3\. There is an explanation text **_"SVG only"_** for the item _Add URL to individuals and families_

This has been inherited from the previous version. But we can of course consider changes.

>  * isn't it also for PDF?

Yes and no. Links do work if you have GraphViz installed on the server, but do not work if using the new client-side PDF generation. The basic reason is that GraphViz converts the SVG to PDF, while the client side converts a PNG image to PDF. And the reason for this is that I could not find a reliable SVG to PDF converter that runs on the client side.

>  * isn't automatically set for browser rendering (preview)?

Currently the browser render respects the setting. Should we change this? It should be simple enough to always include links for the browser render.

>  * is it necessarily to be shown for any user or could it be seen in advanced settings?

Currently photos are not shown by default. I didn't change this, but wanted to ensure users knew the option was there, so I left it out of the advanced section. Following this, it seemed logical that including links and including photos should be placed together, and that's why I didn't move the link option to the advanced section. How about we enable photos by default (links is already enabled by default), then move both into the advanced section?

Abbreviated names and places could probably be moved to the advanced section as well.

**Comment by schuco** [comment]
> > 1. The process of accumulating starting persons works perfect for me. But would a beginner know or detect just by doing that unless you have already entered a second starting persons further starting persons can be just collected by clicking? 

> 
> Having something intuitive would be preferable

The present approach to accumulate starting persons by clicking on names has the disadvantage, that you can't get a diagram just for the clicked person. Rather, as soon as two starting persons have already been collected, you get a diagram for all previously accumulated starting persons.
Could that be changed that when you click an individual in a GVE-window, get the individuals page and open GVE from there, then the diagram only displays this individual as starting person **_unless_** the option to accumulate starting persons is set. 
With the previous solution to add XREFs to a list we had the ENTER-symbol to accumulate the selected XREF to the list.
Could we have a similar selection-field, named e.g. "accumulating clicked individuals" which is set non-selected and not highlighted by default. Clicks on names in the diagram will show the individuals page and selecting GVE from there will only display the clicked individual. 
As soon as you have clicked the accumulation-selction-field it switches to be highlighted and clicks will result in using the accumulated list of starting persons.
Sorry for my English and ignorance on IT-terminology.

**Comment by schuco** [comment]
> How about we enable photos by default (links is already enabled by default), then move both into the advanced section?
> 
> Abbreviated names and places could probably be moved to the advanced section as well.

That would be o.k.
May be the text could be something like "SVG and server side downloaded PDF only"

**Comment by hartenthaler** [comment]
> How about we enable photos by default (links is already enabled by default), then move both into the advanced section?

yes and yes. But I like to have the possibility to switch off the link option even in the browser, because sometimes when I drag-and-drop the diagram I accidentally click on a person and then the person page opens and then I have to go back to that last window.

> Abbreviated names and places could probably be moved to the advanced section as well.

yes.

Regarding the selection of start persons: for me, it works perfectly as it is now. I would prefer not to add more complexity to this function.

**Comment by Neriderc** [comment]
> > Sorry, could you explain what you mean by this? I find if I go fullscreen on my phone, move around to look at things, often when I leave fullscreen the smaller view is all grey because it only shows the top left of what I was looking at in fullscreen. Is this what you mean?
> 
> That is what I mean.

It would be nice to not have this issue, but it's hard to think of a good solution. When exiting fullscreen we could scroll to the (first) starting person, but I would imagine this could be quite annoying in some circumstances. Probably better would be to try to have the smaller view be focused in the middle instead of the top left. That should be doable with a bit of maths.

> Instead a multiple choice dropdown field could be inserted into the present empty field to enter further starting persons. 

We don't have a lot of control over this search field. It is provided by webtrees, and in fact it was not made for webtees, it's a "library" (reusable piece of code) called tom-select. Some things are possible but I don't think what you've proposed would work (technically) within the current system.

I also agree with @hartenthaler that we don't want to add complexity, especially for beginners. However, we have discussed in the past having an option for how GVExport handles the XREF passed in from webtrees. Currently if we have just one selected person, if we come in from another page we replace them. If we have more than one, then the new XREF is added to the list.

What if we added a dropdown in the advanced section of the "People to be included" section, perhaps just below the list of XREFs, that had the options:
1. Default (what happens currently)
2. Always add to list
3. Always replace

Then the user can override the action without needing to add complexity to the selection process. Although I note both of you have said the current system works great for you, so unless it will actually get used then perhaps there is no need for this setting.

> That would be o.k. 

> yes and yes.

Great, I've created #252  to make that change.

> May be the text could be something like "SVG and server side downloaded PDF only"

We have more options. A couple that come to mind:
- Alter text based on if GraphViz is installed. i.e. say "SVG only" when GraphViz not installed, "SVG and PDF only" when GraphViz is installed.
- We could grey out (disable) the option when it would not have any effect. 

Or we could do both of these things. When SVG selected, don't show any message. When PDF selected, only show the message when GraphViz isn't installed, and disable the option. When anything else is selected, show the appropriate message (based on if GraphViz is installed) and disable the option.

**Comment by Neriderc** [comment]
> My argument was, that the present solution is fine for experienced users, but may be not for a beginner. Does a beginner understand, why and in which cases a call to GVE results in accumulating the starter list? I agree my drop down proposal may not be helpful for a beginner. So a good help- function may solve it best.

Yes I think in lieu of a great idea, some good help text will have to do. We have a plan #233 to add this into GVE instead of needing to go to the wiki. Current plan is to have an ℹ️ icon that you will (probably) click to show help text about the specific setting (i.e. every option will have the icon next to it for help text specific to that option).

> Isn't it that the option **always** has an effect when server side (browser) rendering is done?

It's true that the option would always have an effect on the browser rendering - and @hartenthaler is keen to keep it this way, so you're right, disabling the option wouldn't work. We could alter the text based on whether GraphViz is installed. Would we want to reference the browser rendering? Should we say "(only affects the browser rendering, SVG, and PDF)"? Except don't say PDF if GraphViz is not installed.

And on that note:
> sometimes when I drag-and-drop the diagram I accidentally click on a person and then the person page opens and then I have to go back to that last window.

I'd actually like to fix this at some point. I have read a few people on the panzoom github page having somewhat similar issues, it's probably a bit of trial and error to fix but I hope we can fix it. The idea would basically be that if you drag it (more than some minimum) then the click wouldn't count.

**Comment by hartenthaler** [comment]
> The idea would basically be that if you drag it (more than some minimum) then the click wouldn't count.

That would help! Good idea!

**Comment by Neriderc** [comment]
I've created #253 for this :slightly_smiling_face:
