### ISSUE TITLE
Resize images before generating files with embedded images (server side GraphViz)

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#258]
As described in #75, file sizes (and related memory issues) could be improved if we scale images to a consistent size (based on the DPI) before embedding the images in the file. This issue is for the server side GraphViz process. We should change this to:

- get photo from webtrees and resize (or have webtrees resize it)
- save the file to a temporary directory
- repeat for each photo
- feed the location of these files into the DOT file for GraphViz to consume
- delete the files when done

This needs to be applied to the SVG and PDF types. Other types may have this applied if it is the more practical option, but it won't make a difference to file size.

**Comment by schuco** [comment]
Responding to my comment on #271 @Neriderc  explained to me the problem of including raster graphis images into vector graphic. 
I do now understand why playing around with DPI setting makes no sense and a better solution may be expected from this issue #258:
```
file sizes (and related memory issues) could be improved if we scale images 
to a consistent size (based on the DPI) before embedding the images in the file. ...
We should change this to:

- get photo from webtrees and resize (or have webtrees resize it)
```
Reading the discussion in the webtrees forum on thumbnails it seemed to me as a non-IT-expert that webtrees does already provide resized image files:
https://www.webtrees.net/index.php/en/forum/help-for-2-0/35864-thumbnail-instead-of-icon
There webtrees-administrator Greg Roach explains _"We have half-a-dozen different thumbnails in different sizes and aspect ratios. For each of these, we can have up to 4 versions with different DPI resolutions."_

**Comment by Neriderc** [comment]
Yes I've found when requesting an image from webtrees, you can specify the size you want it. However, Graphviz takes the files from the hard drive while the resized image from webtrees is in the form of a download URL. So I'll need to look at if it's easier to resize the image on the hard drive directly or to download via webtrees then save to the hard drive for Graphviz to access.

This is something I've been looking at as I get time and I don't have concerns, I think it's doable.

**Comment by Neriderc** [comment]
@schuco I've got this working. I couldn't use webtree's scaling, the only way webtrees makes this available is via URL (i.e. you can't access the functionality directly from the back end), and we can't access a URL because to do that you have to be logged in. The user's browser is logged in, but the server is not logged in so can't access the URL.

Instead I'm using a similar system to how the DOT file is fed to Graphviz, by creating a temporary directory and copying the images there, resizing them as it goes. The temporary directory is the operating systems temporary directory (e.g. on linux this will probably be /tmp, in docker this will be /tmp within the docker container, windows is probably %appdata%/Local/Temp though I haven't checked this).

It seems to work, for PDF I had a 130MB PDF come out at just 10MB, so this does seem to be a large improvement (though this will depend on the original resolution of the photos).

This has been merged into the main branch so feel free to give it a go!

**Comment by schuco** [comment]
I am away from home. I will try as soon as I am back home

**Comment by Neriderc** [comment]
No hurry, give it a try when you get time.

**Comment by schuco** [comment]
I wrongly thought that I already had answered. Sorry!
Your resizing approach works fine. The diagram which always crashed when I tried to download now comes out with a quite small pdf-file.

There  seems to be a different small problem with photos displayed in a server side generated pdf. The photos seem to be scaled to a uniform format:.
![grafik](https://user-images.githubusercontent.com/5896925/204624696-4569e733-3b15-46ac-b6b0-be638150cc74.png)
In the example shown the upper original photo was almost standard portrait format, the middle and lower ones were landscape format, now squeezed to portrait format.
In the browser generated diagram the proportionality is correct.

**Comment by Neriderc** [comment]
I've had a test and found the same thing in some of mine. I rolled back versions and found this issue first appeared in 2.1.10 about 3 months ago. It's not related to this change and seems to be related to the major diagram redesign. It also occurs in all output types for me, not just PDF.

I have created #286 and will look at how to resolve it.
