### ISSUE TITLE
Translation incomplete

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#262]
In the name selection:
"Given and **S**urnames" versus "Given and **s**urnames" does not allow the translation.

**Comment by Neriderc** [comment]
Thanks for spotting that. I'm thinking there's no reason for the capital, I think we should update to have all options start with a capital and then be lower case for the rest of the phrase. This would also affect one other item in that list.

In addition we may want to consider updating the place abbreviation list:
![image](https://user-images.githubusercontent.com/89974636/200049773-0fbf44a5-d67c-4a56-ad59-9772d3c21bb1.png)

And possibly even these:
![image](https://user-images.githubusercontent.com/89974636/200050118-ec4637ea-f74d-4eb8-a031-7ab31e2ebb47.png)

And then it raises the question of whether we should change these as well:
![image](https://user-images.githubusercontent.com/89974636/200050431-34bbaecd-a40f-4ab5-9597-17dbdf19b5be.png)

Grammatically, I'm not aware of any reason for capitals for each word like that. The vast majority of the options start with a capital and are followed by all lower case. so it seems to make sense that we should keep that consistent.
