### ISSUE TITLE
Help system

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#272]
It works great! Thank you!

- "If selected, the browser rendered diagram will automatically update when any option is changed. This will also hide the "Update" button." should be "If the option "Auto-update" is selected, the browser rendered diagram will automatically update when any option is changed. This will also hide the "Update" button.". Alternatively, a new headline "Auto-update" can be added in the help text.
- I suggest replacing two times 'you would type 3 in this box by 'you would type "3" in this box'
- there should be information on how to toggle the advanced options (maybe in the first help text or in all related help texts)

**Comment by hartenthaler** [comment]
- In "File types SVG, PNG, JPEG, and PDF can be downloaded," there should "JPEG" be replaced by "JPG"

**Comment by hartenthaler** [comment]
In the main help text there should be help for

- Fullscreen mode and button
- main buttons: Update, Download, Reset

In the German translation I added a remark about the clippings cart.

**Comment by Neriderc** [comment]
Thanks for the suggestions! Lots of good ideas.


> * In "File types SVG, PNG, JPEG, and PDF can be downloaded," there should "JPEG" be replaced by "JPG"

Yes, I think so. In the backend it's JPEG because this is the data type of the image file, which is probably why I wrote it that way as it's how I'm used to seeing it. But the frontend does use JPG so we should keep it consistent and call it JPG (unless we want to change everything to say JPEG, which I believe is it's official name. But I _think_ JPG is more recognisable to the average person so we should probably leave it as that).

**Comment by Neriderc** [comment]
I've made these changes. I'll leave open for the moment for any more suggestions.

**Comment by hartenthaler** [comment]
As you can see at https://graphviz.org/ Graphviz is written now with a lowercase "v". We should respect this.

**Comment by Neriderc** [comment]
I've spent so long reading Graphviz documentation I can't believe I never noticed this. Using archive.org it seems it may have always been this way. The GraphViz spelling is how the previous GVExport repositories spelt it and I never noticed the difference. I'll try to update this in the help and the wiki and wherever I see it wrong. Thanks for letting me know!

**Comment by Neriderc** [comment]
I've updated the wiki and readme file, as well as the terms in POEditor. I'll do a pull request when I get a chance.

You may have noticed, but I'm just working this out, in POEditor when I change a term (such as updating GraphViz to Graphviz) POEditor marks the translation as "fuzzy". If you go into (e.g.) German, you can choose at the top to show just fuzzy translations, so you can check they are still accurate. If they are, you can click the "F" button to un-mark them as fuzzy.

**Comment by hartenthaler** [comment]
Yes, I'm using this fuzzy button already.

**Comment by Neriderc** [comment]
Great!
