### ISSUE TITLE
Server side GraphViz output stretches photos

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#286]
As per [this comment](https://github.com/Neriderc/GVExport/issues/258#issuecomment-1331182306) in #258, server side generation of diagrams with GraphViz installed cause photos to be stretched in some cases.

**Comment by Neriderc** [comment]
@schuco I have made a change that should fix this. It still doesn't line up 100% with the browser view, but I've tried all the options GraphViz gives for displaying the image and this is the best I've come up with (which is actually just reverting the setting to what we had 3+ months ago).

Let me know how you get on :). You'll need to download the code from the main branch to test it.

**Comment by schuco** [comment]
Thank you. That looks good now
