### ISSUE TITLE
Text correction

### ISSUE THREAD

**Issue by TheDutchJewel** [Neriderc/GVExport#291]
> For SVG (and PDF is GraphViz installed on server) output, links can be included. This way you can click on the person in the diagram to be taken to their webtrees page.

Should be:
For SVG (and PDF `if `GraphViz `is` installed on server) output, links can be included. This way you can click on the person in the diagram to be taken to their webtrees page.

**Comment by Neriderc** [comment]
Thanks! I have made the change in the POEditor term and will probably do the code change in conjunction with the translated files a bit later since there are bound to be more errors :)

**Comment by hartenthaler** [comment]
Here there are some ;-)

> "Whether to include the webtrees Person ID in the output."

The XREF isn't a webtrees Person ID. The XREF is part of GEDCOM but not related to webtrees. So it should be: "Should the GEDCOM Person ID be shown in the diagram?" or "Should the XREF of a Person be shown in the diagram?"

>... If you have added individuals to the clippings cart ...

It is not enough to add Individuals to the clippings cart, you have to add the INDI and all related FAM and OBJE records. So it should be instead "... If you have added individuals and the related family and media records to the clippings cart ..."

**Comment by Neriderc** [comment]
Thanks, I've made those changes :)
