### ISSUE TITLE
Information about changed strings in the translation sources

### ISSUE THREAD

**Issue by TheDutchJewel** [Neriderc/GVExport#292]
Thanks, I've made those changes :)

_Originally posted by @Neriderc in https://github.com/Neriderc/GVExport/issues/291#issuecomment-1332643044_

Poeditor.com gives no notifications when strings in the translation sources are changed. This makes it very hard to keep translations up-to-date.

Is it possible to inform translators of about changed strings in the translation sources?

**Comment by Neriderc** [comment]
Hmm. To find those changes, you should be able to select the option to only show "fuzzy" translations. When a string is updated, it will be set to fuzzy. Once you've reviewed it you can toggle the fuzzy setting to un-set it.

But as for notifications, well, I have the ability to send a message to all POEditor users on the project, but I want to use this sparingly. I worry about sending too many messages and driving people away, or at least having them disable emails and therefore not keep the translations up to date.

I'm actually not sure what control you have over what emails you get. In my settings I only have one for comments, but also I'm the only one with access to add or update the base terms so perhaps I don't see pther email options.

What options are available to you regarding email notifications?

**Comment by TheDutchJewel** [comment]
> To find those changes, you should be able to select the option to only show "fuzzy" translations. When a string is updated, it will be set to fuzzy. Once you've reviewed it you can toggle the fuzzy setting to un-set it.

That was not clear to me. Thanks for the clarification!

These are the options I see:
![afbeelding](https://user-images.githubusercontent.com/46184729/205241608-7bbd465d-025c-425c-bb6e-880e921a2dc9.png)

**Comment by Neriderc** [comment]
> That was not clear to me. Thanks for the clarification!

I only recently learnt about the "fuzzy" setting! I agree it's not immediately clear what it's for, but I found a help page on it [here](https://poeditor.com/kb/fuzzy-translations). 


> These are the options I see:

I also only see that option for comments. I would have expected some settings for getting notifications when a new term is added, and ideally when a term is updated.
