### ISSUE TITLE
Use webtrees user preferences instead of cookies to remember settings 

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#307]
Remembered settings are currently stored in a cookie. If the user moves to another computer, they are lost. And come to think of it, probably another user on the same browser would override the settings.

In #299 we discussed the possibility of using the webtrees preferences saving system instead.

We should switch to using the webtrees preferences for saving settings. Existing cookies should still be loaded - but the cookie should then be deleted and the settings saved into the webtrees preferences.

**Comment by Neriderc** [comment]
This should go with release 2.1.17 as other changes made since 2.1.16 may become redundant with this change (I'm thinking of the change to storing the cookie in JSON). Probably best to sort out this before the next release.

**Comment by Neriderc** [comment]
Ok new issue - we can only save user settings if logged in. However, you don't necessarily need to require users to be logged in to use GVExport. We can't save preferences to webtrees for a logged out user.

I propose we keep cookies for logged out users. 

In my view if logged in, we should not set a cookie. We probably should not touch cookies, but how do we handle the transition? We release a new version that uses webtrees preferences instead of cookies, but everyone currently has cookies with their settings. Do we ignore these and reset to default, or do we load the cookie if found, and convert this to webtrees preferences?

If we load the cookie, how do we handle the situation where a logged out user makes some changes, then a different user logs in on the same browser and finds all their settings have been overwritten by the logged out user's settings because we loaded the cookie?

Should we have a load-once policy, where we load the cookies the first time one is found, but set a preference to say we have done it once and then never load cookies again for that logged-in user?

Or is it cleaner to just reset everyone's settings the first time?

Thoughts @hartenthaler and @schuco?

**Comment by hartenthaler** [comment]
Ok, use cookies for logged out users. Don't care about changing users that use the same browser. If my wife is using my browser she has to live with my settings.

Ignore cookies for logged in users. No conversion. Reset to default for the first time after the upgrade. Inform the user about that in the release note of the version.

**Comment by Neriderc** [comment]
I've found there's a separate set of functions for saving settings for guest users. These are tied to the session, I think our cookie approach is better for our purpose.

I have a first cut working, it seems to be just what I'd hoped. If the user is logged out, it saves and loads from a cookie. If the user is logged in, it saves and loads from user preferences (per tree). 

Preferences have a GVE_ prefix to keep them separate from other settings. I'll create the pull request soon.
