### ISSUE TITLE
Option: show XREF

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#31]
If you are using the Vesta modules and have selected to always show the XREF it makes no sense to show it two times.
![Screenshot (163)](https://user-images.githubusercontent.com/6324175/173814862-819cd1ea-f457-4850-8f11-078629a81726.png)

**Comment by Neriderc** [comment]
Given the Vesta modules are third party modules, what's your proposed solution to this?

**Comment by hartenthaler** [comment]
This problem is not new. The solution that was implemented the last time:

check the name of an INDI - if it contains "(...)" at the end of the name, then do not add an additional "(<xref>)".

**Comment by Neriderc** [comment]
Are there scenarios that this could break things? Does anything else add brackets like that? Perhaps we should only remove *specifically* the same text data. For example, we get the PID (say "X123")and then do a find and replace, replacing " (X123)" with "", prior to adding the PID? This way it would be more compatible with other brackets added for other reasons.

**Comment by hartenthaler** [comment]
Good idea! I can't think about anything else. And "(" or ")" is not allowed as part of a name. But who knows. Your idea is good.

**Comment by Neriderc** [comment]
I was thinking if there's one module that adds to the name in the form of brackets and XREF, then there may be other modules that add other info, so we should try not to interfere if possible.

**Comment by Neriderc** [comment]
Is this pull request what you were thinking? #41 

I'm not familiar with these modules, can you test that it actually works?

**Comment by hartenthaler** [comment]
Yes, this pull request is doing what it should. Tested. Perfect.

**Comment by Neriderc** [comment]
Awesome, thanks!
