### ISSUE TITLE
Topics in Diagram preferences versus Appearance

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#32]
From my point of view, some options should be moved from "Diagram preferences" to "Appearance", because they are influencing the appearance. Maybe "Diagram preferences" could be then renamed to "Content" or "Persons and Families".
![Screenshot (163)](https://user-images.githubusercontent.com/6324175/173815537-f0a42d31-5722-4ab3-be79-ec2ee7d9a656.png)

**Comment by hartenthaler** [comment]
"People to be included"?

**Comment by Neriderc** [comment]
Yes I think that would be ok.
