### ISSUE TITLE
Add ability to clear settings to control panel

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#320]
In Control Panel settings, we should add a button that clears all user settings. This should:

- Show warning dialog before clearing settings
- Clear all user settings if user chose to proceed - this should include all settings saved using #299 
~- Possibly also clear module settings? Or could leave this to built in process. User might expect these are cleared by this action.~

**Comment by hartenthaler** [comment]
> Possibly also clear module settings? Or could leave this to built in process. User might expect these are cleared by this action.

What will happen to the module settings if you press the "clear settings" button? Ok, they will be cleared. Then you have to press the save button to close the control panel window. I assume that then empty module settings are stored. So they are still there if you deinstall the module now. You can delete them now using the built-in webtrees process.

I prefer to not delete the module settings. The built-in process can deal with them.

**Comment by Neriderc** [comment]
I'm not sure if it's different for you, but when I click "Save" the page reloads and there is a message that the settings have been saved - but it does not go back to the control panel. To do this, I would click the bread crumbs at the top:
![image](https://user-images.githubusercontent.com/89974636/211117217-9100e2f8-28ec-4faf-9253-db1825911a30.png)

However, for this particular option I am not concerned one way or the other. I'm happy to leave module settings to the built in process. My only worry would be that users might expect that a button to delete preferences would also handle this - but some simple messaging next to the button can make sure users understand what it does.

One question is whether we need the ability to clear the module settings _without_ removing the module. In my view this is not necessary, as the "reset" button will reset them to defaults and I don't believe there is a need to actually delete them unless you are removing the module, but I'll ask the question anyway :slightly_smiling_face:

**Comment by Neriderc** [comment]
Closing this as after further discussion with Greg, I'm not going to use the user settings and will instead use the module settings. 
See further information here: https://github.com/Neriderc/GVExport/issues/299#issuecomment-1382969582
