### ISSUE TITLE
Endless rotating wheel when adding a "stop person"

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#322]
I'm just testing the latest development version with the possibility to save sets of settings. But whenever I add one or more "Stop persons" the diagram is not updated anymore (endless rotating wheel). This happens in my test and in my production system.

**Comment by Neriderc** [comment]
Sorry, this is my mistake. I changed the name of the setting and missed updating it in one important place.

If you update it should be fixed now.
