### ISSUE TITLE
Add easy to access list of saved settings, option to share

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#325]
We should add an optional new section at the top that has a dropdown list of saved settings.

This should be optional, enabled and disabled with a checkbox in the advanced settings in the File settings section, near where the settings are saved.

This should be disabled by default.

The intent is to add a way for an admin to create saved versions of settings for other users (via "Masquerade as user" in webtrees), then be able to present an easy to access list of settings that user can choose from.

Proposed mock-up:

![image](https://user-images.githubusercontent.com/89974636/214454520-7f4af321-220d-4b4d-b5ad-96c19828cd77.png)

Checklist:
- New section :white_check_mark: 
- Option to show or hide section :white_check_mark: 
- Disabled by default :white_check_mark: 
- Add to admin panel so default setting can be changed by admin :white_check_mark: 
- Load settings when settings ID in URL :white_check_mark: 
- Add ability to copy URL for these settings :white_check_mark: 
- Remove record of shared setting when saved setting record is deleted :white_check_mark: 
- Allow settings owner to un-share settings, removing record from shared settings preference :white_check_mark:

**Comment by Neriderc** [comment]
@schuco In the case that this has been "switched on", should the list remember what was last selected (in the same way that other settings are remembered) and load those settings?

Or when going to this page would this always default to not having something selected, and only load the settings when one is selected?

**Comment by schuco** [comment]
`We should add an optional new section at the top that has a dropdown list of saved settings.`
very good idea
```
should the list remember what was last selected (in the same way that other settings are remembered) 
Or when going to this page would this always default to not having something selected, and only load the settings when one is selected?
```
The alternatives are not really clear to me. So I try to describe how it might work in my opinion:
Assume a user has clicked on one of the prepared lists. He does **not change** any settings and logs out. When he logs in again and opens GVE I would prefere that he is shown a chart for the default starting person and not the prepared list.
Assume that he **has changed** (added or deleted) some of the prepared starting persons then these starting persons should be added to the list of starting persons (as usual) in a later session unless a reset has been chosen.

**Comment by schuco** [comment]
`The intent is to add a way for an admin to create saved versions of settings for other users (via "Masquerade as user" in webtrees), then be able to present an easy to access list of settings that user can choose from.`
Would it be possible to call a saved version by link? Then this link could be part of a HTML-block in a starting page or my page.

**Comment by Neriderc** [comment]
Yes we could do that, I don't think that would be too difficult.

Do you think the side panel should be hidden by default if settings are loaded from a link?

**Comment by schuco** [comment]
`side panel should be hidden by default if settings are loaded from a link`
Yes if its not too complicated

**Comment by Neriderc** [comment]
Shouldn't be too hard :)

**Comment by hartenthaler** [comment]
When it is possible to load a GVExport "settings" using a specific URL it would be possible to use the standard webtrees function "Favourites" to store and present such favourited settings. That would be great!

**Comment by Neriderc** [comment]
We can relatively easily add the ability to load settings from a URL, but how should the user obtain this URL? I think this is too difficult, too easy to accidentally delete the settings instead of getting the settings, right?
![image](https://user-images.githubusercontent.com/89974636/215038082-260e3389-a140-4f2b-8b52-ee125a2b3e5e.png)

Would it be better to use a ... and have a menu with the option to delete or copy link (and maybe more later)? I'm thinking like here on Github, you have the ... on each reply, with the option to copy a link to the post or delete the post (you possibly don't see this one):
![image](https://user-images.githubusercontent.com/89974636/215038474-d84594e7-e225-4f27-b49b-01f13616ecc2.png)

Does this seem like a good way of doing it? Or are there other ideas?

**Comment by hartenthaler** [comment]
The link icon beneath the "x" icon looks great, but you are right this can easily result in accidentally deleting this setting. The idea with the "..." is even better and has potential for the future (maybe "delete all settings").

But where to place the "..."? It should be clear what "Copy link" does mean: which of the settings will be used for the copied URL? If the "..." is in the "Save settings" block, then the "Copy link" should open a selection menu with all the settings, so that you can choose one. Or the "..." is related to each "settings" line and replaces the "x" button, then the menu can offer a menu with two lines "Copy a link to this" and "Delete this". Maybe there are more possibilities.

**Comment by Neriderc** [comment]
Yes, I was thinking it would be on each settings record, replacing the X, like this:
![image](https://user-images.githubusercontent.com/89974636/215254372-0eef8df5-a1ac-4cb8-b028-b046a3bdb31e.png)

**Comment by Neriderc** [comment]
How is this looking?
![image](https://user-images.githubusercontent.com/89974636/215311784-d59d9e2e-015e-4589-b583-b16b17fadb41.png)

**Comment by Neriderc** [comment]
Ok a new question. I really want to get this right before releasing 2.1.17 so we don't have anyone losing settings because we had to change how we saved them.

@hartenthaler you mentioned saving links in "Favourites". Currently, settings are unique to a user. You would not be able to have a link to some settings and have everyone see them, based on the original plan. It sounds like there may be appetite for settings that are not unique to a user. How do we see this working?

Should any item where the link has been copied be available to anyone?

If so, is it ok to just have it load via the ID (that it would be easy for someone to guess), or do we want to use a hard to guess URL so that only people who have been directly given the URL should be able to access it?

Just to clarify, you _must_ be logged in to access any shared settings. If you are not logged in, saved settings are stored in your browser and so can't be shared (except with others on the same browser). In theory we could have logged out users access shared settings but I suspect this is not really something we would want.

**Comment by hartenthaler** [comment]
First: I would prefer to have URLs which are hard to be guessed (pseudo encrypted). 

Webtrees has two types of favorites: one set is related to an user (on my page). And another set for each tree (not related to an user on the starting page of the tree). 

The first one was the one I'm thought about. So if I'm using such an URL link to a GVExport setting I would expect that GVExport is opened, that the tree is loaded that is mentioned in the settings, and that the settings is executed. So this is in line with "specific to one user and one tree". 

Now: about favorites per tree: they can be used for members (logged in) and visitors. Until now this was not foreseen by the GVExport settings. But it makes some sense, too. If an URL link was clicked in a tree favorites block, and the actual user and the user in the settings are identical and everything is OK. But what should happen if they are not identical (URL was published or sent to another user)? Option 1: processing is aborted by GVEXPORT ("there is no such settings for this user"). Option 2: ignore the user and load the settings of the other user the settings is related to. Maybe the actual user has other visibility rights than the original user, but this would be OK for me. So I would prefer option 2.

**Comment by hartenthaler** [comment]
But I understand that option 2 (ignoring the user) is a totally different approach compared to what was discussed until now. So it is absolutely Ok if you decide to choose option 1. 

If I would have the need to generate a favorite URL for another user, I then would do it the following way:
- prepare everything in my account
- store the settings to a file
- masquerade as the other user 
- load the settings from the file 
- store them to a user settings
- generate the URL link to his setting
- save this URL on the my page favorites of this user

**Comment by Neriderc** [comment]
> First: I would prefer to have URLs which are hard to be guessed (pseudo encrypted).

I think we can do that.

> But I understand that option 2 (ignoring the user) is a totally different approach compared to what was discussed until now. So it is absolutely Ok if you decide to choose option 1.

I've spent the day thinking about this. I think we can build this on top of the existing system. Currently we have settings saved as follows:

Settings_t2_u3 = {[settings here]};

Where t2 is tree ID 2 and u3 is user ID 3. The way settings are loaded means if you are not logged in as user 3 looking at tree 2, it's not possible to load these settings. However, let's add an additional field in the database.

In this field, we use JSON to store some new values. We would save a few values:

- The original user
- The original tree
- The settings ID

And as a key we would have a random sting of letters/numbers that acts as a lookup and token.

So basically have an array:

```
$shared_settings['ai3dsug6fhal7ku6ghlskdfh43gs435df'][user] = 3;
$shared_settings['ai3dsug6fhal7ku6ghlskdfh43gs435df'][tree] = 2;
$shared_settings['ai3dsug6fhal7ku6ghlskdfh43gs435df'][sid] = 9;
```

And convert this to JSON to save in the module settings.

When a settings record is shared, and _only_ then, a record would be created in this list. So that means if you have not shared settings, it would be impossible for someone else to see them, because a token for those settings would not exist.

If a valid token is provided from the URL, we would find it in the record, then use the stored user, tree, and settings ID to load the appropriate settings.

We could build this in a way that also worked for logged out users - but of course if you don't share the link then they would not be able to access the settings, and they wouldn't be able to see anything the wouldn't have been able to see by entering settings themselves.

And also if we do it this way, if the original user changes the settings (once #327 is implemented) then the settings that the users accessing the link see would also change. I presume this is what we want, so you can edit some saved settings without needing to update your favourites links.

For the record, brute forcing or accidental guessing is really unlikely. At 100 attempts per second, which probably your web server would not allow, it would take about 40,000 years to try every combination of a 10 character alphanumeric token. We can make it longer but I guess there's a question here about if users are only sharing via copy-paste or if they might want to write a URL on paper or print it out or otherwise have a person transcribe it to their browser rather than copy paste. Would we prefer longer tokens that are more secure or shorter tokens easier to share via methods other than copy paste?

10 characters:
`https://www.mywebtreessite.com/module/_GVExport_/Chart/treename?t=OM2UG4DISN`
20:
`https://www.mywebtreessite.com/module/_GVExport_/Chart/treename?t=7QZBXNCT58GG965HKUNQ`
50:
`https://www.mywebtreessite.com/module/_GVExport_/Chart/treename?t=GNX7C2VNSM5RYYHUQQAHP59N3FHB75KJ8U48RHLZHDFAU5BMGM`

URLs are already quite long, so maybe having a 50 character token is fine. But at the same time, settings will not show anything that a user could not have seen by setting the settings themselves, so perhaps a short 10 characters is more appropriate - not long enough to guarantee no one will ever guess but long enough that it probably won't happen.

So to summarise the things to do:
- Add token system for loading settings
- Add option to "Copy link" to settings, when allows them to be shared to anyone with the correct URL
- Add option to "unshare" settings, removing them from the shared settings. (I'm going to have to build this removal functionality for when settings are deleted, so might as well also make it an option for users)

And to summarise the input I'd like:
- Confirm less secure shorter token is preferred over more secure longer token that is harder to share (remembering sharing settings doesn't change what a user can see, so guessing a token is not a big problem)
- Confirm we want changes to the settings to be shared (i.e. loading the settings always gives the latest changes to the settings, even if changes were made after settings were shared)
- Any other feedback :slightly_smiling_face:

**Comment by schuco** [comment]
I can't say that I do understand all the intended programming tools and steps. As far as I understand I agree to your proposals.
I like the ability to use the favorite option as decribed by  @hartenthaler .
My expectation is that the settings used for links resp. favorites will mostly be prepared by administrators or moderators and not so much or even never by normal users. Could the special options be different for admin, moderators, users with admission to modify and users without?

**Comment by hartenthaler** [comment]
Great! 
- I prefer a 10 characters token because there is no need for high security.
- yes, the shared link should always open the latest version of a settings
- I do not see a need for different options for different types/categories of users.

**Comment by Neriderc** [comment]
Great! I won't actually build the updating of settings as part of this, I'll do that in the other issue, #327. But this design will mean you always get the latest version.

@schuco if you feel you want a separation of options based on user type, then we can still consider it. I think perhaps wait and see what this functionality comes out like, then if you still think you need that functionality then create a new issue.

Development is coming along well, though I accidentally broke the functionality to add a starting person (a quite important function) and I didn't notice for days because my automated tests don't cover that (they test loading via adding XREFs to the box in the advanced section and refreshing as this was easier). Now I'm working on adding a test, it's just a bit tricky navigating webtree's fancy search box with an automated test. I don't think it should be too long until I'm done with this sharing functionality though.

**Comment by Neriderc** [comment]
Well that was closer to being finished than I realised. If you install from the main branch you can check out the new functionality. Please let me know if you find any issues or any quirkiness.

**Comment by schuco** [comment]
I have tried the new functionality. It seems to work in most items.

1. I don't get an URL working:
the generated link looks like this: https://brandneu.schulte-coerne.de/index.php?t=DBERWFIL9P
If I use it in the browser I get my page in webtrees and not GVE as expected. The same happens when I include the link in a HTML-block.

2.  The saved settings do appear in the **Saved diagrams** **_list of diagrams_** dropdown and are working as expected when clicked on. It is a bit confusing that the empty line **"-"** remains as the starting line in the list. Couldn't it disappear as soon as one entry to the list has been made?
3. It may be a bit confusing to users not being informed by a git hub discussion like me that there are two lines where input for saved settings can be made:
**_Save settings_** with settings name to be saved
and
**_Settings file_** with _save setting file_ to be downloaded.
Couldn't these be  combined in one input line **_Save settings_** and the **...** option list also include an option to save to a file?

**Comment by Neriderc** [comment]
> I have tried the new functionality. It seems to work in most items.
> 
>     1. I don't get an URL working:
>        the generated link looks like this: https://brandneu.schulte-coerne.de/index.php?t=DBERWFIL9P
>        If I use it in the browser I get my page in webtrees and not GVE as expected. The same happens when I include the link in a HTML-block.

This is not right. When you are in GVExport, what does the URL look like? I'd like to work out if my manipulation of the URL is causing the issue or if it's a problem with what webtrees is telling us is the URL.

The intention was to add the token to the end of the GVExport URL.

>     2. The saved settings do appear in the **Saved diagrams** **_list of diagrams_** dropdown and are working as expected when clicked on. It is a bit confusing that the empty line **"-"** remains as the starting line in the list. Couldn't it disappear as soon as one entry to the list has been made?

The settings do not automatically load the first one in the list. That would prevent the user being able to have settings of their own, as they would be overwritten when you loaded the page. So there is a blank option, so that the settings can be loaded when a different option is chosen. I'm happy to take suggestions on how to do this better but I think having it start on a saved setting would not be helpful. Either you load the first saved setting straight away and the user can never have their own settings (annoying), or you don't load it, but then if that's the one you want to load how do you do that without having to change it to another then back again?

>     3. It may be a bit confusing to users not being informed by a git hub discussion like me that there are two lines where input for saved settings can be made:
>        **_Save settings_** with settings name to be saved
>        and
>        **_Settings file_** with _save setting file_ to be downloaded.
>        Couldn't these be  combined in one input line **_Save settings_** and the **...** option list also include an option to save to a file?

So we would retain the "Load settings from file" where it is, but instead of having the "Download" button download whatever settings are currently set, we would move this to the ... menu? That sounds like a great idea, but I just want to point out this means you can only download the settings if you have saved them to webtrees first. If that's ok then let's make that change.

**Comment by hartenthaler** [comment]
1. I don't get the URL working, too. When I "copy" the link I get "http://ahnentest.hartenthaler.eu/index.php?t=6CR1VZ1835", but this link is not directed to the GVExport module.

3. Yes, it is a bit confusing to have two save/load possibilities side by side. It should be possible to make it a bit better by changing some words, but I like the idea to transfer the "save this settings as file" function to the "..." menu of a settings. It is obvious to a user that you have save a settings first and then you can download it as a file. Then it can be deleted as a settings if it is no longer needed. Yes, retain the "load settings from file" where it is.

**Comment by Neriderc** [comment]
Thanks, it looks like your URLs are structured differently to mine. It looks like this is related to [pretty urls](https://webtrees.net/faq/urls/). Mine are apparently the pretty kind, and yours are the default. Because of how I assembled the URL it's cutting off the bit that directs to GVExport.

I think I know how to fix this to work with both. I'll make that change.

I'll also do that change for downloading settings. I'll start making some new issues to track all this.

**Comment by Neriderc** [comment]
> My naive understanding was that you manipulate saved settings only in the section **File settings** _save setting_ and that _list of diagrams_ is just to display available saved settings and to choose one by clicking

This is correct.

If it helps, we could make the default value say something like "--Please select--" or some other text that indicates to the user they should pick from the list.

I came across a discussion between user experience professionsals discussing what is best. They were largely against having it default to one of the options. Many suggested leaving it blank (no dash, just nothing) because this indicates to users that this hasn't been filled in yet. However, most suggested that while this was an acceptable option, it was preferred to add an instruction the user (like "--Please select--"). I think this may work best in our case. 

The -- on either side is to visually separate it from the other options. Otherwise you might mistake it for one of the saved settings.

Should we change it to say "--Please select--"? Or maybe "--Select diagram--"?

**Comment by schuco** [comment]
Maybe we should better leave it blank or "-" because a not experienced user my understand "Please select--" Or "--Select diagram-" appearing at the top of th whole menu that he has to enter anything here to get GVE starting.
