### ISSUE TITLE
Inconsistent list of persons

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#329]
If you enter in the summary list of persons "i104" instead of "I104", the list of stop persons shows the entry for the person with the XREF = I104, but the summary list shows the (wrong) entry "i104". The entry "i104" does not work.
![Screenshot (164)](https://user-images.githubusercontent.com/6324175/214786260-63d81c1f-15c3-44bd-b6c7-56b40dbcee12.png)
I suggest to accept the user input "i104" if webtrees found an appropriate individual record and to change the "i104" in the summary list t the XREF of the found person "I104".

**Comment by Neriderc** [comment]
We should be able to do this.

> The entry "i104" does not work.

What did you mean by this? It looks like it loads the individual fine, and from my testing the diagram is loaded ok. What doesn't work?

**Comment by hartenthaler** [comment]
> The entry "i104" does not work.

This has no effect if you add "i104" as a stop person. The tree is not cut at the INDI "I104". The list shows the person I104 but it does not function as a stop person.

**Comment by hartenthaler** [comment]
For me, it is more a "bug" than an "enhancement". There are two possibilities: if the user enters garbage (wrong XREF i104),

- the garbage should be ignored/removed or (exclusive or)
- the garbage should be transferred into something valuable (I104)

But in the actual version the garbage is kept (i104) and at the same time transferred into something valuable (I104). This is inconsistent.

**Comment by Neriderc** [comment]
Ah I understand now. Sorry, I marked it as an enhancement only understanding the cosmetic side (that it loaded I104 but still showed i104). Now I understand it's not properly working as a stop person I agree it's a bug.

I'll update the label and add this to my to do list. I have a pretty good idea of how to fix this so shouldn't be too hard I think.

**Comment by Neriderc** [comment]
This should be resolved now.
