### ISSUE TITLE
New option "Space"

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#33]
There are two options "Space". They do not belong to DPI, so they should be separated by a line from DPI.
![Screenshot (164)](https://user-images.githubusercontent.com/6324175/173822506-e9b1659a-db12-4ca0-b118-bf5193064ff3.png)
e

**Comment by Neriderc** [comment]
I agree, this would be a better layout.

**Comment by hartenthaler** [comment]
I'm a physicist. Is there a measuring unit for the "space number"?  "cm" or "dots" or "inches"?

**Comment by Neriderc** [comment]
I haven't looked into it further. The only reason I know what they do is that I saw the explanation in the older translations. It's possible the value is fed into GraphViz so the answer might lie in that documentation, but I haven't looked into it.

**Comment by Neriderc** [comment]
It's inches: 
https://graphviz.org/docs/attrs/ranksep/
https://graphviz.org/docs/attrs/nodesep/

**Comment by hartenthaler** [comment]
Do you know that there was a very early mission to the planet Mars? It was a disaster because a programmer used "inches" in his code where "cm" where expected. Ok, webtrees is not flying to Mars, but maybe we can change this to a number between 0% and 100%. That would make it easier in the user interface. 100% = 10 inches, so 1% would be 0.1 inches. This would avoid the decimal dot/comma, too.

**Comment by Neriderc** [comment]
Haha yes that story is semi-famous. 

Rather than having 100% = 10 inches, which seems pretty arbitrary, how about 100% = default (I doubt we want 10 inches as the defaut, from my testing that's very spaced out). 

Then by default it's set to 100%, and it's pretty clear to users to make it 200% to double spacing, 50% to halve it, etc.

I'd think a default of 1 might be more appropriate, based on my testing.

**Comment by Neriderc** [comment]
I have made the layout change in #40 but have left this open pending more discussion on whether to update to use % and if so what base to use as 100%.

**Comment by Neriderc** [comment]
I've made the change. I left 100% as the current default (0.15), but this is configurable in config.php, and we should add this to the control panel in #51
