### ISSUE TITLE
Option "store link in my favorites" for settings ... menu

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#330]
Beside "Delete" and "Copy link" it would be nice to have a third option: "Store link in my favorites". This should store in the favorites of this user a new entry using the title of the setting as favorite text and the URL of the setting as favorite URL.

**Comment by Neriderc** [comment]
I like this idea, but it does bring the first time I've had to look at doing something like this. The Favorites module is it's own module, in the same sense as GVExport (although it happens to be built in). 

Do you know the appropriate way to do this? The module has a function addUrlFavorite() that can be called to create the favourite. Is it ok to create new FamilyTreeFavoritesModule() and call the function? Are you aware of other modules that do a similar thing where I could check their code?

We would also have to nicely handle the case where the module is disabled or not installed (ideally not show the option).

**Comment by hartenthaler** [comment]
You are right, the "user favourite" module could be disabled. I had once a similar problem and used the following function:

> public static function VestaModulesAvailable(bool $showErrorMessage): bool
>     {
>         $vesta = class_exists("Cissee\WebtreesExt\AbstractModule", true);
>         if (!$vesta && $showErrorMessage) {
>             FlashMessages::addMessage("Missing dependency - Make sure to install all Vesta modules!");
>         }
>         return $vesta;
>     }

But this is maybe only part of the solution. I do not know what happens if the class exists because both favorite modules are part of the webtrees core code and the user favorite module is disabled. I'm sorry but I don't know an example for that. Maybe using the Laravel routing function instead of calling directly a function?

Yes, this option should be only visible if the user favorite module is enabled.

**Comment by Neriderc** [comment]
I think I will ask for advice on the forum.

Are we thinking that there would only be an option to add to the "My page" favourites?

Maybe an admin should have the ability to also add to the tree home page favourites?

**Comment by hartenthaler** [comment]
Good idea, and I think you got fast and good answers from Greg. It seems that he likes your approach to asking and implementing things.

My original idea was only to add to "my favourites", but in the meantime, we had the discussion about using settings even if they are stored originally by another user, so now I would say, there should be a possibility to add to the "tree favourites", too.

- save link to my favourites: available if this user is member or more (ie not visitor) and module "my favourites" is enabled
- save link to tree favourites: available if this user is administrator or manager of this tree and module "tree favourites" is enabled

**Comment by Neriderc** [comment]
Option added!

Favourite is added with a title set from the name of the settings, and the URL from the shared settings URL (adding to favourites also generates the shared settings URL so it can be added to the favourite).

We also have the option to add a note to the favourite but after testing it out I think having no note is best. The user can edit the favourite if they want to..

**Comment by hartenthaler** [comment]
I'm back in Berlin after a long journey from Bali. I will test it tomorrow. It was good that I asked JustCarmen the same thing for her module. So Greg additionally got the message that enhancing the webtrees core code for the favourites is worthwhile.

**Comment by schuco** [comment]
1. It seems there is a bug in adding saved settings to tree favourites, at least in my installation having 4 trees:
![grafik](https://user-images.githubusercontent.com/5896925/218416558-2cdbcde6-8fcc-4a63-b7ab-83c8399ea172.png)
It works for adding to my favourites.

2. It is very helpful that downloads of saved settings get the name of the setting. However as such download are specific to trees you have to keep in mind for which of your trees the download will be working. 
Could therefore the source-tree be added to the download name like _"Miller family - tree2.json"_?

**Comment by Neriderc** [comment]
For 1, I also see this issue and I've fixed this now (hopefully).

For 2, I've made the change to the file name - but have the tree first. This follows the general larger to smaller pattern, which also has the advantage that in an alphabetically sorted list (such as a folder of files) the trees will be grouped together.
