### ISSUE TITLE
Shared settings URLs don't work with default URLs

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#336]
As discussed in #325, shared settings URLs don't work with default URLs, only with pretty URLs.

**Comment by Neriderc** [comment]
@hartenthaler @schuco could you update and test to make sure this change to the shared links now works for you?

**Comment by schuco** [comment]
It works fine! Thank you
https://brandneu.schulte-coerne.de/index.php?route=%2Fmodule%2F_GVExport_%2FChart%2Ftree1&t=9VINYR6NVV

**Comment by schuco** [comment]
I have used it and prepared MyPages for users. I guess this feature will be a big point for the GVE module, as you can attract users, who normally will be reluctant to use webtrees, by immediately presenting  nteresting relationships in their family tree.

To make it even more impressive :
Could the chart open in fullscreen immediately after a link with saved settings has been clicked?

**Comment by Neriderc** [comment]
> Could the chart open in fullscreen immediately after a link with saved settings has been clicked?

I'm afraid not. For security reasons, browsers require fullscreen to be started via user action (e.g. clicking a button).

If you're wondering what security issue there could be, if a browser let you go fullscreen when a page is loaded, you could make a copy of a computers login screen, show this fullscreen when the page loads, and trick a user into thinking it's the real login screen. Then you could steal their login credentials.

Do you think it would be a good idea to do something like show a popup message over the fullscreen button with a message like "Go fullscreen" to draw it to their attention?

**Comment by hartenthaler** [comment]
The shared links are working now in both cases: pretty URL and old URL. I just added one to my favourites.

This is a really big advantage in webtrees! I have several special situations in my tree and produced several diagrams to visualize them. But whenever something changed and there is a need to produce those diagrams again I had to start from scratch and to remember how I have produced them. Now I can store all those diagrams using GVExport. I like it so much!

**Comment by schuco** [comment]
Instead of using the simple menu as described above GVE may generally be opened by a separate menu item. This way it was implemented in the early days of GVE  in PhpGedview where the menu item's name was "_all-in-one-tree_" and it had a nice icon showing a green tree.
Providing such an extra menu item this could not only be used to open GVE like in the charts-menu, but also to open via selected URLs with saved settings. In addition it might also display a list of all accessable URLs with saved settings.

**Comment by schuco** [comment]
I just detected that URLs with saved settings can be easily used in the standard webtrees menu item "Stories". There agin a HTML page can be prepared.

**Comment by hartenthaler** [comment]
The idea to use the Story module is great. It can be prepared in several languages. 

I do not like the idea to use a menu.

First: the space in the menu bar is limited. If every custom module would decide to use its own menu, the user interface would be terrible. I just asked JustCarmen not to use a menu item for her fancy tree view module. GVExport shows a diagram, so it should find its place in the diagram menu. 

Second: the user interface of webtrees should be translatable. If you use the name of a setting as a menu item then this string is not translatable. For example I just named a setting "Verbindung zwischen A und B". For the name of a setting this is acceptable; when using such a German name on the "my site" of a German speaking user this is acceptable; when using that on "my favorites" it is OK. But it would be not good to use it on a top level menu.

**Comment by schuco** [comment]
You are right @hartenthaler , simple menu items make the UI quite long,
So I tried the Story module, **but it seems not to work:**

![grafik](https://user-images.githubusercontent.com/5896925/216688574-37b9cc68-2567-46c1-9c58-9554570dc051.png)
Into the story text I inserted an URL with saved setting (blue text):
![grafik](https://user-images.githubusercontent.com/5896925/216688932-f0c78318-1f44-4e9a-883b-80f46b81d373.png)

**Clicking the link results in an error message and a chart for the previous starting person:**

![grafik](https://user-images.githubusercontent.com/5896925/216689712-e251d052-a685-48d3-a921-154abbfb3728.png)

Maybe the reason is, that a story is always linked to an individual 1:1. You webtrees experts will know it better

**Comment by hartenthaler** [comment]
I have just tried it and it is working like a charm. Your screenshot of the story looks ok. When the error message is "Invalid settings ID" I would assume that there is a copy/paste error. Generate the link from the settings again, go to the story, edit in the "Source code" mode and replace the href link there (http/https should be set correctly).

**Comment by schuco** [comment]
>   @hartenthaler  edit in the "Source code" mode and replace the href link there

It  works!
Thank you for your advice. Before I had used the Link symbol to include the copied link

**Comment by schuco** [comment]
I tried to implement some more URLs using webtrees-stories and noticed an irregular behaviour as follows:
In my implementation I have in principle two trees, tree2 (Hoerdemann)  has been developed from a subset of tree1 (Schulte-Coerne).
Everything worked fine as long as I only worked with tree 1.
Now I prepared an URL for tree 2 (setting name:_Hoerdemann Welkener - gemeinsame Wurzel_) which works as it should when I call it from the GVE-module:
![grafik](https://user-images.githubusercontent.com/5896925/217082618-3541d16e-87d4-4515-898f-f71087f682b2.png)

But when I clicked the URL embedded in a story (everything done within tree2) then GVE tries to use XREFs from tree1 resulting in the message "_invalid starting individua_l".
![grafik](https://user-images.githubusercontent.com/5896925/217082807-15643de2-949e-4937-a727-057b16225346.png)

I noticed that the irregular starting individuals exactly correspond to the starting individuals in a saved setting for tree1 (name: _Kamphaus Witthoff Hamigholt_). This saved setting for tree1 is the 2nd item in the list of saved settings for tree1. Also the non-working URL for tree 2 corresponds to the second setting in the list for tree 2.
Tree1:
![grafik](https://user-images.githubusercontent.com/5896925/217082974-29a8a5a2-deef-4eec-bbba-c42ffc30ac42.png)

Tree2:
![grafik](https://user-images.githubusercontent.com/5896925/217083149-bdcb76a2-a42f-4672-90ec-6089a852bb5f.png)

**Comment by hartenthaler** [comment]
I cannot reproduce that. I just tested:
- produced one link to a setting in tree 1
- produced another link to a setting in tree 2
- put both links in a story of a person in tree 1

Then I can click on those two links and the first one opens setting in tree 1 and the second one the setting in tree 2. All as expected.

@schuco: Can you show us the HTML source code of your story, so that we can check the links?

**Comment by Neriderc** [comment]
Sorry I have been away the last few days and haven't kept up, it will take me a while to catch up on all the conversation! Good to see you are still brimming with new ideas!

Now for the problem at hand, I have managed to reproduce the problem. This is not related to the simple menu extension. It appears that if the settings ID (behind the scenes) is the same as another from another tree, it gives you the same token. This was supposed to be so if you click the button twice for the same settings, you got the same token. I've messed this up and didn't check it was the same tree. IDs are only per tree, so it's possible two settings get the same ID for different trees.

I've made the change and updated the main branch with this, so it should be fixed now. Also in this pull request I have added the latest German translation files. I've noticed two places where the term wasn't added to POEditor ('Revoke link' and 'Show saved diagrams panel') so these are now added to POEditor. Anything else should be translated to German in the latest update (I haven't done other languages). If you see anything else not translated, please let me know!

Also let me know if it doesn't resolve the issue :slightly_smiling_face:
