### ISSUE TITLE
XREFs with lower case letters don't work as starting or stopping individuals

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#338]
As discussed in #333, there is an issue where if an XREF has a lower case letter in it then the individual won't load into the person list.

Proposed solution is to case-insensitive search webtrees, and copy the XREF case from the search results.

This is because webtrees does not allow the same XREF with different case for different records, so we don't need to worry about getting the wrong record.

**Comment by Neriderc** [comment]
@hartenthaler this should be fixed now. Let me know if you still have issues.

**Comment by hartenthaler** [comment]
I have not found any issues! Thank you!
