### ISSUE TITLE
Options DPI and Space are belonging to "Appearance" and not "Output Settings"

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#34]
The two options "DPI" and "Space" have both an influence on the appearance of the diagram in the browser, so they should be part of the section "Appearance" and not "Output Settings".

**Comment by Neriderc** [comment]
After removing the download option (in favour of buttons "Preview" and "Download" instead of "Update" and "Render serverside"), would that eave the file type as the only option in the "Output Settings" section? Is there anything else that should be there?

**Comment by hartenthaler** [comment]
Hmmm.. Yes, the file type will be the only option in "Output Settings". I can't see anything else. But the File type does not fit to the first and second section.

**Comment by Neriderc** [comment]
I think that's fine. It should still look ok as the only option there I think. Plus that makes it a bit clearer that this is different to the other options in that it only affects the generated output, not the browser rendering.

**Comment by Neriderc** [comment]
I've now made these changes, I'll submit the pull request soon. There's also the MCLIMIT option but I've moved that to Appearance as well since it relates to reducing the crossings on the graph - presumably to improve appearance.
