### ISSUE TITLE
A way that only desired starting persons are highlighted

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#343]
### A way that only desired starting persons are highlighted

The option of highlighting starting persons has proved to be very helpful.
Combined with the recently introduced new feature to save settings it is very helpful to prepare stories about family history like "_owners of a farm with change of generations_" or "_my relationship to aunt Mary_".
A complex diagram is much more informative and can be better explained with starting persons highlighted. Also its easier to find a person of interest in a big diagram if it is highlighted.
However in a diagram with many starting persons you will often use some of these starting persons just to get an optimal  form or scale of the diagram, but these are not interesting in the context of the issue to be presented.

**Could there be a way to switch off highlighting (if generally switched on).**
A solution could be:
1.  When you click the option to highlight starting persons, then the background colour of the starting persons in the displayed list is switched on in the chosen color.
2. When you click on the box of a starting person its highlighting is switched off.

Thereotically  an own list of highlighted persons could be provided, but this would explode the menu even more. Also in most cases you will have added the persons of interest in the list of starting persons. 

### Another, somewhat related idea would be, to have a **search function** to jump (center the diagram) for persons within the diagram.

_Originally posted by @schuco in https://github.com/Neriderc/GVExport/issues/240#issuecomment-1420755061_

**Comment by Neriderc** [comment]
I've created this as it's own issue as it's a new request.

The idea is straightforward enough and makes sense, but getting it into the UI may be a little tricky.]



> 2\. When you click on the box of a starting person its highlighting is switched off.

We already have functionality that scrolls the diagram to the person if you click on them in the list. How would these two functions work together?

I know it's not as fancy, but could we just add a box where you list XREFs to ignore? Something like this? 
![image](https://user-images.githubusercontent.com/89974636/217358863-806a86f1-6935-4356-bafa-079683de3ebc.png)

**Comment by schuco** [comment]
That would be o.k.!

**Comment by Neriderc** [comment]
Great!

**Comment by Neriderc** [comment]
This is done :slightly_smiling_face:
