### ISSUE TITLE
Search function to scroll to 

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#344]
Another, somewhat related idea would be, to have a search function to jump (center the diagram) for persons within the diagram.

From https://github.com/Neriderc/GVExport/issues/240#issuecomment-1420755061 by @schuco

**Comment by Neriderc** [comment]
I'd like to do this but it's not exactly straight forward. It works for clicking on the starting individuals because we already know the XREF and can track that down in the code of the diagram.

If we want to arbitrarily search the diagram, it gets a little trickier. I'll need to have a play and see what I can come up with.

**Comment by Neriderc** [comment]
I'm pretty happy with what I've come up with here. @schuco Check out the main branch, let me know what you think (and if you find any issues)

**Comment by schuco** [comment]
@Neriderc I am travelling on Teneriffa just with mobile on hand. I will test when I am back next week.

**Comment by hartenthaler** [comment]
This is a nice function. Very helpful if you are showing a large tree. The "search" icon should be positioned some pixels more to the left. No issues found.

**Comment by Neriderc** [comment]
I've made a few changes. I have hopefully better aligned the button. The issue is that the fullscreen button is a unicode character, while the search icon is generated by webtrees and is an SVG. This makes them difficult to size as they could be shown different on different browsers or devices. The search icon is too big on mobile for me but on desktop this looks the right size. I have now centered these icons so even if the size isn't right the alignment should be.

I also made some changes to the search box. It now should be correctly sized on mobile, and I also have removed the "blank" part. Normally in webtrees this would show the selected person. In GVE we don't show the person here anymore so it is blank all the time, but normally this would be the place to click to select a person. The search box automatically enabled the text field so the blank part is not necessary, and so I have hidden this. 

I also now hide the search field when an individual is chosen from the search results as I expect this is the behaviour most would expect (but if you click the search button again you should still see the previous results).

**Comment by schuco** [comment]
@Neriderc I have now tried the search function: It works fine and is very helpful. Thank you!
You have explained that the symbols for full screen and search function have different origin and are therefore not equally to be manipulated in their display.
Could the search symbol still appear less bold or less massive?

**Comment by Neriderc** [comment]
Sorry, I have been away for the weekend. For me, on my computer I think this looks ok. Here's a screenshot:
![image](https://user-images.githubusercontent.com/89974636/224536051-b858cfb1-c543-4ade-9335-065bc980c70f.png)

However, it does not display the same on my mobile. The search button is much bigger, it does not seem to be affected by the size setting.

@schuco are you looking on a computer or mobile?

I will try some different ways of setting the size to see if i can get it consistent on different devices.

**Comment by schuco** [comment]
May be I have been too critical and the present symbols are o.k.. 
Here the screenshots from all my devices:
desktop:
![Search symbol desktop](https://user-images.githubusercontent.com/5896925/224563531-32468ebe-c379-4e98-97be-ace98a5f5eb8.jpg)

laptop:
![Search symbol laptop](https://user-images.githubusercontent.com/5896925/224563535-686c16c3-a8c1-4158-a2f5-9109768379ed.jpg)

tablet:
![Search symbol tablet](https://user-images.githubusercontent.com/5896925/224563542-05062041-b587-4398-bbb9-2c97a0c90e92.jpg)

mobile:
![Search symbol mobile](https://user-images.githubusercontent.com/5896925/224563550-fb9b7c7e-3f86-46c7-997f-882ecdcc29e4.jpg)

**Comment by Neriderc** [comment]
Nah yours aren't scaling right. Mine is scaled to be the same width, for yours the search button is clearly wider. I will have a play and try to scale it in a different way then have you test it.

I'll reopen this for now so we don't lose track of it.

**Comment by Neriderc** [comment]
Could you give this another go? I've just adding scaling rules that only apply to mobile.

I don't actually understand the underlying issue that is making the icon larger on mobile, which makes it difficult to know if it will help. But it looks better on my phone, so hopefully it looks better for you too!

**Comment by schuco** [comment]
looking good!
![Screenshot_20230315_112525_Firefox](https://user-images.githubusercontent.com/5896925/225281827-a04d532c-b3d4-4bfc-bd81-dde1aecea07a.jpg)

**Comment by Neriderc** [comment]
Great! I'll close this :slightly_smiling_face:
