### ISSUE TITLE
Translation - differences between souce persons and starting persons?

### ISSUE THREAD

**Issue by TheDutchJewel** [Neriderc/GVExport#375]
What are the differences between `source persons/individuals` and `starting persons/individuals`?

**Comment by Neriderc** [comment]
There was quite a bit of discussion on this in https://github.com/Neriderc/GVExport/issues/347. I think where we landed was that this option specifically referred to what happens with the individual passed in from webtrees (e.g. when you come from the page of an individual in webtrees to GVExport, the XREF of that individual is provided to GVExport via the URL).

This term provides a level of separation to show the setting does not apply to all starting individuals, but just to individuals passed in through this functionality. It's quite difficult trying to pick a term that describes what the setting does in a few words!

I'll also tag @hartenthaler and @schuco in case they have further comment.

**Comment by hartenthaler** [comment]
A source person (the individual that was active when you call GVExport - or the default person of a tree or the first person in a tree) will be added to the list of starting persons (or replaces this list). Then that source person is a/the new starting person. 

So there is a small difference between source and starting, but uptonow I used only "Startperson" in the German translation for starting persons as for source persons as well.
