### ISSUE TITLE
Message history

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#377]
When a pop-up toast message is shown, once it is gone it is gone. I propose we have a way to view this history.

I'm thinking there could be two ways to access this history. Firstly, clicking on a message should bring up the message history. This has the potential to in future be used to provide more information.

But secondly, we need a way to view this history without needing there to already be a notification on the page. I have a couple of places this could be added:
- Next to the help button
- In the "File settings section".

Adding it next to the Help button could work. I'm conscious of adding too many things here. Perhaps we could call the button "Alerts" as a nice short word - but this isn't necessarily true for other languages.

An alternate option is to rename "File settings" to "General settings", and add it there (not in the advanced section). This section is starting to become a place to put settings that don't fit elsewhere. Many of the settings here don't actually relate to files anymore.

I think the second option is my preferred option (renaming File settings and putting it there). Let me know your thoughts.

**Comment by hartenthaler** [comment]
For me, the second option is better, too.

**Comment by Neriderc** [comment]
This is completed as above. Renamed section, added button to show history. Clicking notification will also show the history.
