### ISSUE TITLE
Error "Individual does not exist ..."

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#38]
When you remove the starting person, using the small x (the tooltip is "Clear all" ???) in the name box, and then "Update" there is an error message in a red window. Maybe it would be better to do nothing in this case.
![Screenshot (169)](https://user-images.githubusercontent.com/6324175/174063046-6bf3d765-156a-418d-bd5e-7966d1de08c6.png)

**Comment by Neriderc** [comment]
Perhaps there should be wider validation (inline where possible), e.g. if you don't enter a person (and there is nothing in the clippings cart) then a message would appear under the person selection box saying it needs a person.

Ideally this would show straight away, and the form should scroll to the first error if you try to submit.

Other fields could have validation as well.
