### ISSUE TITLE
Rounded rectangle tiles with gender coloured border

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#381]
I've been playing with the design and have had the idea for two more settings. One is for rounded rectangle borders around the individuals' tiles, and one is to replace the coloured stripe with a sex-coloured border.

Combined it would look like this:
![image](https://user-images.githubusercontent.com/89974636/222940716-9921e97e-dd5c-4733-9c94-0e0b940f5f25.png)

Because GVE is very customisable now, I propose adding these as two separate options.

Making the border rounded rectangles causes an overlap as follows:
![image](https://user-images.githubusercontent.com/89974636/222940813-25c65917-ef80-417e-83e1-ca27adbbfb1b.png)

I have not been able to work out a way to have this correctly displayed, so instead I propose adding the option to show coloured borders instead. Perhaps if rounded rectangle tiles is chosen, the coloured stripe is not available and the only options for sex colouring are "none" or "border", with "stripe" only being available if rounded rectangle tiles are disabled.

**Comment by Neriderc** [comment]
Can we remove the "Simple" diagram type if we add an option to set the background based on sex (like how it works for the "Simple" diagram type)? It seems to me this is the only thing stopping you from creating the same look with the "Decorated" style.

Thoughts?

**Comment by hartenthaler** [comment]
You are right! Having only two basic styles: "xxx" and "combined" would be much more straightforward. How to name the "xxx"? I do not like "decorated"; "separated" or "simple"?

And it would be nice to have the option to set the background based on sex (using the same colours we have already for sex?).

**Comment by Neriderc** [comment]
You're right, this should be a new issue, but it also solves some problems with this one. I will make a new issue for this, and for this one will not do dynamic hiding of options that don't work with Simple mode, and we will make sure to do both before the next release.
