### ISSUE TITLE
Disable some options when "rounded rectangle" chosen as tile shape

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#387]
Changes in #384 and #381 do not always work with each other. We should disable some combinations.

For some examples:
1.  the "rounded rectangle" tile shape does not work with the "combined" diagram type. This is because the combined diagram is made up of different boxes put together with a table format, and I have not been able to find a way to only change some of the corners of each box to make them rounded, which would allow an overall rounded corner look.
2. The coloured stripe overflows the tile when rounded rectangles are chosen. So probably we should disable this option as well.
3. Photos that have not been altered (not a circle, oval, etc) also tend to go over the corner of rounded rectangles.

For 2 and 3, possibly we instead could provide the ability to change _how much_ the corners are rounded, and leave it up to the user to set this to contain the contents.

**Comment by schuco** [comment]
1. Regarding an installation with Graphviz installed serverside:
after having chosen rounded photos only after clicking "download" you get a message that downloading serverside does not work with this setting .
It would be more helpful to get a warning already when clicking the option. Such a warning my be e.g. "this setting can not be used to download a diagram serverside" or "diagram with this setting will be generated and downloaded clientside".

2. In the menu the settings for photos and tile design should follow each other as they are somewhat related.

3. It seems to me that  rounded rectangle tile design only works without overlap when you chose non rectangle photos

**Comment by hartenthaler** [comment]
2. please move the "Tile design" up, maybe before "photo"

I would prefer not to disable/enable some options when other options are set/unset. The user interface would become more and more unpredictable. You have to do the selection of options in the right sequence, otherwise, you cannot do what you want. If you like to select the greyed-out "coloured stripe", you have to know that you have first to deselect the rounded rectangle tile options. 

I do not like an option to change how much the corners are rounded, because the user interface is already now very powerful. If there are more and more options a user has to define to get a nice diagram it will become too complex for many users. 

I would prefer to have two more sentences in the help text:
- Individual tile shape: Do not select the rounded tile shape if rectangular photos are selected.
- Coloured stripe: Do not use this together with the rounded tile shape.

**Comment by hartenthaler** [comment]
I'm not sure whether I like or not like "toast messages" as a warning when selecting/deselecting an option as @schuco suggested in 1. 

It could be helpful for users that do not read the help "i" button. If they select the rounded tile shape when "coloured stripe" is selected, they could be warned: "if you use this, deselect that".

**Comment by Neriderc** [comment]
@schuco
> 1. Regarding an installation with Graphviz installed serverside:
>        after having chosen rounded photos only after clicking "download" you get a message that downloading serverside does not work with this setting .
>        It would be more helpful to get a warning already when clicking the option. Such a warning my be e.g. "this setting can not be used to download a diagram serverside" or "diagram with this setting will be generated and downloaded clientside".

Ok, I can change this. I'll remove the warning when downloading and add the message when choosing this option.

>     2. In the menu the settings for photos and tile design should follow each other as they are somewhat related.

I put it next to the other settings that allow you to change the tile colours. Should I move the photo section down above the tile design section?

>     3. It seems to me that  rounded rectangle tile design only works without overlap when you chose non rectangle photos

Yes. This is possibly something I can resolve by adding a margin around the photo when one of these options is selected.

@hartenthaler 
> I would prefer not to disable/enable some options when other options are set/unset. The user interface would become more and more unpredictable. You have to do the selection of options in the right sequence, otherwise, you cannot do what you want. If you like to select the greyed-out "coloured stripe", you have to know that you have first to deselect the rounded rectangle tile options.

Alternatively you could allow the selection of these, but disable the other option when this happens. e.g. if you choose rounded rectangles while the coloured stripe option is chosen, it automatically changes to coloured border. If you choose Coloured stripe while rounded rectangle is chosen, it automatically disables rounded rectangle. Probably it's easiest not to have this, though.

> I do not like an option to change how much the corners are rounded, because the user interface is already now very powerful. If there are more and more options a user has to define to get a nice diagram it will become too complex for many users.

This is why most of these settings are hidden in advanced sections :slightly_smiling_face:. I actually think we should consider a list of saved designs that a user can choose from. We have many ways to change the look, and many different combinations look good. We could set some saved ones. We could even let the user save the style (like a checkbox to save only the Appearance settings when saving settings - and not change any others when loading them).

> I would prefer to have two more sentences in the help text:
> 
>     * Individual tile shape: Do not select the rounded tile shape if rectangular photos are selected.
> 
>     * Coloured stripe: Do not use this together with the rounded tile shape.

Yes I think this is my preferred option.

> I'm not sure whether I like or not like "toast messages" as a warning when selecting/deselecting an option as @schuco suggested in 1.

Having the warning when setting the option means you see it just when you set the photo shape option, and if you don't change it then you don't get warned again. Having it when clicking the download option means you get warned every download, but not when using the browser render. I also am not sure which I prefer.

> It could be helpful for users that do not read the help "i" button. If they select the rounded tile shape when "coloured stripe" is selected, they could be warned: "if you use this, deselect that".

We could do this, but I feel this would be a lot of messages. Probably when someone is playing around with settings in the advanced appearance section, they are closely watching the diagram to see what effect it has. In this case they probably don't need a warning to tell them it doesn't look too nice.

**Comment by schuco** [comment]
> I put it next to the other settings that allow you to change the tile colours. Should I move the photo section down above the tile design section?

I would prefere to move tile design up following photos as it is a more general setting for the appearance of the diagram

**Comment by Neriderc** [comment]
Ok so:
1. Change when warning message is shown when Graphviz installed but option not supported by server (show when option selected)
2. Move the tile design section under the photo section
3. Add a margin around photos when the rectangle/square photo shape option is chosen in combination with the rounded rectangle border, to move them away from the edge, containing them without crossing the border
4. Add to the help text to explain that some combinations may cause an overlap or may not work at all (e.g. rounded rectangle tile with combined diagram type)

Is there anything else (whether previously mentioned or not) that should be done?

**Comment by Neriderc** [comment]
These changes have been made.
