### ISSUE TITLE
Reorder and regroup settings to help make navigation easier

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#396]
I think we should have a rethink of the order and grouping of settings, and consider adding a toggle to show hide. I'm thinking that common style where you have a little triangle, sort of like the demo near the top of [this page](https://www.w3schools.com/howto/howto_js_treeview.asp). But leave our advanced settings as they are, and have sub sections show/hide like this. 

For example, under the advanced appearance settings, there is a "Tile colours" section. In my view this should all be hidden by default, and if you want to edit colours you would expand this section showing all the colours that can be edited. Something like this:
![image](https://user-images.githubusercontent.com/89974636/226160255-e5e962cb-2ee7-4b89-a45c-3725ea567f79.png)

Then once clicked:
![image](https://user-images.githubusercontent.com/89974636/226160335-81b919f2-43ea-43b4-b8db-81ae2d908ef4.png)

I think the general groupings we have (One for individuals to include, one for the appearance, and one for general settings) is good, but within these there is probably some reorganising to be done. For example. "Show birth place", "Show death place", etc. should probably all be in one subsection, instead of having a subsection each.

As always, happy to take suggestions!

**Comment by Neriderc** [comment]
As discussed in #397, we should change the structure of settings such as for setting background colour:
> Currently we have a setting that sets e.g. how to show the sex of the individual. But you could show this in multiple ways (background colour and border), while the background colour can only be set to one thing. Therefore, as you suggest, we should have an option for how to set the background colour which lists "sex" as an option, not an option for sex that sets "background colour" as an option.

**Comment by Neriderc** [comment]
I think this needs to be tackled before the others we've been discussing recently like #397 and #395.

Probably the easiest way to approach this is for me to take a stab at it, shuffling things around. Then I'll push the changes into the main branch, and ask for some feedback.

**Comment by Neriderc** [comment]
I decided to start small. Here's a screen shot of the basic settings in the People to include section:
![image](https://user-images.githubusercontent.com/89974636/227370133-be51a6da-3237-43fc-90b1-4848f9e4c332.png)

Do we want a hide/show toggle on _all_ of the option sections? I'm thinking probably only put them on particularly large sections, and hide those by default.

For some, we may want to only show the toggle when they have grown large. For example, if you have more than 3 starting individuals you could hide these behind a show/hide toggle, only showing them when the user clicks to display them. For others, like the colour options, these could always be hidden until you click to show them.

**Comment by hartenthaler** [comment]
Looks great! I like the new "max level" boxes. Is the lowset level = 0? Is the highest level infinite? Theoretically you can calculate the maximum max level (= max(count of ancestor generations foreach starting individual))

> Do we want a hide/show toggle on all of the option sections? I'm thinking probably only put them on particularly large sections, and hide those by default.

No. I would prefer to always see those most important options (max generations and relation types to include). Yes, the long list of colour options could be normally hidden.

**Comment by Neriderc** [comment]
> Looks great! I like the new "max level" boxes. Is the lowest level = 0? Is the highest level infinite? 

Yes, currently.
> Theoretically you can calculate the maximum max level (= max(count of ancestor generations foreach starting individual))

I think it's best not to do this, otherwise we end up in that scenario of needing to do things in a certain order. I think probably a limit such as 99 may be reasonable, so it keeps to two characters. I don't think any reasonable use of GVE would go over this limit. 
 

> No. I would prefer to always see those most important options (max generations and relation types to include). Yes, the long list of colour options could be normally hidden.

What about the idea of hiding some when they get large, e.g. starting individuals list?

**Comment by hartenthaler** [comment]
> What about the idea of hiding some when they get large, e.g. starting individuals list?

No, I don't like that. The user interface is not clear for me. First you can see them all, then you add one and immeaditly after that the new one disappears in the hidden part of the list? No, if such a list grows, then it grows. And you can see it.

**Comment by Neriderc** [comment]
Thats a good point. It's not a good experience.

I'll leave the starting individual selection as is, and now move on to looking at the advanced part of that section after I've done some tidy up (update help text, update control panel page to match, etc).

**Comment by hartenthaler** [comment]
A lot of work. It will help for the ease of use after this tremendous growth of options and functions.

**Comment by Neriderc** [comment]
For the advanced section for People to include, I don't have too many ideas on how to improve it. I have changed one setting to show hide like it does further down, but otherwise have left it the same. Any ideas on improving it?
![image](https://user-images.githubusercontent.com/89974636/227487785-ceda4f93-468f-4372-ab12-187939b5ea0a.png)
Option disabled, so sub-option now hidden:
![image](https://user-images.githubusercontent.com/89974636/227487872-3d6a2f41-fc9b-4777-bee7-dbeda489d187.png)
Previously it was not very clear that these options were related:
![image](https://user-images.githubusercontent.com/89974636/227488533-0d6949bb-6db5-4feb-bc02-7da5fb586d6c.png)

**Comment by hartenthaler** [comment]
General remark:

- use of ":": sometimes they are there, sometimes not. I would prefer to remove most/all of them. 

- used language: should it be US-ENGLISH? I think so. (color versus colour) But maybe it is already Ok and your Screenshot us based on your personal language version.

**Comment by Neriderc** [comment]
> General remark:
> 
>     * use of ":": sometimes they are there, sometimes not. I would prefer to remove most/all of them.

Thanks, I will aim to remove the : from options and will post here if there are any I think should stay.


>     * used language: should it be US-ENGLISH? I think so. (color versus colour) But maybe it is already Ok and your Screenshot us based on your personal language version.

Yes I use UK English. Hopefully the US ones are all right, I tend to do a search for  the suffix "our" and for the "colour" to try to catch any I've missed. Currently I think they are OK.

**Comment by Neriderc** [comment]
I have removed the : from options.

I have also done some back end changes to make it easier to keep the control panel and settings panel aligned, so let me know if you see anything weird.

The changes are now pushed into the main branch, so you can have a go yourself (I think I've added all translations to POEditor but these aren't translated yet so aren't included in this update).

Let me know if there are any other things you think should change in the first section. I'll move on to looking at the second section.

**Comment by schuco** [comment]
Although graphviz is installed:
![grafik](https://user-images.githubusercontent.com/5896925/228204644-688d6809-f7fc-4022-9575-72b10be599bb.png)
a message is like this:
![grafik](https://user-images.githubusercontent.com/5896925/228205062-2c7cdf4d-9090-43d9-949d-04503cbb67b1.png)

Also I miss the option to use graphviz on the server. This is still in the admin control options but not in the user menu. May be this is intended, as it would be sufficient to have it only for the admin

**Comment by Neriderc** [comment]
This hasn't been changed recently, so I'm not sure what has caused it to appear now. However, I would guess that if you have "Use Graphviz on server" checked in the control panel, it may be overwritten by user settings. If you "Reset" on the GVE page (not control panel), does this resolve it?

As for where the option is, this is only displayed to users as part of the "Debug" panel, which can be enabled or disabled in the control panel settings. The debug panel is really only designed for use in a non-production development environment (i.e. where there aren't other users), as enabling it in the control panel enables it for all users. Perhaps you've previously had this enabled?

**Comment by schuco** [comment]
> I would guess that if you have "Use Graphviz on server" checked in the control panel, it may be overwritten by user settings. If you "Reset" on the GVE page (not control panel), does this resolve it?

It does!

**Comment by Neriderc** [comment]
I'm glad you like it! The border lines are the same for any show/hide parts, or at least they will be when I'm done. It's good to keep consistency, and it's a visual indicator that the section isn't always shown.

I've also moved a couple more colour settings into that section since taking the screen shots. Next I'll make a section for tile contents, and put all the options about including birth date/marriage place/XREFs, etc.

**Comment by schuco** [comment]
I like the new style with unfolding functionlity very much.
Also the regrouping has been very helpful.

There is one issue which may be my personal tick:
Exploring family structures I mostly work with the _"add to list" treatment of source individuals_ or at least switch from _"default"_ to _"add to list"_. That means, this field is quite often used or at least checked in my case.
If not showing the _treatment of source individuals_ option already in the standard settings, then it should be displayed in front of the advanced settings below the _connections to include_ and not at the end of this section.

I could even imagine a  further improved setting, where I admit not to know if and how it could work:
If you want to add individuals to the displayed tree and you are in the "add to list" mode you need two clicks to get the enlarged diagram:
1. at the individuals name in the diagram
2. open GVE-diagram in the individual page

Could there be an _**"add clicked individual to diagram"**_ option so that the enlarged diagram is shown immediately after the click on an individual?

**Comment by Neriderc** [comment]
> I like the new style with unfolding functionlity very much. Also the regrouping has been very helpful.

Great!
 
> There is one issue which may be my personal tick: Exploring family structures I mostly work with the _"add to list" treatment of source individuals_ or at least switch from _"default"_ to _"add to list"_. That means, this field is quite often used or at least checked in my case. If not showing the _treatment of source individuals_ option already in the standard settings, then it should be displayed in front of the advanced settings below the _connections to include_ and not at the end of this section.

I think this should stay in the advanced section, it's not very easy to understand for a new user who probably doesn't even understand why you would need more than one starting individual. But I am curious why you need to change the option so much. It sounds like you prefer this to be set to "Add to list", do you not just set this once and then it stays set to the option you like?

> I could even imagine a further improved setting, where I admit not to know if and how it could work: If you want to add individuals to the displayed tree and you are in the "add to list" mode you need two clicks to get the enlarged diagram:
> 
>     1. at the individuals name in the diagram
> 
>     2. open GVE-diagram in the individual page
> 
> 
> Could there be an _**"add clicked individual to diagram"**_ option so that the enlarged diagram is shown immediately after the click on an individual?

I could imagine having a setting for what happens when you click an individual in the diagram. How this works from a technical angle is unclear, but that's never stopped me before :slightly_smiling_face:. I'll create this in a new issue, and have a think about how we might do this.

**Comment by Neriderc** [comment]
I believe the base changes here are complete, though there are related changes in other issues.

Let me know if you have ideas for improving on the changes, or just open a new issue :slightly_smiling_face:
