### ISSUE TITLE
Show starting person in different color does not work anymore

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#405]
I can select and deselect this option but the color of the starting person box is not highlited anymore.

**Comment by Neriderc** [comment]
Odd, this works for me:
![image](https://user-images.githubusercontent.com/89974636/235273671-1f0f5558-7b83-4c7d-8bf7-01e073177129.png)
![image](https://user-images.githubusercontent.com/89974636/235273685-537fac8a-e8cd-421d-a09f-1f338d95a3ef.png)

Is the starting individual ticked within the "Colour these individuals" option, such as Joseph Joe Bloggs above?

**Comment by hartenthaler** [comment]
Yes, the starting individual is ticked within the "Color these individuals" option.

The problem is the option "Individual background colour".

It is ok if the option is "Custom":
![Screenshot (271)](https://user-images.githubusercontent.com/6324175/235296392-32e1dfda-d52a-47f2-b836-90ce09f33a0c.png)

It is not ok if the option is "Based on individual's sex":
![Screenshot (270)](https://user-images.githubusercontent.com/6324175/235296396-9d548699-a659-4d45-a6a4-6ff3dc04e20f.png)

**Comment by Neriderc** [comment]
Ok thanks, I see it now. I'll work on fixing it.

**Comment by Neriderc** [comment]
This is resolved in the main branch now
