### ISSUE TITLE
graphviz server not recognized after login

### ISSUE THREAD

**Issue by schuco** [Neriderc/GVExport#412]
After login I get the message _"Options limited as Graphviz not installed on server"_ though graphviz **is** installed and selected in the admin settings.
Reset results in the correct recognition.

**Comment by Neriderc** [comment]
I think this has come up before. I'm not sure of the cause, but it seems to happen after some updates.

Currently, the setting on the debug panel is loaded even if the debug panel is not visible - this is why it is wrong but is fixed after a reset. I think it would be good to not load the user setting on the debug panel if the debug panel is not visible. I think this should resolve the issue.

**Comment by Neriderc** [comment]
Don't worry, you don't need to understand it. I will make a change, and then you can tell me if it still happens :).

**Comment by Neriderc** [comment]
Ok I have made this change. The settings in the Debug setting are now ignored if the Debug panel is not showing, even if you have saved settings from when the panel was previously shown (the settings will be saved until the next time it is showing).

Probably there isn't much point in testing this on its own, but hopefully this resolves the issue for you going forward. If you still get this issue in future then we can reopen it.
