### ISSUE TITLE
Refactor help to be more focused on individual options and try to remove long help text

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#423]
As discussed in #422, we should break the help text into smaller pieces and bring it closer to the place it relates too. As the options grow, the help text is getting pretty large.

Unfortunately we are quite tight on space, so adding the current :information_source: button to every option is too cluttered. We need some new ideas on how this could be done.

Some ideas:
1. Leave most alone but for the appearance settings that have subgroups, break the help up to be one for each subgroup.
2. Remove all help buttons, add functionality where you can click a ? button then click on one of the fields and related help will show
3. Leave current help buttons but cut them down to only say what the group is for, then add the functionality from 2 to provide the more detailed help.
4. Add a new help panel on the right that can be opened and closed similar to the panel on the left. When open, display help about the last option you clicked on.

I think my preferred option is 4, but I'm keen to hear opinions from others. I'm also keen to hear more ideas!

**Comment by Neriderc** [comment]
Here's what I'm thinking:
![image](https://github.com/Neriderc/GVExport/assets/89974636/a4d664aa-d11c-4c5d-97de-5148e25cfd4c)

![image](https://github.com/Neriderc/GVExport/assets/89974636/8a94d719-8acc-4f9b-ba66-28c215a38675)

It would be hidden by default, except perhaps the first time the user uses GVExport.

If you click on an item in the settings form, it would update the help text to match the thing you clicked on.

In time, we could add more functionality. Such as search functionality, or an index where you could browse through help topics. But for the first version lets keep it simple.

Any thoughts? Thumbs up/thumbs down?

**Comment by schuco** [comment]
How does it fit on mobile or tablet screens?
Othewise very good!

**Comment by Neriderc** [comment]
> How does it fit on mobile or tablet screens? Othewise very good!

All I've built so far is as above, and that works ok. But there is not enough room to show both panels at once on a phone. You can show and hide the help, and this works, but you cannot see the settings while the help is showing because the two panels overlap (as you might expect).

On a tablet it should display a little better. It seems ok when held horizontally, but this will depend on the tablet.

For mobile, we will need to have a think about how a user might choose the field they want help info on. Perhaps we need the index sooner rather than later. Then instead of tapping on the form, the user can choose the help option from a list instead.

**Comment by Neriderc** [comment]
@TheDutchJewel @hartenthaler This is coming along well, but I don't think we can completely remove long text. For example, in the wiki we have [help for someone using GVExport for the first time](https://github.com/Neriderc/GVExport/wiki/How-to-use-GVExport).

When you're translating, would you prefer something like this to be broken into small pieces (say, each paragraph) so that changes are easier to find when updates are done? Or does the lack of context make it harder to translate, so these may be better as one big translation term to make it easier to understand what it's referring to?

**Comment by hartenthaler** [comment]
I would prefer paragraphs instead of long text.

**Comment by TheDutchJewel** [comment]
As long as there is no one-to-one comparison between the old and new version, I also prefer to divide the text into paragraphs.

For context, it would be useful if an image is added to the comment with the complete text.

**Comment by Neriderc** [comment]
Great, let's move towards paragraphs.

What would be a good way to transition from what we have now to the new format? I worry it will feel like starting from scratch if I break down the large text into a bunch of new terms, which would all need re-translating. The translations are already there, they just aren't split up right.

I could attempt to split them up by taking each part under a heading. So for example I could take this:
![image](https://github.com/Neriderc/GVExport/assets/89974636/98b5bfb0-0822-466d-b49c-2c33386d31fc)

Then split out "Show photos" and the paragraph under it as a term (or should this be two terms? one for title one for text?), and just copy over the translation that is in the same place.

Is this actually helpful, or would you end up needing to review it all anyway?

**Comment by TheDutchJewel** [comment]
> Then split out "Show photos" and the paragraph under it as a term

This seems fine to me.

**Comment by Neriderc** [comment]
I think we will do this over time (it's a lot of work for me, or anyone).

So to start, the new help panel will have mostly the same information. But over time I will break them down into smaller pieces, and try to copy the existing translations where possible. As I need to add or update terms, I will instead break them out into separate terms.

**Comment by hartenthaler** [comment]
Doing it over time would be better than changing all long paragraphs in one step. 

For me, it was always a problem to synchronize the translated heading in the help text and the translated label in the GUI. For example, "Photo resolution" is a label in the GUI, that is maybe translated by "Bildauflösung". When translating the help text I decided sometimes to translate this by "Auflösung des Bildes". Afterwards, I have always to search for those translations in order to keep them synchronised. So I would prefer not to see the label as a heading again.

**Comment by Neriderc** [comment]
OK, great. I will break up the paragraphs and copy translations over. Where I'm not sure, I'll mark as fuzzy and leave a comment on the term under the appropriate language.

I'll keep the titles and paragraphs separate, so they can be reused.

Unless something important comes up, this will be the last feature for this release. There are a few bugs that have been fixed after the last release so it would be good to get a new release published, plus there are lots of new features and changes.

**Comment by Neriderc** [comment]
I have finished the conversion to the new help system (I think). I have kept the help texts as large pages in this new help, but have split the "Tile design" page into multiple terms in POEditor which are assembled back into one page in the help. Over time I will do this to other large pages, then when most are done I'll start splitting the large pages into smaller pages for each setting rather than setting group.

The text is quite broken down, it would be good to know what you think of it @hartenthaler and @TheDutchJewel, if it's easier to translate now or if the terms are too short. I have broken down the lists into individual items because the lists normally start with the name of the setting. By doing this I have reused the setting translation which should make it easier to prevent translating the same term in two different ways.

I have merged the pull request, so now we have our release candidate for 2.1.18. Please download from the main branch and test it out! Raise any issues you find, and if all is working ok I will do one last translation update and release a new version!

**Comment by TheDutchJewel** [comment]
>[...]if it's easier to translate now or if the terms are too short. 

The terms are not too short, but rather manageable. This makes translation much easier.

Thanks for this great improvement!

**Comment by Neriderc** [comment]
Great! I think this will work better for managing the help pages as well, once the big pages are broken down into their pieces.

**Comment by hartenthaler** [comment]
I like the new help system! I have not tested everything. My first comments:

1. There are not translatable items: one in the bread crumb: "Home" and another item in the footer: "Related Links"
2. In the top help text: "You can navigate by clicking the options below, searching using the magnifying glass icon above, or by clicking on a setting to show the information for that setting." I do not understand the meaning of "using the magnifying glass icon above" because there is no magnifying glas. I do not understand "clicking on a setting" - is this the i-button near a setting?
3. In Edge and Chrome there are vertical and horizontal scroll bars visible even if they are not needed. Maybe you can hide them.

**Comment by TheDutchJewel** [comment]
Each help text has a two untranslated terms in the menu: `Home > Detailed information`:
![afbeelding](https://github.com/Neriderc/GVExport/assets/46184729/e0954344-1a6d-4c94-8e38-bbf348946ef0)

And in the Dutch help text under General settings > Output file > `[i]`, the first letter of the first heading 'Type uitvoerbestand' is missing:
![afbeelding](https://github.com/Neriderc/GVExport/assets/46184729/fcec23a8-a5fd-45aa-92f8-bd1633e60c30)

**Comment by Neriderc** [comment]
> I like the new help system! I have not tested everything. My first comments:
> 
>     1. There are not translatable items: one in the bread crumb: "Home" and another item in the footer: "Related Links"

Thanks! I've added these terms to POEditor.
 
>     2. In the top help text: "You can navigate by clicking the options below, searching using the magnifying glass icon above, or by clicking on a setting to show the information for that setting." I do not understand the meaning of "using the magnifying glass icon above" because there is no magnifying glas. I do not understand "clicking on a setting" - is this the i-button near a setting?

Whoops, I wrote that at the start but haven't actually implemented that functionality. The idea was to have some way of having the user click a setting and seeing help for it, but i will edit this text for now as I haven't built functionality like this. I also have not built the search yet so will remove this text as well.

>     3. In Edge and Chrome there are vertical and horizontal scroll bars visible even if they are not needed. Maybe you can hide them.

I'll fix this, it seems to be different behaviour between browsers but I have a fix for it.

> Each help text has a two untranslated terms in the menu: `Home > Detailed information`

I have added "Home". For "Detailed information", it seems to have been added in English. Maybe this was my fault. I have now removed this, so you can add a proper translation.

> And in the Dutch help text under General settings > Output file > `[i]`, the first letter of the first heading 'Type uitvoerbestand' is missing:

I can see this in mine as well, but I do not understand why. The translation seems fine. No other languages seem to have the same problem. I will look into it.

**Comment by Neriderc** [comment]
Thanks for spotting these! The first one has probably been around a long time, but I've updated this and gone through all the translated versions and corrected them.

The other three are more interesting. For some reason, they are not parsed due to the dynamic way I'm loading the content. Luckily I have found a way to correct for this.

I've merged in the pull request so feel free to update from the main branch and make sure it's all looking better 🙂

**Comment by hartenthaler** [comment]
Now it is looking better!
There are only two heading lines in the help text "Home › Detailed information › Appearance" which are not translated:
- Individual border colour
- Individual stripe colour

**Comment by Neriderc** [comment]
Would you believe I checked through the help looking for things not translated before I did the first pull request? I can't believe how many I've missed.

I have hopefully got it all sorted now?

**Comment by hartenthaler** [comment]
You trained to read English. If there is an English phrase inside a German environment, your brain says "It is ok".
I'm trained to read German. If there is an English phrase inside a German environment, my brain says "Oh that is not ok".

**Comment by Neriderc** [comment]
I think you're right.

I had automated testing set up for this, but now it is all broken because I redid the help. And I don't have a good plan for easily redoing it. Before, I just loading the large help under German language and had a check for German characters. Because it was all one term, it either all worked or all didn't. Now it's in pieces if one part is ok then the whole thing would pass. I need to have a think about if there is a realistic way of keeping this test or if I'll just have to rely on you guys telling me when something is wrong. It's not really feasible to list each of the 280 terms (and soon to be many more) individually in the test.
