### ISSUE TITLE
No graphic

### ISSUE THREAD

**Issue by guiyou65** [Neriderc/GVExport#425]
Hello,
I just installed your extension.
But the graphic window stay empty except a rotating arrow.

I'm not convinced that graphviz is installed by my web host. Is it mandatory to have a result ? Is there an alternative if graphwiz is not available ?

**Comment by Neriderc** [comment]
Hi there, no Graphviz is not mandatory.

It sounds like there may be an error on the page. Can you right click (anywhere) on the GVExport page, and click on the "Inspect" option, then choose the "Console" tab, and post a screenshot here? Here is what it looks like for me in Firefox (along the bottom of the window):
![image](https://github.com/Neriderc/GVExport/assets/89974636/5b3383a2-dc91-4e3c-a26b-77f6efc98458)

Here is what it should look like in Chrome (which has it on the right hand side by default):
![image](https://github.com/Neriderc/GVExport/assets/89974636/cdfd013b-0789-46a4-851e-17c55a2ab356)

Could you see if there are any errors there, and if so post them?

And if there is an error, could you click the link on the right to see what part of the code it leads you to? In my first screenshot, you'll see a link "email_detector.js", this is what I'm referring to, but you'll see a red error.

There will most likely be yellow warnings like I have above, but red errors are what I'm interested in.

**Comment by guiyou65** [comment]
Hi Neridec
Here are the screenshots. You also can test directly on 
https://genealogie.guiyou.online/index.php?route=%2Fmodule%2F_GVExport_%2FChart%2Fguiyou&xref=I0004

Hope that helps.
Thierry
![Capture d’écran du 2023-05-24 10-45-12](https://github.com/Neriderc/GVExport/assets/5413493/30cb8c32-af43-4095-b85a-b88be5729cba)
![Capture d’écran du 2023-05-24 10-39-05](https://github.com/Neriderc/GVExport/assets/5413493/f3effbf0-7628-4d78-8ab6-603283a5100a)
![Capture d’écran du 2023-05-24 10-38-31](https://github.com/Neriderc/GVExport/assets/5413493/d0b4733b-4fad-452d-a239-a659c1568526)
![Capture d’écran du 2023-05-24 10-38-12](https://github.com/Neriderc/GVExport/assets/5413493/c1f5f658-2b75-455b-862f-911ebd657554)
![Capture d’écran du 2023-05-24 10-37-50](https://github.com/Neriderc/GVExport/assets/5413493/90e6ee62-aa60-4007-96d1-a2b84a30dc9f)
![Capture d’écran du 2023-05-24 10-37-21](https://github.com/Neriderc/GVExport/assets/5413493/f71daa21-9d32-4bc5-ab7c-8ec925b518cf)

**Comment by Neriderc** [comment]
Thanks for posting those!

When I tried it, it worked fine. Then I realised you were using French. There was an issue with the French translation that I picked up a while back, where it stopped the page from loaded. I fixed it in the translation file, but this did not make it into a release yet. No one had reported the issue until now!

There have been lots of changes to the development version of the code, so while you could use the updated translation file, there would be many things not translated. There are a few options:
- Change the webtrees language to something else
- Download the [new translation file](https://github.com/Neriderc/GVExport/raw/main/resources/lang/fr.mo), and replace it in the resources/lang folder within the GVExport module folder. This would have some but not all translations. The others would show in English.
- Delete the translaton file resources/lang/fr.mo and have GVExport revert to English.

You could also use the development version, but there are known issues with some parts but largely this works ok. Let me know if you'd prefer this, and I can talk you through how to get it (the short answer is to download the code from the main branch).

**Comment by Neriderc** [comment]
In fact, the French translation is not complete. We'd love some help! We are using the website POeditor.com, where I add terms and others can contribute translations for those terms. If you'd like to help, you can join the project here: https://poeditor.com/join/project/YqPRBXZnlf

**Comment by guiyou65** [comment]
Thanks !
I'll be glad to help. Tell me more.
Thierry

Le 24 mai 2023 12:40:23 GMT+02:00, Neriderc ***@***.***> a écrit :

**Comment by Neriderc** [comment]
Great! Go to this link: https://poeditor.com/join/project/YqPRBXZnlf

It should ask you which language you want to contribute to, and to log in. You can log in using your github account, or choose one of the other options.

Once you've logged in and selected the language, you can click on it. As French is partly translated, at the top you can choose to only show untranslated terms. This will show a list of words in English on the left, and a box to type a translation on the right. Simply enter the translation in the box.

There is a "F" icon that stands for "Fuzzy", this means the term has been updated after the translation was done, so the translation should be checked, then click the "F" to remove this setting.

There is also a button to show comments about that term. When I add new terms I try to put some information about the context (though some of the older ones don't have this), and if I change a term I will leave a comment to say what was changed.

GVExport is still being actively developed, with new features and other changes, so the terms will change over time and need to be updated. But it's collaborative, so just do as much as you want and others may also do some.

Normally I will download the language files before I publish a new release. If you're familiar with git and pull requests you're welcome to do it yourself, but if not then it's not a problem I will do it before each new release of GVExport.

Thanks for your offer to help!

**Comment by guiyou65** [comment]
OK, I am in and at work !

Le 24 mai 2023 13:04:03 GMT+02:00, Neriderc ***@***.***> a écrit :

**Comment by Neriderc** [comment]
Thank you for your work! There is one final term that I missed the first time around, now added. It would be great if you could update this.

I plan to release a new version in the coming days, which will include a lot of new features as well as hopefully resolving the issue with the diagram not loading when the French language is selected.

It doesn't end here! After this release, I will start to work on further features listed here as issues. I also expect to make a lot of changes to the help text. It would be great if you could check in occasionally to update the French translation as new terms are added and changes are made. I am not sure if the website will email you or not when there are new terms to be translated, but I think it may do that or it may be an option you can enable.

I mentioned above about "Fuzzy" translations, these are not as easy to spot but should be checked and then marked as not fuzzy. You should also remember to check the comments, when a new term is added or an old term is changed I try to always add a comment to help translators understand what has changed or what the context is for the term.

I appreciate your contribution and I'm sure others do as well, you've done an amazing job getting the French translation up to date so quickly! Thank you!

I'm going to close this issue as the work to resolve it has been completed and so it will be resolved in the next release. However, you can still continue to reply here if you wish and I will see it.

If there is anything in future you want to ask about or comment on, feel free to open a new issue. There are no rules about what it can be about, despite the name "issue". You can also feel free to comment on other issues, we often discuss new features or changes and it's always good to hear more opinions.
