### ISSUE TITLE
"show saved diagrams panel" not saved in control panel 

### ISSUE THREAD

**Issue by schuco** [Neriderc/GVExport#428]
I select "show saved diagrams panel" in the admin control panel and then click "save" to save changed settings.
After clicking "save" the setting for "show saved diagrams panel" changes to be unselected.

I have to select this option in the user menu to get it working as expected, i.e. to get the saved diagrams on top of the menu.

**Comment by Neriderc** [comment]
Thanks for reporting this. This will be resolved when I merge in #429, just trying to track down one final issue first.
