### ISSUE TITLE
Zoom range too small if "left to right"

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#430]
When using the direction top/down everything is fine. When using "left/right" the zoom range is too much limited. When zooming out the boxes are still very large. This happens in any theme and any browser.

Both images are showing the most zoomed out position:

ok:
![Screenshot (302)](https://github.com/Neriderc/GVExport/assets/6324175/dea96242-1daf-4717-9673-5d24cab56b2e)

not ok:
![Screenshot (301)](https://github.com/Neriderc/GVExport/assets/6324175/ec7e9d2e-be42-426d-ba4a-36c887b38523)

**Comment by Neriderc** [comment]
The max/min settings are generated from the width of the rendering. I don't see the same problem but that may be related to my screen. I have changed the minimum zoom to be more than twice as zoomed out, so it should look better now.

**Comment by hartenthaler** [comment]
Yes, it is looking better than before. But still not ok. The screen shots above are made with DPI = 300. Now I have  loaded the newest version of GVExport and set DPI = 72. Maybe the problem is already there when the diagram is loaded. The size of the boxes is different if I select left/right or top/down. The following screenshots are showing the size just after loading the diagram.

top/down: ok
![Screenshot (310)](https://github.com/Neriderc/GVExport/assets/6324175/93ed60c2-ac58-4dd5-9588-77401d3ca076)

left/right: not ok, too large boxes
![Screenshot (305)](https://github.com/Neriderc/GVExport/assets/6324175/eb2a9a9e-8ee4-41aa-8b03-a0c2714bbbc9)

If I zoom out now then the smallest diagram is ok, but it is still larger than the smallest diagram top/down:
![Screenshot (313)](https://github.com/Neriderc/GVExport/assets/6324175/5613210b-2eaf-4562-a859-b0ea551d5d0f)

**Comment by hartenthaler** [comment]
This is a minor important issue. It is not necessary to analyze/solve it before the release of the next version.

**Comment by hartenthaler** [comment]
I think the problem is in fullZoom. How or why does this value change if you switch from top/down (where it is ok) to left/right (where it is not ok)?

My example diagram is very atypical. It is a long chain of partners in the same generation. So it is in top/down only 1 generation high, but very broad. In left/right it is only 1 generation broad, but very high.

**Comment by Neriderc** [comment]
A top down diagram is much wider (and shorter)  than a left to right diagram.

In your ideal world, what would the zoom look like for you? When the diagram loads, do you want the size of one individual tile to be the same regardless of how many individuals are in the diagram? Or would you prefer the whole diagram is visible (regardless of size), and you would zoom in to view it in detail (i.e. scaled so diagram is entirely visible, to just fit inside the render box)?

Or something else?
