### ISSUE TITLE
Setting for quality of jpeg output file not always shown

### ISSUE THREAD

**Issue by schuco** [Neriderc/GVExport#440]
I run an installation with graphviz on the server.
After loading a saved setting where output file had been set to PDF the option to set the quality of JPG photos is visible.
When I change output file type to JPG this quality option disappears.
May be this is intended and correct as the option has only effect on JPG files embedded into a PDF.
But then the following behaviour should be corrected :
after loading a saved setting where output file had been set to JPG the option to set the quality of JPG photos is visible.

**Comment by Neriderc** [comment]
It makes sense to me that the quality option is available for JPG output, even though it's likely to have much less impact on the file size than the formats with embedded images (PDF & SVG).

I will fix this up when I get a chance.
