### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by aelmahdi** [Neriderc/GVExport#451]
Hello
I am new to webtrees  I have a huge tree of 9 generations and 1800 individuals. I can use GVExport for the fifth generation. But more than that I get
Error running GVExport in browser mode:
Error: abort(15). Build with -s ASSERTIONS=1 for more info.

**Comment by Neriderc** [comment]
That's normal. The browser version of Graphviz can't handle large trees.

To do this, you need to [install the Graphviz program](https://github.com/Neriderc/GVExport/wiki/Installation-of-Graphviz) on the webtrees server (if possible). 

If you're not able to install software on the server, you can try generating without links or images, or you could download the DOT file and use Graphviz compatable software on your computer to generate the diagram from the DOT file.

**Comment by Neriderc** [comment]
I'll close this. If you have further questions or need further help you can still reply here and I'll still see it, closing it just helps me see what needs attention.
