### ISSUE TITLE
Error when using empty boxes

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#459]
This happened when I tried to use empty boxes (no name, no birth/death data/no images). 

![Screenshot (457)](https://github.com/Neriderc/GVExport/assets/6324175/f1737c1b-54a1-4f38-ae8d-3a6fd0a7323a)

**Comment by Neriderc** [comment]
It's working for me:
<details>
  <summary>Click for screenshot of diagram with no details</summary>
<img src="https://github.com/Neriderc/GVExport/assets/89974636/fead2b7a-612b-4b8e-b9d6-6df305c4d1b0">
</details>

Is there any more info you can provide? The error is for I567, which is the last in the list of individuals which makes me think there is something special about that individual. Is there anything in that line that looks different from the others?

**Comment by Neriderc** [comment]
Did you manage to work out what is wrong? I'd like to release a new version, but don't want to do that if there's a bug in it. But I haven't been able to reproduce it.

**Comment by schuco** [comment]
There is another issue you might check before the new release:
When the option is set to style individuals based on shared note and then I load a saved setting, which had been saved in a former release of GVExport where the style-option did not yet exist, the saved setting is displayed in shared note style.
This works correctly, i.e. looks as it was saved, when the setting had been saved in the new release of GVExport.

**Comment by Neriderc** [comment]
> There is another issue you might check before the new release: When the option is set to style individuals based on shared note and then I load a saved setting, which had been saved in a former release of GVExport where the style-option did not yet exist, the saved setting is displayed in shared note style. This works correctly, i.e. looks as it was saved, when the setting had been saved in the new release of GVExport.

Ah yes, when loading settings we don't set them to defaults first. If there isn't a setting in the saved settings, it won't be changed. I'll have to have a think about how to solve this.

**Comment by Neriderc** [comment]
@schuco I decided for the sake of loading speed that I'd resolve this issue directly, by checking for that value and add it in as blank if it didn't exist in the saved setting, which should resolve the issue (it does for me).

@hartenthaler it would be great if you could add some more info about your issue as I haven't been able to reproduce it.

**Comment by Neriderc** [comment]
@hartenthaler any further issues with this?

**Comment by hartenthaler** [comment]
Sorry, I was not able to reproduce that issue. I think you should close it. Whenever it appears again I will remember.
