### ISSUE TITLE
Issue with display of preferred name (pre-release bug)

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#465]
Using the merged code I see a problem similarly reported already in December testing d3-graphviz:
![grafik](https://github.com/Neriderc/GVExport/assets/5896925/cfadad5e-5724-4621-a889-bd4b7331d121)
This behaviour is observed when long text is to be displayed in a box and a nickname (underscored text) is followed by normal text. 
Official release works as expected:
![grafik](https://github.com/Neriderc/GVExport/assets/5896925/93ae2d3b-86b8-4189-9fa3-7f32a412d74e)

_Originally posted by @schuco in https://github.com/Neriderc/GVExport/issues/268#issuecomment-1966196278_

**Comment by Neriderc** [comment]
@schuco I have made a change that should fix this for you.

The root cause seems to be when the browser isn't picking up the right font. I've made some changes which should fix it for the default Arial font (which should be ok everywhere, I've tested Windows, Linux, and Android on Firefox. Interestingly, Chrome has a lot less issues, maybe they grab the font from the google server if it doesn't exist).

Unfortunately you may still find some fonts have an issue. We aren't able to tell which fonts are available, so can't hide the ones that will fail and cause an issue, but it does seem to be a lot better for me now.

Let me know if you're still having issues.

**Comment by schuco** [comment]
![grafik](https://github.com/Neriderc/GVExport/assets/5896925/d049177a-72ca-4835-a529-a580d1a97ffb)

I am happy with that! Thank you
