### ISSUE TITLE
Add marriage date prefix

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#469]
It would be nice to have a marriage date prefix like ∞ in the diagram.

_Originally posted by @marwelin in https://github.com/Neriderc/GVExport/issues/232#issuecomment-2006624601_

**Comment by Neriderc** [comment]
This is done now in the main branch. Added the prefix in the same manor as the others, i.e. it's configurable by admins only.

**Comment by marwelin** [comment]
Thank you. This works exactly as imagined.
