### ISSUE TITLE
Add name abbreviation "First given name and surname"

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#470]
The name abbreviation "First given name and surname" would be great for complete but compact diagrams.

_Originally posted by @marwelin in https://github.com/Neriderc/GVExport/issues/232#issuecomment-2006655946_

**Comment by Neriderc** [comment]
@marwelin sorry just realising now that I don't understand how this is different from "Given and Surnames", which is a current abbreviation option. Webtrees doesn't distinguish between first and middle names, so we grab the first word from the "Given names" field.

**Comment by Neriderc** [comment]
Sorry again - I was wrong about the above. "Give and Surnames" includes all given names. We want an option to include just the first given name and the surname.

**Comment by marwelin** [comment]
I think it is not the first given name and the surname. Ideally it is the normally used given name and the surname.

For example:
James <ins>Paul</ins> McCartney - this is the genealogy format, with the underlined usually used given name.
James Paul* McCartney - this is the webtrees format which renders to the genealogy format

The compact name in GVExport should ideally show the normally used given name and the surname.
In this case:
**<ins>Paul</ins> McCartney** 

If there is no given name marked with a star, the first given name can be used.
So, if Paul would not be marked with a star, the name would be
**James McCartney**

**Comment by Neriderc** [comment]
Great, thanks! I'll do it as you describe.

I think perhaps "First given name and surname" isn't an appropriate name. Perhaps something more like "Preferred name and surname"?

Is the term you used, "usually used given name", a normal way of describing this in genealogy? Perhaps that would be a more appropriate label?

Another thing, if there are two starred first names, do we show both?

**Comment by marwelin** [comment]
I don't know a normal way of describing this in genealogy, but what do you think of
- **Primary given name and surname** 

The "primary given name" can then be described as either the starred given name or the first given name.
I think if there are multiple starred given names, they should be shown all.

_Some background information:_
Wikipedia differentiates the [given name](https://en.wikipedia.org/wiki/Given_name) in given name (or first name) and middle name, where webtrees puts all names into the given name (except of the surname). Beside that there is the nickname.

For example: **<ins>Martin</ins> Seamus "Marty" McFly**
- nickname: Marty
- given name (webtrees): <ins>Martin</ins> Seamus
- given name (wikipedia): Martin
- middle name: Seamus
- surname: McFly

In Germany the starred name is the "Rufname", which is something like "call name".

**Comment by hartenthaler** [comment]
I would prefer:
"Preferred name" or a bit more descriptive "Preferred given name and surname". 

There should be only one preferred given name marked by an asterisk. But if there are two or more I would expect to see them all, ie to show "Hans Jürgen Meier" for "Robert Hans* Jürgen* /Meier/" and to not underline any part of the name in this case.

The asterisk is a speciality of webtrees and some other programs, it is not standard GEDCOM. The custom GEDCOM tag NAME:_RUFNAME is supported by many German genealogy programs. It is defined in the "GEDCOM-L addendum" https://genealogy.net/GEDCOM/GEDCOM551%20GEDCOM-L%20Addendum-R2.pdf

**Comment by Neriderc** [comment]
> There should be only one preferred given name marked by an asterisk.

In thinking about this a bit more, names can be two words. For example, here in New Zealand there are some common Māori names that start with a particle "Te". For example:
- Te Aroha
- Te Atarangi
- Te Ariki

So to mark this as a preferred name, you'd need to star both parts in webtrees, and so we would need to make sure this carries through properly.

> I would prefer:
> "Preferred name" or a bit more descriptive "Preferred given name and surname".

"Preferred given name and surname" seems better, as users might expect "Preferred name" to only show the preferred given name. It's a little long, but a similar length to "Given name initials and surname" that we already have.

**Comment by marwelin** [comment]
For me, that looks fine. I like this compact view very much.
Thank you for implementing it.

**Comment by Neriderc** [comment]
Thanks for the suggestions! It's nice to have some easy changes to do :smile:
