### ISSUE TITLE
Bug in plugin interface of webtrees 2.1.18?

### ISSUE THREAD

**Issue by marwelin** [Neriderc/GVExport#473]
webtrees 2.1.18 works smooth together with GVExport 2.1.19.
As of webtrees 2.1.19, the interface to the unchanged GVExport 2.1.9 seems to be broken.

What happens:
Normally the GVExport starting point "Include everyone related to" in the upper left GVExport-corner, is transferred from the currently selected person in webtrees to GVExport, when calling the GVExport-Diagram.
As of webtrees 2.1.19 this does not work anymore. GVExport comes with an ERROR an resets the starting point.

![grafik](https://github.com/Neriderc/GVExport/assets/54200744/affa6b3c-8799-4f0f-9aa3-50d37a71b52d)

Will this be fixed in webtrees or must it be fixed in GVExport?

_This is also posted in the webtrees forum._

**Comment by hartenthaler** [comment]
I have seen this "error" message, too. But I was too busy to document it.

**Comment by marwelin** [comment]
Greg Roach answered in the webtrees forum.
In gvexport.js, function pageLoaded(Url), "data-url" must be replaced by "data-wt-url".

I tested it and it works.
@Neriderc Will you update the main sources, please?

**Comment by Neriderc** [comment]
Huh, my development webtrees is on v2.1.17 and has not informed me of an update!

Apologies, I will re-plan what the next release will be and get it out as soon as possible (now's a good time to check translations are up to date if you contribute to those!)
