### ISSUE TITLE
HI, GVExport permission configuration BUG

### ISSUE THREAD

**Issue by xiaoyang2013** [Neriderc/GVExport#479]
I have set it to "Show to managers" in the background, 
but when the visitor directly constructs the URL: /module/_GVExport-main_/Chart/cheng?xref=X434, the module can be accessed
![捕获](https://github.com/Neriderc/GVExport/assets/139220146/81772b6e-ecd6-4df0-90b1-5c564438a33f)

**Comment by Neriderc** [comment]
Thanks for reporting this. This visibility should be controlled by webtrees, do you find the same issue with other modules?

Which version of webtrees are you running?

**Comment by Neriderc** [comment]
I've had more of a play. This is apparently handled by the module. It has probably always been an issue for this module, so thanks for finding it!

Note that a user can still only see the individuals they have access to, they will show up as private if they don't have access to the individuals in webtrees.

I'll push out a new version that resolves this soon.

**Comment by xiaoyang2013** [comment]
Thank you for fixing this bug so quickly.
