### ISSUE TITLE
Place name abbreviation

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#48]
I like your idea about "place name abbreviation" because the place names can make the boxes very large.

I'm using already ISO-3-Code for place names, like "Mengen, Sigmaringen, Baden-Württemberg, DEU". Using the option "City, Country" works fine. Using "City, ISO-2" or "City, ISO-3" are resulting in no place name at all displayed. I would expect
- City, ISO-2: Mengen, DE
- City, ISO-3: Mengen, DEU.

**Comment by Neriderc** [comment]
I think I know what the issue is, I suddenly realised I've not dealt with the case of no match. Should be easy to fix, I'll get it sorted as soon as I get a chance.

**Comment by hartenthaler** [comment]
Not so important, I can live with that.

**Comment by Neriderc** [comment]
I've created a pull request for it, I might need to hold off merging until we get the other one sorted in case of more conflicts.
