### ISSUE TITLE
Add option to sort saved settings

### ISSUE THREAD

**Issue by schuco** [Neriderc/GVExport#482]
After adding  the 45th saved setting this was no more displayed in the saved setting list. So I can't delete, download, rename etc. this setting.
This setting can be seen in the list of saved diagrams.
Also it would be fine if both lists (saved diagrams and saved settings) were displayed in sorted order (by name).

**Comment by Neriderc** [comment]
I can't reproduce this. Though I did notice something odd. I added these in number order, but numbers 35-44 are placed in the wrong place.

You're sure your new ones aren't just sorted into the wrong place?

![screenshot of list of saved settings numbered from 1 to 50, showing unusual order as mentioned above](https://github.com/Neriderc/GVExport/assets/89974636/fe409efb-0cf8-420d-88ce-d214e0437ef4)

**Comment by schuco** [comment]
Excuse me! I was wrong.
![grafik](https://github.com/Neriderc/GVExport/assets/5896925/eadb0cf0-734b-460d-be11-4fa219ea8d09)

The setting has been hidden somewhere in between older settings.

Still the question, if not sorting of the list could be implemented

**Comment by Neriderc** [comment]
Well that's good! I'm happy it's working, just confusing.

Let's leave this open as the record of this and I'll implement some sort of sorting. I'm away from home this week but will take a look when I'm back :slightly_smiling_face:

**Comment by hartenthaler** [comment]
I would prefer to see the newest ones first.

**Comment by Neriderc** [comment]
> I would prefer to see the newest ones first.

Currently the field to add a record is underneath the list. With oldest first, the new record appears at the bottom just above the box where you add it, so you can see it's been added. Would you prefer it was added to the top, and the rest of the process stays the same?

**Comment by schuco** [comment]
In my case I mainly store settings grouped by family, like Br01Overview, Br02Farmowners, Kh01Overview, Kh02Founders, ...
So in my case alphabetical order would be best.
In case only newest/oldest is possible I would prefere to see the newest entry at the bottom.

**Comment by Neriderc** [comment]
Somehow I knew this conversation would lead to adding a new option for sort order 🙂

I'm home again now so will try to find some time to dive into this.

**Comment by Neriderc** [comment]
On second thought, I should work on the changes to how settings are saved first.

Just to make sure I have this right when I come back to it, here's my understanding of what we want to do:

- Add hidden data to saved settings to record when setting was saved
- Add new dropdown field that lets you choose the sort order: Oldest first (default), Newest first, Alphabetical
- Sort the list of saved settings based on the selected option

**Comment by schuco** [comment]
As far as I understand that is o.k.

**Comment by Neriderc** [comment]
This is now done :slightly_smiling_face:

**Comment by hartenthaler** [comment]
The translations are done. The test was successful. Thank you!
