### ISSUE TITLE
Add option to what happens on clicking an individual to highlight this individual in the diagram

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#488]
We should allow the user to highlight individuals in the diagram by adding them to the options for what happens when we click on them (and also the menu, if the option to show a menu is active).

As suggested by @schuco in https://github.com/Neriderc/GVExport/issues/402#issuecomment-2143398881_

We could possibly extend "Highlight starting individuals" to allow XREFs of other individuals to be added, and then have the option add to this list.

**Comment by Neriderc** [comment]
I've finished this functionality. In the end I added a second option next to the option to highlight starting individuals, where you can add XREFs to highlight additional individuals.

I have then added the option to the menu or clicking action to add to this list.

**Comment by schuco** [comment]
It works fine.
There is only a minor matter of wording:
In the side menu >appearence > colours there is "show **additional** individuals in different colours".
This should read like "show **selected** individuals in different colours" because when you click a starting person which is already highlighted due to the regarding option for starting persons this will be highlighted in the colour set by the new extra option.
Another problem is that this powerful new option to set colours for selected individuals is "hidden" quite deep in the menu structure. Can the help-funtion be provided somehow with the popup-menu?

**Comment by Neriderc** [comment]
>  There is only a minor matter of wording:

I struggled to find good words for it. I'm happy to update it to 'selected'.

> Can the help-function be provided somehow with the popup-menu?

In the place you set the action for clicking on an indvidual, if you click the button to see the help, it tells you about the option to highlight and says where to find the actual setting, pointing you to the help page for that section.

Were you thinking of something like having a help button within the menu? Perhaps there could be an option in the menu "Show help for these options"?

**Comment by schuco** [comment]
> Were you thinking of something like having a help button within the menu? Perhaps there could be an option in the menu "Show help for these options"?

Could you add an "i"-button at the endor below the line "add to list of individuals to highlite" in the popuo menu?

**Comment by schuco** [comment]
Now we have the option to use two different colours to highlight individuals in the chart, which is fine. But one colour is reserved for starting individuals.
Could this become more flexible by adding a box for the highlight colour behind each selected individual in the side menu? Then maybe colouring of starting individuals and selected individuals could be treated in one box instead of in two.

**Comment by Neriderc** [comment]
> Could you add an "i"-button at the endor below the line "add to list of individuals to highlite" in the popuo menu?

Are you thinking we only need help for that specific option, since it's buried in the settings? Something like this?

![screen shot of context menu with help icon added to last option](https://github.com/Neriderc/GVExport/assets/89974636/5e2af74d-eb54-4f72-964b-47b833b6aad4)

Or maybe just an icon for the whole menu, like this?

![screen shot of context menu with help icon at top right](https://github.com/Neriderc/GVExport/assets/89974636/448313dd-9dfd-4f7f-a1a6-d0895f85726c)

Or add a whole option to the menu?

![screen shot of context menu with new help option at bottom](https://github.com/Neriderc/GVExport/assets/89974636/c2cb53e6-a5f3-47ea-85cc-00459d2512db)

> Now we have the option to use two different colours to highlight individuals in the chart, which is fine. But one colour is reserved for starting individuals.
> Could this become more flexible by adding a box for the highlight colour behind each selected individual in the side menu? Then maybe colouring of starting individuals and selected individuals could be treated in one box instead of in two.

Hmm, so you're thinking that we remove the option to highlight starting individuals, create a list of individuals based on the XREFs in the selected individuals option, and then have a colour select next to each individual person?

**Comment by schuco** [comment]
> Or maybe just an icon for the whole menu, like this?

This will do the same as poroposal below

> Or add a whole option to the menu?

I think just the icon for the whole menu is sufficient and is consistent to other help-texts.




> Hmm, so you're thinking that we remove the option to highlight starting individuals, create a list of individuals based on the XREFs in the selected individuals option, and then have a colour select next to each individual person?

Not really. My idea is like this
![grafik](https://github.com/Neriderc/GVExport/assets/5896925/83c567ff-cd2b-4bf7-9e19-29e65c6e36f2)
![grafik](https://github.com/Neriderc/GVExport/assets/5896925/f14d3fe3-7054-429f-a359-5f85cf818c22)
![grafik](https://github.com/Neriderc/GVExport/assets/5896925/a9eb244c-72f6-4111-9832-e8ac97066adc)
where the 
![grafik](https://github.com/Neriderc/GVExport/assets/5896925/c09fc787-a3c2-41a4-b7c0-521f4bc3f40f)
is set behind each of the listed starting- and selected individualsand each can be set toi individual colours

**Comment by hartenthaler** [comment]
Regarding the  "i"-button: I would prefer the second option, placing the button in the top right corner. (What does that look like in RTL languages?)

**Comment by Neriderc** [comment]
> Not really. My idea is like this ![grafik](https://private-user-images.githubusercontent.com/5896925/337661283-83c567ff-cd2b-4bf7-9e19-29e65c6e36f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4Mzc1MzgsIm5iZiI6MTcxNzgzNzIzOCwicGF0aCI6Ii81ODk2OTI1LzMzNzY2MTI4My04M2M1NjdmZi1jZDJiLTRiZjctOWUxOS0yOWU2NWM2ZTM2ZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDhUMDkwMDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjRhNmM5ZWQxYjVlZGZkNWM1NjdkMjYzZTNkNTY2ZjhkODRmNWVmZDMyMzYyYjRjNGVjMGYyZmNiYjllNDY3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DofMLjhx7ZpHYT1_yuJcHAGHXBJ2JvcoChK4dDbTEvY) ![grafik](https://private-user-images.githubusercontent.com/5896925/337661407-f14d3fe3-7054-429f-a359-5f85cf818c22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4Mzc1MzgsIm5iZiI6MTcxNzgzNzIzOCwicGF0aCI6Ii81ODk2OTI1LzMzNzY2MTQwNy1mMTRkM2ZlMy03MDU0LTQyOWYtYTM1OS01Zjg1Y2Y4MThjMjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDhUMDkwMDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjliMjljODRlZGJjZTQwZjZmN2QwMmNmYjhmNjQ0ZjcyM2EzMTEyMTRjNzkwZTZkMGViYmJhNTczMDNhMzY0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GHqCr3p6PbSO6a2MBWvAocy7D8FTdBM0vgEkxlYOV4E) ![grafik](https://private-user-images.githubusercontent.com/5896925/337661648-a9eb244c-72f6-4111-9832-e8ac97066adc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4Mzc1MzgsIm5iZiI6MTcxNzgzNzIzOCwicGF0aCI6Ii81ODk2OTI1LzMzNzY2MTY0OC1hOWViMjQ0Yy03MmY2LTQxMTEtOTgzMi1lOGFjOTcwNjZhZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDhUMDkwMDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQ2MDg0MjMwMWYwNzM1NTk3OGQ1Njc0ZmExZjVjZmIyMmI0NDgwMzI1NGQ0MjU4ZThhNWQ1ZDkyNmQ0YTkxZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-fGMT-9v8gGiaJLxJlCtfNDvnnuEEGzqNMPRo8CpAAc) where the ![grafik](https://private-user-images.githubusercontent.com/5896925/337661855-c09fc787-a3c2-41a4-b7c0-521f4bc3f40f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4Mzc1MzgsIm5iZiI6MTcxNzgzNzIzOCwicGF0aCI6Ii81ODk2OTI1LzMzNzY2MTg1NS1jMDlmYzc4Ny1hM2MyLTQxYTQtYjdjMC01MjFmNGJjM2Y0MGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDhUMDkwMDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGI4OTFiZDhjZmU0ZGEwZjJiZDIzMmFhOTE1YTZhMjA4OGZhNGY4MGE0MWY3MTA4MDVhN2FhZTdiOTU2NmNiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5DmF78TUEEZSr8Atzt6mjtyFuLeRHbpkxGEQde1tiWI) is set behind each of the listed starting- and selected individualsand each can be set toi individual colours

Is the option to highlight starting individuals necessary anymore, if each individual can be individually coloured? I would just the option to add selected individuals should be enough. It will be quite easy to add new ones using the menu option, and we should be able to automatically convert old saved settings into the new setup.

> Regarding the "i"-button: I would prefer the second option, placing the button in the top right corner. (What does that look like in RTL languages?)

I don't think GVExport is translated into any RTL languages, so it's not easy to test. My guess would be the **i** would potentially cover some text at the top right. If we ever get translated into an RTL language, we can probably fix it relatively easily once we can test it.

I'll add the **i** to the top right as suggested.

**Comment by Neriderc** [comment]
I'll take a thumbs up as agreeing, so I've created #497 to do these changes.
