### ISSUE TITLE
Update option to highlight individuals

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#497]
As per discussion in #488, we should make the following changes:
- Add help icon to context menu
- Remove option to highlight starting individuals
- Add colour selection for each individual on the list of selected individuals to show in a different colour
- Add logic when loading settings to move highlighted starting individuals into the selected starting individuals list and set the colour based on the highlighted starting individuals colour, unless the individual is already in the selected individuals list.

**Comment by schuco** [comment]
Sorry that I could test it just today.
It seems not to work at least in my installation.
The menu looks as before - no help button to be seen.
Separate menus for starting individuals and highlited individuals as in previous version.
Only change I realised (very helpful change!): after clicking an individual to be highlighted it is immediately highlighted without leaving fullscreen mode.
I get the follwing console error:
![grafik](https://github.com/Neriderc/GVExport/assets/5896925/5d605f23-2788-4800-81b3-c8ba0c20eb6e)
The menu looks like this:
![grafik](https://github.com/Neriderc/GVExport/assets/5896925/a1601b58-3513-451b-95f3-72d98eaf75bb)

**Comment by Neriderc** [comment]
I haven't done these changes yet, which is why you're not seeing a help button and there are still two options 🙂. I'll work on this when I get a chance, and close this issue when it's done.

Having the diagram stay when updating on click was something added at the same time as the highlight option. It was quite fiddly to get working so I'm happy you appreciate it!

**Comment by schuco** [comment]
> I haven't done these changes yet,

Sorry, I am still learning github procedures

**Comment by Neriderc** [comment]
> Sorry, I am still learning github procedures

Me too! It does give us some flexibility in how we do things, and there are an awful lot of features that I have no idea what they do! The way I'm doing it is that either I or anyone else creates an 'issue' for each proposal, which will then be in an 'open' state (like this one is).

When the functionality is completed, a 'pull request' is created, which is basically a submission of code that can be accepted or rejected (anyone can do this). If I accept it, it will be merged into GVExport's code and become part of the module.

When this happens, I close the issue.  So if an issue is closed, that's a sign that the functionality has been completed.

Of course it's possible that issues are closed without completing the functionality, so it's best to check the comments to see what happened. Normally a pull request will be linked to the issue, and that pull request should have details of what functionality is included. I try to add a comment on the issue too.

At the moment I'm not working on anything for GVExport. I've been busy with other stuff, but also @hartenthaler mentioned he would be working on the issue regarding the clippings cart. It can make things a bit easier if two people aren't both working on things at the same time. If we touch the same parts of the code then we end up with merge conflicts and it's annoying :slightly_smiling_face:

**Comment by schuco** [comment]
The new option to chose action when an individul is clicked is very helpful and I have chosen it to be default in the control panel settings.
However I have a problem with my many saved settings which have been created before the new option was availiable. They all react displaying the clicked individuals page. I can't find a way to change my saved settings to open the control panel instead. 
Do I have to create my saved settings new from scratch? It seems to be a problem here that not all options can be set in the user menu.

**Comment by Neriderc** [comment]
Directly above the saved settings in the Advanced section of the General Settings there is an option of what to do when an individual is clicked on, this should be the same setting but set at a user level instead of in the control panel.

As far as I can tell, this setting is excluded from saved settings so setting it once should allow you to keep the setting. 

![image](https://github.com/user-attachments/assets/2b36b39c-0457-441a-9218-744315e0a07e)

Normally you'd click on a setting, then edit the settings, then save with the same name. It is supposed to overwrite the setting, but it doesn't seem to be working so I'll have to investigate that.

**Comment by schuco** [comment]
Thanks for reminding the option in the user menu.
As in your case overwriting does not work.
