### ISSUE TITLE
If no birth place is specified, baptism place is used

### ISSUE THREAD

**Issue by Sobuno** [Neriderc/GVExport#498]
The method you're invoking `getBirthPlace` apparently just takes the first place of what is called Birth Events (`    public const BIRTH_EVENTS = ['BIRT', 'CHR', 'BAPM'];`)

Invoking `getAllEventPlaces(['BIRT'])` instead and using the first element as the birth place (if any) should ensure that only the birth place is actually used.

**Comment by Neriderc** [comment]
Thanks! I'll get this change into the next version.

**Comment by Sobuno** [comment]
Ok, so if there is a birth event, but no place attached, it would show up empty. And if there is no birth event at all, it will fall back to that list? I can live with that :)

We use your plugin to print out (parts of) the tree to bring to family events and had some questions the other day as to why it looked like some people were born in churches 😜

**Comment by Neriderc** [comment]
Sorry, I wasn't clear. If there's a birth event but no place, I'd propose we fall back to the place in getBirthPlace so as to show _something_ if available.

Interesting you mention it looked like people were born in churches. I'm not a genealogy or webtrees expert (I had barely started using webtrees and was just starting my genealogy journey when I took over development of this extension), so tend to look to others on how this all works. However, I personally have been recording the city, region, country in the "Place", and the name as part of the address (e.g. The Johns Hopkins Hospital, 
1800 Orleans St, Baltimore, Maryland, United States). So I haven't noticed this difference.

I have no idea which is correct though!

**Comment by Sobuno** [comment]
So that's actually the current behavior :) I'd like for people to easily spot we're missing their birth location so they can add it to the printed out version by hand and then I add it to Webtrees - especially the older part of my family is not that technically inclined

**Comment by Neriderc** [comment]
Ah, I see! In *that* case, I'd propose we add this as an option. Something like "If no birthplace, use christening/baptism place". Enable it by default, to keep the current functionality, but allow you to disable it to get the functionality you are looking for.

This option could go next to the option to show birthplace.

**Comment by hartenthaler** [comment]
Normally the places are town, county,... Then it is a good assumption to use the baptism place if there is no birth place. But if you use chirch name, town, county,... as a place for baptism, then it looks strange that someone is born in a church. So I would suggest to either store the church name in the address field and not in the location (PLAC) or to use shared location _LOC for the church together with PLAC with town, county,...
Nevertheless it is a good idea to implement the suggested new option to decide how the place should be decided. The same problem is for the death location. If there is no such location the burial location could be shown instead.

**Comment by Neriderc** [comment]
I'm going to look at implementing this sometime soon.

> Nevertheless it is a good idea to implement the suggested new option to decide how the place should be decided. The same problem is for the death location. If there is no such location the burial location could be shown instead.

It looks like webtrees already does this. We use the webtrees functions, and webtrees uses the following GEDCOM tags for birth/death:
![image](https://github.com/user-attachments/assets/5174c42f-95ee-4f6b-8eb1-4a92a0c427fd)

I will add an option to adjust this. I'm thinking to have one option "Use similar events if information not available" that applies to both birth and death events, then the help can expand on this a bit more.

Marriages don't seem to be affected, it gives us the first marriage date for the MARR event for the family:
![image](https://github.com/user-attachments/assets/d1aaddcc-54f8-41aa-aa98-f5ff760ee21c)

**Comment by Neriderc** [comment]
@Sobuno sorry for the wait, this is now in the main branch, and will be in the next release. If you want to update ahead of the next release, you can install from the main branch. If you need help with this let me know.

I've added a new option "Use similar events if information not available" in Appearance->Tile contents->Information on individuals. Disable it to stop it using christenings and baptisms.
