### ISSUE TITLE
ReferenceError: Form is not defined

### ISSUE THREAD

**Issue by webwurm** [Neriderc/GVExport#499]
When showing a diagram I clicked on an individual and changed the first name.
Going back to GVExport there is no graphics and I get this error in the console, no matter what I do:

```
VM1405:148  Uncaught (in promise) ReferenceError: Form is not defined
    at addIndiToList (eval at <anonymous> (index.php:1:1), <anonymous>:148:5)
    at loadURLXref (eval at <anonymous> (index.php:1:1), <anonymous>:36:17)
    at pageLoaded (eval at <anonymous> (index.php:1:1), <anonymous>:461:5)
    at runPageLoaded (index.php?route=%2Fmodule%2F_GVExport-main_%2FChart%2Fwurm&xref=I500001:1443:13)
    at index.php?route=%2Fmodule%2F_GVExport-main_%2FChart%2Fwurm&xref=I500001:1452:9
addIndiToList @ VM1405:148
loadURLXref @ VM1405:36
pageLoaded @ VM1405:461
runPageLoaded @ index.php?route=%2Fmodule%2F_GVExport-main_%2FChart%2Fwurm&xref=I500001:1443
(anonym) @ index.php?route=%2Fmodule%2F_GVExport-main_%2FChart%2Fwurm&xref=I500001:1452
Promise.then
(anonym) @ index.php?route=%2Fmodule%2F_GVExport-main_%2FChart%2Fwurm&xref=I500001:1450

VM1405:287  Uncaught (in promise) ReferenceError: Form is not defined
    at updateClearAllElements (eval at <anonymous> (index.php:1:1), <anonymous>:287:9)
    at updateClearAll (eval at <anonymous> (index.php:1:1), <anonymous>:275:5)
    at eval (eval at <anonymous> (index.php:1:1), <anonymous>:134:9)
```

Reload with F5/Alt-F5 doesn't work.

I am running the latest version of GVExport on Webtrees 2.1.20 in Microsoft Edge.
You can check it out on https://webtrees.wurmweb.at

Any idea how to fix it?
Thanks!

**Comment by Neriderc** [comment]
Hmm, for some reason the Javascript isn't loading. Thanks for providing a link to your website, that's very helpful!

When I inspect your website, I look at the place where I expect to see the webtrees generated link to the javascript, and I see this:
![image](https://github.com/user-attachments/assets/6095813d-76db-4103-851c-db5a0bcdcafb)

Do you notice the parts like `<script>eval(mod_pagespeed_$tVI5Dqsc3);</script>`?

You seem to be using something that changes how the javascript is loaded. A bit of a search around and it seems it's some sort of Google PageSpeed tool intended to speed up the loading of websites by delaying the loading of javascript.

I'm not sure why your problem occurred suddenly, but are you able to disable this and see if it works again? Even if it's not the problem, it will help with troubleshooting as at the moment it's hard to see why the Javascript code is not accessible to the page.

**Comment by webwurm** [comment]
Thanks, I figured out that it is an option on my (Hetzner-) Shared-webspace. And when I deactivate it, it works!

**Comment by Neriderc** [comment]
Perfect, glad to hear you got it working again!
