### ISSUE TITLE
Hello, is it possible to limit the maximum value of Max levels?

### ISSUE THREAD

**Issue by xiaoyang2013** [Neriderc/GVExport#500]
Hello, can you add a function to limit the maximum value of "Include ancestors" and "Include descendants" Max levels in the background?
For example, in the background, limit "Visitor" to 5 levels, "Member" to 10 levels, "Editor" to 15 levels, "Moderator" to 20 levels, and "Manager" to 25 levels,
because GVExport will take up a lot of resources when generating multi-level graphics.

![捕获](https://github.com/user-attachments/assets/32e5bad9-e8d1-4646-8c1d-8c6157fca7a8)

**Comment by Neriderc** [comment]
This isn't currently possible, but shouldn't be too hard to implement. Currently I'm trying to avoid making changes while another contributor is working on a change, but I will plan to add this into the next version when it's released.

**Comment by xiaoyang2013** [comment]
Thank you very much for your adoption

**Comment by Neriderc** [comment]
Hi @xiaoyang2013, I have completed this functionality and it is currently in the main branch. If you'd like to test it out, check out the instructions I posted here: #512 

I'm happy to give more detailed instructions if needed. Once this version has had a good test and people helping with translations have had a chance to add them to POeditor, I'll publish a new version.
