### ISSUE TITLE
Overwriting settings no longer works

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#502]
It seems refactoring in the last release has broken the ability to overwrite a setting in the advanced saved settings list.

When saving a setting, if you save with the same name as an existing setting it should overwrite that setting (after prompting the user to confirm that's what they want to do).

It seems the prompt appears, but no actual saving occurs.

**Comment by schuco** [comment]
Sorry, but in my case the fix did not help.
There is the prompt to confirm overwriting, but no confirmation or indication, that it was done.
I have made a reset after overwriting, reloaded the saved setting, but the intended change has not been saved.

**Comment by Neriderc** [comment]
Sorry, this was the issue I created to track the issue. Once I've actually fixed it, I close the issue.

I've merged in the fix now, so if you update from the main branch you should find it's fixed.

Just a warning, I was wrong about the "Action when individual clicked" not being included in saved settings. It *is* included, however, I believe it is ignored if you are loading old settings that were created before the new setting was added. That should work in your favour, as the setting should stay the same as you load the older settings.

Regardless, you should be able to update the settings now if you need to. Click a setting to load it, change what you want to change, then save it again. So long as you keep the same name, it should overwrite it.

**Comment by schuco** [comment]
It works as promised. Thank you very much!

**Comment by Neriderc** [comment]
Great to hear!
