### ISSUE TITLE
adapt / bugfix for Primer theme

### ISSUE THREAD

**Issue by arbor95** [Neriderc/GVExport#505]
GVExport and the new Primer Theme do not work together in some places. See comment of the Primer Theme author at 
https://www.webtrees.net/index.php/forum/4-customising/39304-primer-theme#107404
If wanted, I can create some screenshots.

**Comment by Neriderc** [comment]
Thanks for reporting this, I'll install the theme and take a look.

**Comment by Neriderc** [comment]
I have just merged a pull request into the `main` branch. Feel free to download and use it, it should be stable. Let me know if you need more instructions on how to download it without a published release.

I haven't just looked at Primer, I've tried to move the hardcoded values in the CSS over to the available CSS variables. Things don't have a 1:1 mapping, but I've tried to tweak things while letting it work in as many themes as possible. It's possible there are some bits and pieces that I didn't notice are loading odd colours, so anyone can feel free to reply here or open a new issue. I'm happy to make changes to support any theme.

P.S. that Primer theme looks really nice!
