### ISSUE TITLE
Move some options to the control panel

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#51]
At the moment GVExport is not using a configuration menu in the control panel. Some of the options in the user menu are relevant to the user, others can be transferred to the control panel.

- There are several options hidden in the code, that maybe can be made as options to the control panel so that they can be changed by the admin.
- All the colors could be made configurable in the control panel.
- Perhaps DPI and the separation are other values? Normally you'd set these once and not change them again, and with sensible defaults, you may never need to change them.
- Another one is MCLIMIT (number of iterations).

**Comment by hartenthaler** [comment]
As a result after implementing this issue, the file config.php of GVExport should be unnecessary.

**Comment by Neriderc** [comment]
> As a result after implementing this issue, the file config.php of GVExport should be unnecessary.

I'm not so sure about that. config.php sets all the default values. We still need default values, even if they can be changed in the control panel, so I would think config.php would still be necessary. My plan would be to leave config.php as is, and load saved values into the control panel the same way we do it for the front end. Really the control panel is no different to the UI for changing settings now.

**Comment by hartenthaler** [comment]
This is related now to #154 .
If there are advanced options available for the user in a nice way the need for options accessible by the admin using the control panel is less important.

My idea: add a control panel menu for the admin to set the defaults for all options (per tree) and allow the users to modify the options if they like (using the expanded menu like it is suggested in #154) (per browser session). But if the users can control all colours, fonts, etc. it is not so important if an admin can predefine the options for a tree.

If there are more and more options that can be configured by users, the permanent storage of a set of options (like suggested in #92 ) becomes more important.
