### ISSUE TITLE
Preparing for new release

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#512]
I've now completed all the items that were marked for the next release. I have found (and fixed) quite a few bugs caused by the changes, so I'd love some help testing before I publish a new release!

For anyone that wants to help, you can download from the "Code" page of github, making sure the branch on the left says "main", then click the green "Code" button and choose to download the zip. You'll need to extract it and install as normal, making sure the module folder name does not have a "." in it, as webtrees ignores modules with a "." in the folder name.

Any issues found can be posted here.

This also gives some time for translations to be completed, I'll update the translations with whatever has been translated before publishing the next release.

**Comment by HerzScheisse** [comment]
Thanks @Neriderc  i'm downloading right now and will test over the weekend...

**Comment by HerzScheisse** [comment]
so far 2 missing translations in the settings menu

![gvexport_2](https://github.com/user-attachments/assets/cdc46b6f-e17c-40ad-a82e-a010317ea020)
![gvexport_1](https://github.com/user-attachments/assets/901f77e0-8591-4958-ba8a-df0f5c428ffa)

**Comment by Neriderc** [comment]
Oh wow, thanks! One of those is a new option, not all translations have been completed. But "Preferred given name and surname" has been in GVExport for many months and I didn't realise it had no translation (I hadn't added it to POEditor, so translators wouldn't have been able to add a translation for it). Thanks for picking up on that!

I've adding the missing term to POEditor and will update the translations once they have been translated by our helpers into the main languages.

**Comment by schuco** [comment]
I use the saved settings quite often. 
I realised just now the following (slight) problem:
_If there had been set individuals to stop processing and/or a list of selected individuals to be shown in different colour and I thereafter load another saved setting, then the stop individuals and the list of differently to be shown individuals remain. They are shown in addition of regarding individuals from the just loaded list._
This may be due to the fact, that most of my saved settings have been built and saved with older versions of GVE.

**Comment by schuco** [comment]
I just tested the above mentioned problem with an actually saved setting.  Then the problem does NOT appear, so it is just a matter of settings, saved with prevoius versions of GVE.

**Comment by Neriderc** [comment]
> I just tested the above mentioned problem with an actually saved setting. Then the problem does NOT appear, so it is just a matter of settings, saved with prevoius versions of GVE.

Yes, it's a bit unclear what should happen as a general rule for loading settings where not all settings are included due to being from a version of GVE before the setting existed. At the moment the saved setting will update any settings found in the saved settings, so any not found will not be touched, as you have found.

For your older settings, you can update them by clicking to load them, choosing to save again, then agreeing to overwrite them. Of course you'll need to ensure the new settings are actually set right before saving them, which is the time consuming part.

Settings could be loaded from defaults when not specifically listed, but I can imagine other scenarios where this would not be ideal.

I'm happy to take suggestions on how to make this a bit smoother.

**Comment by schuco** [comment]
@Neriderc For your older settings, you can update them by clicking to load them, choosing to save again, then agreeing to overwrite them.

I have done so and observed some points:
1. Loading older saved settings modified settings with no influence on the loaded diagram, like _setting list order_, _message history_ or _show saved diagrams panel_. These would have better not been overwritten by the loaded saved setting.
2. When I pressed the _save_-button to overwrite a setting while the diagram was still loading ths sometimes resulted in having two settings with the same name.

I admit there are different scenarios the saved settings are intended to be used for. In my case it is mainly to get almost the same diagram for a certain familiar constellation which is just updated with new genealogic information. Others may use saved settings to switch between different workflows. Then it would make no sense, to generally reset the _browser render settings_ to administrator default as I would prefere.

**Comment by Neriderc** [comment]
> Loading older saved settings modified settings with no influence on the loaded diagram, like setting list order, message history or show saved diagrams panel. These would have better not been overwritten by the loaded saved setting.

Message history is not saved, it's not even saved from one page load to the next because it's not stored in the database at all.

I'm wondering if an additional option is in order, "include settings that do not affect the diagram". If this is selected, we include all settings as it is now. If it's not selected, then we exclude settings that don't relate to the diagram itself.

Though this raises the question of whether this setting itself should be stored in saved settings.

> When I pressed the save-button to overwrite a setting while the diagram was still loading ths sometimes resulted in having two settings with the same name.

I wasn't able to reproduce this. I have tried loading a large diagram that takes a while and clicking to save while it's still loading, and I still get asked if I want to overwrite it, and if I choose yes while the diagram is still loading I don't get any duplicates. Is there some specific sequence you have found to get a duplicate each time?

**Comment by schuco** [comment]
> I'm wondering if an additional option is in order, "include settings that do not affect the diagram". If this is selected, we include all settings as it is now. If it's not selected, then we exclude settings that don't relate to the diagram itself.
Though this raises the question of whether this setting itself should be stored in saved settings.


If I understand your comment correctly you are discussing an extra option "include settings that do not affect the diagram"  and conclude it would raise further questions.
But could my concern be solved by just not saving settings like "setting list sort order"?

**Comment by schuco** [comment]
> 

  @schuco   When I pressed the save-button to overwrite a setting while the diagram was still loading ths sometimes resulted in having two settings with the same name.

@Neriderc  wasn't able to reproduce this.

I wasn't able today too. However when I got the problem of getting double settings /settings with the same name yesterday the settings were loading very slowly. Might have been a temporary problem of my server. Today loading is so quick that I even don't manage to click "save" while the setting ist still loading.
I would come back with this problem when I should observe it again.

**Comment by Neriderc** [comment]
> If I understand your comment correctly you are discussing an extra option "include settings that do not affect the diagram" and conclude it would raise further questions. But could my concern be solved by just not saving settings like "setting list sort order"?

My concern with this is that some people might be using the option to save these sorts of settings. I am wondering if the best option is to start a new issue to discuss it, and leave any changes for a future release when others have had the opportunity to input.

**Comment by Neriderc** [comment]
I am closing this as the new release is out. I have created #519 to discuss the one outstanding thing.
