### ISSUE TITLE
Added marriages and photos to GVExport

### ISSUE THREAD

**Issue by elysch** [Neriderc/GVExport#514]
Hello.

I made some changes to the GVExport module in order to show marriages and the first photo of a Birth, Marriage, Death and Burial.

I've been feeling for a long time I was needing a way to share more information to people to help me gather missing data. I first changed the family book graph. It looks nice but I encountered nobody understand it the first time, so I took that experience to make changes to the GVExport one.

I added checkboxes for every new data I added so people can get the original format.

The only thing I haven't been able to fix is the "Add URL to individuals and families" setting. It was working at some point. If you clicked on the principal photo or the name of the individual It did the same as before, but when you clicked on any one of the photos I added to the report, it took you to that specific media object.

I thought I should share the changes in case other people see them useful.

I merged my changes to the main branch on 2024-10-21

[GVExport.disabled-BAK-202410311222.patch](https://github.com/user-attachments/files/17593226/GVExport.disabled-BAK-202410311222.patch)

**Comment by elysch** [comment]
I missed to say something else. I changed the symbols for birth, death and burial to something not related to religion. Let's see what you all think:
↑  = Birth
↓  = Death
_  = Burial

**Comment by Neriderc** [comment]
Hey thanks for this! I managed to apply the patch to a branch taken at that date, but haven't managed to get it to run without errors. I can keep working on it to see if I can get it running. Would you be willing to do a pull request?

> I missed to say something else. I changed the symbols for birth, death and burial to something not related to religion. Let's see what you all think: ↑ = Birth ↓ = Death _ = Burial

These are configurable by an admin in the control panel, so people can use what they like 🙂. Those icons do make nice non-religious symbols, but I'm under the impression (rightly or wrongly) that the current symbols are more standard.

**Comment by elysch** [comment]
I didn't do a pull request because I don't have now a machine with git
running...

Do you know if everything can be done in the git web page?

Sure I can try

**Comment by elysch** [comment]
Forgot to ask... which branch did you merge the changes?  I could also help resolving errors.

**Comment by Neriderc** [comment]
I haven't pushed my testing branches to GitHub but I'm thinking I will get the current release out, then have a more determined effort to merge in these changes. I did manage to get the patch applied and working on a branch as at the Oct 21, after clearing cache and resetting settings. There are quite a few changes (both in the patch and that are in the main branch after the 21st) so it will take a while to work through them but I will work on it.

In theory you could do most things on github but it sounds like a nightmare, so don't worry about it, I'll work on it after I've got this release out.

**Comment by elysch** [comment]
Hello again.

Today I tried to download a config and load it from file and it didn't work.
I got the following error:

> Unable to load setting burial_date_year_only

I guess I didn't test my changes enough. I'm sorry for that.

**Comment by Neriderc** [comment]
Hey don't worry about it, it's not a problem. There are lots of moving parts, and with the code being an amalgamation of at least 5 lead maintainers over the years it's not always clear how things fit together.

I'm still happy to work on merging your changes into the main code base and I'll test that things work as I go.

**Comment by Neriderc** [comment]
I still have a list of things to be investigated, but I agree it's coming along nicely! Thanks for the contribution!

**Comment by Neriderc** [comment]
I'm done! Have merged it into main. The new functionality is not translated yet, I'll update those at some point before the next release once translators have had a chance to do the translations.

I'd be very happy if anyone wanted to test this out and see if they can find any issues. There's a lot in here, so I probably haven't got all the bugs.

**Comment by elysch** [comment]
Haven't tested it completely yet, but can say the links in the PDF file are still missing.

I'll keep testing it a bit longer.

**Comment by Neriderc** [comment]
Remember that links in PDFs only work if you have Graphviz installed on the server. This has always been the case. Without Graphviz on the server, PDF generation is just an image embedded in the PDF.

With Graphviz on the server, PDF links are working for me.

**Comment by elysch** [comment]
Hello. 
Today I tried to load some settings and got this message. 
Looked for a way to fix it, but didn't find the right place:

"Unable to load setting show_marriage_type_not_supecified"

Ely
