### ISSUE TITLE
settings of place names

### ISSUE THREAD

**Issue by HerzScheisse** [Neriderc/GVExport#515]
Hi, 

while playing with the latest version a bit i noticed some issues with place names...

![2024-11-03 23_01_45-Window](https://github.com/user-attachments/assets/16f6ef5d-531d-4d1b-8b4f-4e041f9ca8e0)
Full place name works as expected...

![2024-11-03 23_03_09-Window](https://github.com/user-attachments/assets/59cb2155-b665-4b59-b138-33d5fd73bf92)
but if i use the place name and 2 digit ISO code... it displays the full country name...
Am I missing something?

and btw... do you think its possible to add another option to just display the first place name f.e. "Pillau" without any country code... this will shorten the boces quite a bit...

**Comment by Neriderc** [comment]
> but if i use the place name and 2 digit ISO code... it displays the full country name...
Am I missing something?

Simply that the starting list of countries was a list of ISO countries from [here](https://datahub.io/core/country-codes), and we knew it did not contain all countries (especially not historical ones). It is also entirely in English. You can see the current list that GVExport uses [here](https://github.com/Neriderc/GVExport/blob/main/resources/data/country-codes_json.json).

One issue is that historical countries may not have a 2 or 3 letter ISO code! If a country can be related to a code (e.g. if it's just a non-English name), then feel free to give me a list of names and mappings and I can update it.

> and btw... do you think its possible to add another option to just display the first place name f.e. "Pillau" without any country code... this will shorten the boces quite a bit...

Yes this should be possible, I can add this.

**Comment by HerzScheisse** [comment]
> Simply that the starting list of countries was a list of ISO countries from [here](https://datahub.io/core/country-codes), and we knew it did not contain all countries (especially not historical ones). It is also entirely in English. You can see the current list that GVExport uses [here](https://github.com/Neriderc/GVExport/blob/main/resources/data/country-codes_json.json).

ah great... thank you for explanation and the links...
hmmm so translation is the problem... If we use translated countries in that file it can be a bit challenging... so for now i can live with how it is... Thanks

**Comment by Neriderc** [comment]
>  If we use translated countries in that file it can be a bit challenging... so for now i can live with how it is... Thanks

Translated names are fine. We can add a new entry next to the English entry with the translated name mapped to the same country code, if that is what you are looking for.

What is challenging is that, as far as I can tell, Ostpreußen was not a country but a province of Preußen (Prussia). Neither Ostpreußen nor Preußen appear to be covered by the ISO standard.

I think a different abbreviation list would be nice, one that we control and don't try to align to the ISO standard, but that requires people to contribute appropriate abbreviations, and also some decision over what should be included (e.g. whether we should abbreviate provinces or if it should only be countries). 

All my key ancestral lines come from countries that still exist (in some form) today, so I don't have a lot to go on. As I mentioned, I'm happy to take suggestions for abbreviations and start to form our own list.

**Comment by HerzScheisse** [comment]
> What is challenging is that, as far as I can tell, Ostpreußen was not a country but a province of Preußen (Prussia). Neither Ostpreußen nor Preußen appear to be covered by the ISO standard.
Yeah i understand this... the example with Preußen was just selected, because i noticed the missing ISO abbreviation on a living individual and dont wanted to share this data...

> I think a different abbreviation list would be nice,
yeah this would be the best way... and I thought about this the last days... maybe it would be better to combine this with the webtrees user language... and i think this not just belongs to this module, but better to webtrees core itself...

while searching for a solution... i stumpled upon this page https://stefangabos.github.io/world_countries/ and here is the repo for it https://github.com/stefangabos/world_countries/
Maybe we can use this?

What do you think?

**Comment by Neriderc** [comment]
Oh that's a nice find! It's only current countries (not historical ones), but it has translations into a lot of languages. I should be able to incorporate this into the existing abbreviation function.

> maybe it would be better to combine this with the webtrees user language

I think it would be ok to not rely on the set language. If we see a country that we know how to abbreviate, we should do this regardless of whether the particular user has set their language to the same language that the tree was written in.

I can look to do this for a future release, including adding the option to show only the first component of the place.

**Comment by HerzScheisse** [comment]
okay great... yeah no hurry... its not that important right now...

and if you can add the single place name.. that would be my first choice to use...

**Comment by Neriderc** [comment]
I have added a new option "City only" into the place name abbreviation options. This is now in the main branch if you want to test it.

I'll continue to work on adding the county list.
