### ISSUE TITLE
Show a message with the number of individuals and families when you generate a download file

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#526]
> Another idea. To show a message with the number of individuals and families when you generate a download file and add it to the list of messages. Just like when you click on the "View" button. That way there is no need to view before download to know this information.

_Originally posted by @elysch in https://github.com/Neriderc/GVExport/issues/487#issuecomment-2477622109_

**Comment by Neriderc** [comment]
This was not as easy as I thought it would be! The issues are:
- When you are downloading from the server, the server response needs to be the streamed file that is being downloaded. No chance for messages.
- When the file is generated for download from the browser (I think only SVG fits this case), then we do not query the server again so don't get the info on individuals and families.

To implement this easily, I have made the browser remember the last set of messages from the server (in practice I think it's only ever one, but in theory it supports more). When you click the download button, it will now replay this.

The problem is if you do not have auto-update enabled. If you do not click Update immediately before downloading, the data may be wrong.

I have a pull request open for this but as I write this I realise that this is quite a problem. Some options coming to mind:
1. I could disable this message if auto-update is disabled
2. I could force-update the diagram first, but I think this is a bad idea. Imagine you have a huge diagram the browser can't handle, you may want to bypass the browser and generate on the server so it doesn't crash the browser.
3. I could create a new API endpoint and request the info on the diagram separately from the download. However, this would require the server to crawl all the family links and generate the DOT file twice, once for the download and once for the message. This seems like a bad idea.

It's late here but I will keep thinking about this. Option 1 seems like the most pragmatic.

I think it also may be possible to do the messages if client-side rendering is used (since info is passed from server to browser the same way as loading the browser render), but that needs a bit of research. 

Ideas from anyone are welcome!

**Comment by Neriderc** [comment]
I think I have solved this. I create a token based on the time, and include that with the form information used to generate the diagram. When generating the diagram, I store the number of families and individuals in the webtrees preferences.

At the same time as this is happening, clicking the download button starts a check every 0.5 seconds where it sends that same token to the server and asks if the token matches the one sent in the form. Once it is successful, it gets the numbers stored on the server and presents them in a message.

In some cases it will not be successful ever, probably when you click the download button too many times in a hurry. But in this case it silently fails and you will not see a message (or will only see one message when you clicked 3 times quickly). I think this is ok.

In case you are wondering, it seems to be impossible for the page to tell when the download has started, the browser doesn't let the website access this information. Large diagrams can take 10 seconds or more to finish generating so a polling system and token like this was needed rather than just waiting a second and assuming it was done.

One further complication is guests. I can use the same system, but all logged out users would have their information stored in the same place, overwriting each other. If two logged out users clicked their download button at the same time one might get a message intended for the other.

I am thinking it might be best to disable these messages for logged out users, to be safe.

**Comment by Neriderc** [comment]
This is complete, more info on implementation in #532

**Comment by elysch** [comment]
Great work. Never thought it would be that complicated.  :D

Thank you
