### ISSUE TITLE
Use tree option to show or not to show thumnails

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#54]
For each tree in webtrees there is an option in the control panel indicating if thumbnails should be shown. GVExport should respect this and should not show the option "add photos" in the UI if this tree option is set to "no".

There is now a function "isTreePreferenceShowingThumbnails" available in functions_dot.php that can be used to check this setting.

In "simple" mode thumbnails cannot be used. So it would be better to gray-out the "add photos" checkbox if "simple" is selected.

**Comment by Neriderc** [comment]
Done!
