### ISSUE TITLE
Error: Call to undefined method Fisharebest\Webtrees\Registry::container()

### ISSUE THREAD

**Issue by aelmahdi** [Neriderc/GVExport#543]
After upgrading to GVExport Version  2.2.1 I got this exception.

Fatal error in module: GVExport
Error: Call to undefined method Fisharebest\Webtrees\Registry::container() in /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/modules_v4/GVExport/module.php:436 Stack trace: #0 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Services/ModuleService.php(737): include() #1 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Services/ModuleService.php(711): Fisharebest\Webtrees\Services\ModuleService::load() #2 [internal function]: Fisharebest\Webtrees\Services\ModuleService::Fisharebest\Webtrees\Services\{closure}() #3 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/vendor/illuminate/collections/Collection.php(695): array_map() #4 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Services/ModuleService.php(710): Illuminate\Support\Collection->map() #5 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Services/ModuleService.php(632): Fisharebest\Webtrees\Services\ModuleService->customModules() #6 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Cache.php(58): Fisharebest\Webtrees\Services\ModuleService->Fisharebest\Webtrees\Services\{closure}() #7 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/vendor/symfony/cache/Adapter/ArrayAdapter.php(84): Fisharebest\Webtrees\Cache::Fisharebest\Webtrees\{closure}() #8 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Cache.php(55): Symfony\Component\Cache\Adapter\ArrayAdapter->get() #9 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Services/ModuleService.php(622): Fisharebest\Webtrees\Cache->remember() #10 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Services/ModuleService.php(583): Fisharebest\Webtrees\Services\ModuleService->all() #11 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Http/Middleware/UseLanguage.php(82): Fisharebest\Webtrees\Services\ModuleService->findByInterface() #12 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Http/Middleware/UseLanguage.php(61): Fisharebest\Webtrees\Http\Middleware\UseLanguage->languages() #13 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process() #14 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle() #15 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process() #16 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle() #17 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process() #18 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher->handle() #19 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process() #20 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Http/Middleware/BadBotBlocker.php(308): Middleland\Dispatcher->handle() #21 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process() #22 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Http/Middleware/CompressResponse.php(71): Middleland\Dispatcher->handle() #23 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process() #24 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle() #25 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process() #26 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle() #27 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process() #28 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process() #29 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Http/Middleware/HandleExceptions.php(89): Middleland\Dispatcher->handle() #30 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process() #31 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Http/Middleware/SecurityHeaders.php(49): Middleland\Dispatcher->handle() #32 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process() #33 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle() #34 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process() #35 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle() #36 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process() #37 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle() #38 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process() #39 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #40 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Webtrees.php(276): Middleland\Dispatcher->dispatch() #41 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/app/Webtrees.php(263): Fisharebest\Webtrees\Webtrees::dispatch() #42 /var/www/vhosts/takiah.co.uk/family.takiah.co.uk/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest() #43 {main}

**Comment by Neriderc** [comment]
Thanks for reporting this, can I ask which version of webtrees you are using? The version can be found at the top of the webtrees control panel page.

**Comment by yann64** [comment]
Same issue on all websites I installed GVExport  release 2.2.1.
All websites are Webtrees version 2.1.21

**Comment by Neriderc** [comment]
Hi @yann64, as stated on the release page, GVExport 2.2.1 requires the latest webtrees, 2.2.0. It does not support webtrees 2.1 versions.

There is a GVExport 2.1.23 released at the same time that supports webtrees 2.1 versions, and you can grab it here: https://github.com/Neriderc/GVExport/releases/tag/v2.1.23

But please note that GVExport is only developed for the latest version of webtrees. Future versions will require webtrees 2.2.0 or later.

**Comment by Neriderc** [comment]
Hi all, now some other modules are being updated I've looked at how they have handled this. GVExport should now support both versions of webtrees again. Hopefully this helps.
