### ISSUE TITLE
Privacy settings in favorites html block

### ISSUE THREAD

**Issue by elysch** [Neriderc/GVExport#544]
I decided to hide all information to no authenticated visitors but the html block block doesn't respect that as you can see in the middle box of the following image. It shows the names of the settings that obviously have last names in them

![Screenshot_20241130-070641-930](https://github.com/user-attachments/assets/62089232-8dfb-401c-8186-86f0cc0d659b)

**Comment by Neriderc** [comment]
The favourites block is a component of webtrees, not GVExport. If you don't want visitors to see any of the favourites, then you can change this in the control panel. In the control panel, in the Modules section, find the Blocks type and click on this. Then look for the Favourites block. Click the edit button to change who can see it.

**Comment by elysch** [comment]
Found it.

Thank you.
