### ISSUE TITLE
Preferred name marked with asterisk should be displayed as underlined like in webtrees

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#6]
A preferred name marked with an asterisk should be displayed as underlined when generating the GVExport diagram. This is to match the way webtrees displays it.

**Comment by hartenthaler** [comment]
I would prefer to underline the preferred given name.

**Comment by schuco** [comment]
I don't quite understand the headline of this issue "Preferred name marked with asterisk displays with asterisk at start of name".
In  my case where a given name is followed by * GVExport seems to neglect this - it does not "display with asterisk at start of name".
I support @hartenthaler to underline the preferred given name.

**Comment by Neriderc** [comment]
I've just been digging into this, and worked out that embarrassingly I never committed the change to show the asterisk into a repository, I only ever made the change locally on my production server, and it's now been overwritten by updating it with new releases.

It wasn't that great anyway so I won't bother redoing it, instead I will aim for what we want, which is for the name to be underlined. I have renamed the issue and reworded the original post.
