### ISSUE TITLE
Error if the clippings cart is not empty, but did not contain an INDI

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#60]
This is possible if you add for example only a source and no individuals to the clippings cart. This results in an error. A pull request to overcome this problem is on the way.

**Comment by Neriderc** [comment]
After merging I noticed the pull request may have removed lines from page.phtml causing the bug in #62. Although I can't seem to reproduce the bug, I'm going to add those lines back in and get them to retest.

**Comment by hartenthaler** [comment]
The following lines have to be removed from page.phtml:
```
        $cart = Session::get('cart', []);
        $xrefs = array_keys($cart[$tree->name()] ?? []);
        $cartempty = sizeof($xrefs) == 0;
```
because it is not about if the clippings cart is empty, it is about if there are no INDI records in it. This was my fault. For GVExport it is important if there is at least one person in the clippings cart, this person can be shown by GVExport. If there are only other record types in the clippings cart, then GVExport cannot show anything, so the "People to be included" standard part should be active.

The variable $cartempty in page.phtml (can be renamed to noIndiInCart, maybe) is now set in module.php in line #192. To make the code clearer, all complicated calcuöations should be done outside of a view function. So page.phtml should have nearly no PHP code, only simple if-then-else. page.html should concentrate on the UI using HTML and JavaScript. The CSS code should be moved to a separate file.
