### ISSUE TITLE
BUG?

### ISSUE THREAD

**Issue by yako1984** [Neriderc/GVExport#62]
```
Undefined variable $cartempty …/modules_v4/GVExport/resources/views/page.phtml:117
#0 …/modules_v4/GVExport/resources/views/page.phtml(117): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
#1 …/app/View.php(183): include('...')
#2 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#3 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#4 …/app/Http/ViewResponseTrait.php(50): view()
#5 …/modules_v4/GVExport/module.php(192): Fisharebest\Webtrees\Module\AbstractModule->viewResponse()
#6 …/app/Http/RequestHandlers/ModuleAction.php(85): vendor\WebtreesModules\gvexport\GVExport->getChartAction()
#7 …/app/Http/Middleware/RequestHandler.php(54): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle()
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
#9 …/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher->handle()
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#11 …/app/Module/CheckForNewVersion.php(115): Middleland\Dispatcher->handle()
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process()
#13 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle()
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#15 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#16 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#17 …/app/Http/Middleware/Router.php(153): Fisharebest\Webtrees\Webtrees::dispatch()
#18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#19 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle()
#20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#21 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
#22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
#23 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#25 …/app/Http/Middleware/CheckForNewVersion.php(65): Middleland\Dispatcher->handle()
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process()
#27 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#28 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#29 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#31 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#33 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
#34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#35 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#37 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle()
#38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#39 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle()
#40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#41 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#43 …/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle()
#44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#45 …/app/Http/Middleware/BadBotBlocker.php(233): Middleland\Dispatcher->handle()
#46 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#47 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
#48 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#49 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
#50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#51 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
#52 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#54 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#56 …/app/Http/Middleware/BaseUrl.php(79): Middleland\Dispatcher->handle()
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#58 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#59 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#60 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#61 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#62 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#63 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#64 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#65 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#66 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#67 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#68 {main}
```

**Comment by yako1984** [comment]
Hello, you are very fast. Now it works and it creates the graphics for me. there are only minor errors but they do not affect the operation. I attach screenshot

![Screenshot_1](https://user-images.githubusercontent.com/67491705/175178065-d4116996-4fdd-494a-84e8-d3bd7f570841.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/67491705/175178082-5cf1d95e-2cf4-458f-a015-9472952b6069.jpg)
s

**Comment by Neriderc** [comment]
It's very odd. I'm using the latest webtrees (2.1.6), the same version of PHP as you ( 8.1.7), and I disabled the clippings cart to test but mine functions fine without it. You _are_ using some different PHP settings, so that's where I'm thinking the problem is. There seems to be something in common between the bits of code you are using, so I have an idea of what it might be. 

I've made a change that may fix it. Are you comfortable with cloning from master? If so, could you test out the change I've just made? If not, I can package up a new release for you.

**Comment by yako1984** [comment]
Unmatched '}' …/modules_v4/GVExport/resources/views/page.phtml:119
#0 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#1 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#2 …/app/Http/ViewResponseTrait.php(50): view()
#3 …/modules_v4/GVExport/module.php(193): Fisharebest\Webtrees\Module\AbstractModule->viewResponse()
#4 …/app/Http/RequestHandlers/ModuleAction.php(85): vendor\WebtreesModules\gvexport\GVExport->getChartAction()
#5 …/app/Http/Middleware/RequestHandler.php(54): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle()
#6 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
#7 …/modules_v4/reminder/src/Modules/ReminderModule.php(97): Middleland\Dispatcher->handle()
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Reminder\Modules\ReminderModule->process()
#9 …/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher->handle()
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#11 …/app/Module/CheckForNewVersion.php(115): Middleland\Dispatcher->handle()
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process()
#13 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle()
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#15 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#16 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#17 …/app/Http/Middleware/Router.php(153): Fisharebest\Webtrees\Webtrees::dispatch()
#18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#19 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle()
#20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#21 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
#22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
#23 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#25 …/app/Http/Middleware/CheckForNewVersion.php(65): Middleland\Dispatcher->handle()
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process()
#27 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#28 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#29 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#31 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#33 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
#34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#35 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#37 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle()
#38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#39 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle()
#40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#41 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#43 …/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle()
#44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#45 …/app/Http/Middleware/BadBotBlocker.php(233): Middleland\Dispatcher->handle()
#46 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#47 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
#48 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#49 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
#50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#51 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
#52 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#54 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#56 …/app/Http/Middleware/BaseUrl.php(79): Middleland\Dispatcher->handle()
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#58 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#59 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#60 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#61 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#62 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#63 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#64 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#65 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#66 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#67 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#68 {main}

**Comment by Neriderc** [comment]
Progress! The change I made should have done nothing unless it was causing the issue :)

Can you try again, I've just made further changes.

**Comment by yako1984** [comment]
Progress! The change I made should have done nothing unless it was causing the issue :)

Can you try again, I've just made further changes.

**Comment by yako1984** [comment]
Progress! The change I made should have done nothing unless it was causing the issue :)

Can you try again, I've just made further changes.

**Comment by Neriderc** [comment]
That would be great, thanks!
