### ISSUE TITLE
Option "Include" / "Cousins"

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#79]
This option is only used if the option "Siblings" is set. So if "Siblings" is not selected, then "Cousins" should be greyed-out.

And a remark: in English there are several types of cousins (male/femal) so they are both included when selecting "Cousins". Ok. But in German for example there are "Cousin" = male cousins and "Cousinen" = female cousins so the translation is a bit longer ("cousins translates to "Cousins und Cousinen").

And another remark: it is not only about cousins: if you select the option "cousins" then you will see all the cousins, but Nieces and Nephews, too.

**Comment by Neriderc** [comment]
I think this was mentioned in another issue but I'm not sure if there was a top level issue for it. I'll have a look if I find the time.

But I think the solution here is to rename "cousins" to all relations, probably to automatically select "siblings" if you choose "all relations" (and automatically un-select all relayions if you uncheck siblings).

Greying out might be an option but I feel the automatic checking/unchecking might feel better. It might be something to test to see how the different options feel when using them.

**Comment by hartenthaler** [comment]
good ideas!
