### ISSUE TITLE
Comments on actual implementation of GVExport

### ISSUE THREAD

**Issue by schuco** [Neriderc/GVExport#80]
As I work with GVExport since PhpGedView I would like to contribute to the wiki and also propose some minor improvements. I stick with webtrees 2.0.23, therefore could not install the actual version yet.
But only from what I could read in the wiki of this repository I congratulate that you have achieved much progress in functionality and correctness.
I also read the manual page in GenWiki in German language which is very clear and almost complete.
[wiki.genealogy.net/Webtrees_Handbuch/Anl...rungsmodule/GVExport](https://wiki.genealogy.net/Webtrees_Handbuch/Anleitung_f%C3%BCr_Webmaster/Erweiterungsmodule/GVExport)]
I added only some few points there, reflecting my experience with the outdated module.
As I am completely new in both, Github and GenWiki, I don't know, if my contribution to GenWiki can be used for wiki in Github.

**There is one general point I would like to repeat here:**
In my experience GVExport is much more than a tool to produce just printable output. Rather it is extremely efficient to navigate through a pedigree or look at individual pages of specific persons. It is also very effective to identify duplicate persons and to prepare merging them.
So it can be very helpful also for webtree-users without graphviz-installation or without intention to produce printable output.

**I therefore propose** 

- to modify the introducing chapter "About GV Export". At present users without graphviz installed might stop further reading as there is seemingly no use or value for them.
- Another consequence from this point could be to use another term than "Preview" ("Vorschau" in German), for the button at the bottom of the user menu. Pressing this button to produce a complex diagram without the intention to download might be the only use of the module for many users. In my view "Update" or "Update diagram" might be a better button-label.

**Finally** 

- I support #51 to move some options to the control panel, e.g. parameters for persons to be included, direction of diagram, show XRFEF and type of diagram. Output type could be set to DOT by the administrator if graphviz is not installed, otherwise to PDF.

**Comment by Neriderc** [comment]
> **There is one general point I would like to repeat here:** In my experience GVExport is much more than a tool to produce just printable output. Rather it is extremely efficient to navigate through a pedigree or look at individual pages of specific persons. It is also very effective to identify duplicate persons and to prepare merging them. So it can be very helpful also for webtree-users without graphviz-installation or without intention to produce printable output.

Thanks for this insight, I hadn't thought of it like that but you're right, it is a handy way to browse the tree even if you don't want to download output.

> **I therefore propose**
> 
>     * to modify the introducing chapter "About GV Export". At present users without graphviz installed might stop further reading as there is seemingly no use or value for them.

That sounds like a good idea. I'll look at rephrasing this.

>     * Another consequence from this point could be to use another term than "Preview" ("Vorschau" in German), for the button at the bottom of the user menu. Pressing this button to produce a complex diagram without the intention to download might be the only use of the module for many users. In my view "Update" or "Update diagram" might be a better button-label.

It was previously "Update", I think it's best to switch back to this as we will already have translations in a lot of cases. It was updated to "Preview" at the same time we changed "Render server side" to "Download", wanting to move away from the client/server side distinction and instead handle it in the backend. I think using "Update" should still fit within this so I've created #81 and we'll change this.

>     * I support [Move some options to the control panel #51](https://github.com/Neriderc/GVExport/issues/51) to move some options to the control panel, e.g. parameters for persons to be included, direction of diagram, show XRFEF and type of diagram. Output type could be set to DOT by the administrator if graphviz is not installed, otherwise to PDF.

In the latest version, there's a few changes to how this is handled (which is a very recent change and isn't bundled into a release yet, though I note you're not using the version from this repository). See issue #76. We actually check if GraphViz is installed, and DOT is the only output format if GraphViz is not found. If it is found, we then list the other options. My hope is that we will work out how to get some of the output types without GraphViz installed, then in this case we can have a short list if no GraphViz or a longer one if GraphViz is installed.

**Comment by hartenthaler** [comment]
The German manual page was already updated: https://wiki.genealogy.net/Webtrees_Handbuch/Anleitung_f%C3%BCr_Webmaster/Erweiterungsmodule/GVExport

So I did only some minor fine-tuning. I will update the whole page just after the next release of GVExport.

**Comment by Neriderc** [comment]
I'll close this as I think the discussion has run it's course.
