### ISSUE TITLE
Missing items for translation

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#97]
I'm missing the following strings in the po/mo website
- Use cart
- Ignore cart
- All relatives

**Comment by Neriderc** [comment]
Thanks, I've added these terms to the POEditor.com project.

 @yako1984 @TheDutchJewel it would be great to have these extra terms updated!

And if anyone is able to update the translations for other languages, please do. There are others there where the users haven't identified themselves on Github so I can't tag them.

I'll leave this for some time so translations can be updated. Feel free to create pull requests with the updated .po/.mo files, otherwise I'll pull new copies of them before the next release.

**Comment by TheDutchJewel** [comment]
> Use cart
> Ignore cart

To translate this properly, I need to know what is meant by `cart`.

Can you explain that?

**Comment by Neriderc** [comment]
> > Use cart
> > Ignore cart
> 
> To translate this properly, I need to know what is meant by `cart`.
> 
> Can you explain that?

Sure! This is referring to the webtrees "clippings cart". In webtrees, there are various options along the top. "Family trees", "Charts", "Reports", etc. One of these is "Clippings cart".

The clippings cart allows you to go to an individual's page and add that person to the "cart". You can add lots of people to the clippings cart, and GVExport will find these people and allow you to create a diagram from them. Or you might want to ignore them and use the normal options. These options let you either use the individuals in the "clippings cart", or to ignore these people and use GVExport as normal.

For translating, perhaps look at what webtrees uses for the clippings cart as a starting point.

**Comment by TheDutchJewel** [comment]
Thank you!

So why not use 'clippings cart' instead of 'cart'?

**Comment by Neriderc** [comment]
That's a good question! When you have an item in the clippings cart that triggers this option, there is another message above that mentions it's related to the clippings cart:
![image](https://user-images.githubusercontent.com/89974636/181420586-33e3f89e-93f5-4c3f-bb12-38bf58a1a20f.png)

The shortened version is really just so you don't have "clippings cart" listed 4 times in quick succession. But I'm curious for some other opinions here, is it clear enough as is or would it be better to list "Use clippings cart" and "Ignore clippings cart" to be clearer? Anyone else want to weigh in on this?

**Comment by TheDutchJewel** [comment]
>When you have an item in the clippings cart that triggers this option, there is another message above that mentions it's related to the clippings cart

Aha! My clippings cart was empty, that's why I did'n't see this option. 

Anyway, in Dutch is the same word used for 'clippings cart' and 'cart' in webtrees: 'stamboomknipsels'. So I hope there's enough space in the selection box for the text.

**Comment by Neriderc** [comment]
That shouldn't be a problem, there should be plenty of space. Thanks for updating!

**Comment by hartenthaler** [comment]
I had the same idea as TheDutchJewel when translating those strings. You can replace the second "clippings cart" with "those" ("these"?) to have one repetition less, resulting in "You have items in the clippings cart, so those items will be used ....".

**Comment by Neriderc** [comment]
Does this look better?
![image](https://user-images.githubusercontent.com/89974636/181650079-0baeb5d3-d634-451c-8e96-374ad44ae1bb.png)

Or is the original better?
![image](https://user-images.githubusercontent.com/89974636/181420586-33e3f89e-93f5-4c3f-bb12-38bf58a1a20f.png)

I'm thinking the new one may be better.

**Comment by TheDutchJewel** [comment]
The new one looks better to me.

**Comment by hartenthaler** [comment]
For me, the new one is better, too.

**Comment by Neriderc** [comment]
Great, I've added the terms to POEditor. I'll update the code before the next release. I have slightly changed the term, using "can" instead of "may" because I felt "can" gives more of a sense that it's up to the user to decide.
